### ISSUE TITLE
Build fails on RHEL9 family os'es

### ISSUE THREAD

**Issue by tuxmaster5000** [atlassian-api/atlassian-python-api#1005]
Error:
```
==================================== ERRORS ====================================
_____________________ ERROR collecting tests/test_base.py ______________________
ImportError while importing test module '/builddir/build/BUILD/atlassian-python-api-3.25.0/tests/test_base.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_base.py:4: in <module>
    from atlassian import Jira, Confluence, Bitbucket, Bamboo, Crowd, ServiceDesk, Xray
atlassian/__init__.py:1: in <module>
    from .bamboo import Bamboo
atlassian/bamboo.py:5: in <module>
    from .rest_client import AtlassianRestAPI
atlassian/rest_client.py:6: in <module>
    from oauthlib.oauth1 import SIGNATURE_RSA
E   ImportError: cannot import name 'SIGNATURE_RSA' from 'oauthlib.oauth1' (/usr/lib/python3.9/site-packages/oauthlib/oauth1/__init__.py)
```
On RHEL-8 it will works out of the box.

**Comment by gonchik** [comment]
This weekend will check

**Comment by gonchik** [comment]
@tuxmaster5000  I have been checked that is working well on Oracle linux 9.

**Comment by tuxmaster5000** [comment]
I try it again today and it fails. I looks like Oracle Linux is modifying the default crypto policies, because SHA1 is disabled by default on RHEL9. So this call must fails. Using an SHA2 algo will fix it.
d```
iff -Nuar atlassian-python-api-3.25.0.org/atlassian/rest_client.py atlassian-python-api-3.25.0/atlassian/rest_client.py
--- atlassian-python-api-3.25.0.org/atlassian/rest_client.py	2022-09-17 13:49:12.846072116 +0200
+++ atlassian-python-api-3.25.0/atlassian/rest_client.py	2022-09-17 13:51:05.720241167 +0200
@@ -3,7 +3,7 @@
 from json import dumps
 
 import requests
-from oauthlib.oauth1 import SIGNATURE_RSA
+from oauthlib.oauth1 import SIGNATURE_RSA_SHA512
 from requests_oauthlib import OAuth1, OAuth2
 from six.moves.urllib.parse import urlencode
 from requests import HTTPError
@@ -102,7 +102,7 @@
         oauth = OAuth1(
             oauth_dict["consumer_key"],
             rsa_key=oauth_dict["key_cert"],
-            signature_method=SIGNATURE_RSA,
+            signature_method=SIGNATURE_RSA_SHA512,
             resource_owner_key=oauth_dict["access_token"],
             resource_owner_secret=oauth_dict["access_token_secret"],
         )

```

**Comment by tuxmaster5000** [comment]
The fix as an patch file.
[fix.zip](https://github.com/atlassian-api/atlassian-python-api/files/9591595/fix.zip)

**Comment by gonchik** [comment]
@tuxmaster5000  you can send a PR/MR request, that's quite easier I think so :)

**Comment by tuxmaster5000** [comment]
Here it is, and very simple.

**Comment by gonchik** [comment]
Meanwhile: I will put that information into release
https://developer.atlassian.com/cloud/jira/platform/jira-rest-api-oauth-authentication/

**Comment by gonchik** [comment]
Hm, that one had been patched by you @tuxmaster5000

**Comment by tuxmaster5000** [comment]
In  next release my patch was modified, by an patch from another user, so the build was failed again.
And the path from the other user must fixed again for RHEL-9

**Comment by gonchik** [comment]
@tuxmaster5000  let me release the new version
