### ISSUE TITLE
The paged requests are not managed

### ISSUE THREAD

**Issue by danielesiddi** [atlassian-api/atlassian-python-api#101]
Atlassian API returns a paged JSON answer.
This shoulde be managed by wrapper too, extending array with all the results.

**Comment by SLRover** [comment]
Hello!
What method are you using?

**Comment by SLRover** [comment]
I checked it. The request **get_tags** returns a list of dictionaries. Not JSON.
What type of answer are you want to get from API wrapper?

**Comment by danielesiddi** [comment]
Because the atlassian API returns a json with maximum 1000 elements.
If you have more than 1k tag (which, in big projects, is probable), you just receive the first 1k.
So, I think the library should check the isLastPage flag in json API, and join all the values together.

Please check the example Bitbucket JSON
`{"size":25,"limit":25,"isLastPage":false,"values":[]}`

The maximum admitted for limit is 1000

**Comment by SLRover** [comment]
OK! Thanks for the improvement proposal.

**Comment by gonchik** [comment]
@danielesiddi  Please, have a look PR #102 

Now it should be works well.
I have added in log.info level related messages 
Also, use condition like this len(stash.get_tags()) > 0 

Cheers,
Gonchik Tsymzhitov

**Comment by gonchik** [comment]
@danielesiddi  Any tests from your side?

**Comment by danielesiddi** [comment]
Hi. Going to do it today.

**Comment by gonchik** [comment]
@danielesiddi  
I have tested. 
You can see the example here 
https://github.com/gonchik/atlassian-python-api/commit/8a1563ca2b93885869f25a5ed547f703a32913fb
