### ISSUE TITLE
`get_permissions()` fails with `The 'permissions' query parameter is required.`

### ISSUE THREAD

**Issue by leplatrem** [atlassian-api/atlassian-python-api#1015]
With atlassian-python-api 3.25.0

```
>>> from atlassian import Jira
>>> jira = Jira(url="https://xxxx.net", username="yyyy", password="zzzz")
>>> jira.get_permissions()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mathieu/project/.venv/lib/python3.10/site-packages/atlassian/jira.py", line 73, in get_permissions
    return self.get(url, params=params)
  File "/Users/mathieu/project/.venv/lib/python3.10/site-packages/atlassian/rest_client.py", line 270, in get
    response = self.request(
  File "/Users/mathieu/project/.venv/lib/python3.10/site-packages/atlassian/rest_client.py", line 242, in request
    self.raise_for_status(response)
  File "/Users/mathieu/project/.venv/lib/python3.10/site-packages/atlassian/rest_client.py", line 401, in raise_for_status
    raise HTTPError(error_msg, response=response)
requests.exceptions.HTTPError: The 'permissions' query parameter is required.
```

I understand from manual testing that it might use the v3 API, but I also saw:

https://github.com/atlassian-api/atlassian-python-api/blob/0a630a05e0193a172193c7425d50daeaa7d52ec0/atlassian/jira.py#L20-L21

Am I doing something wrong? Thank you.

**Comment by bsieber-mozilla** [comment]
Looking at the [v2](https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-permissions/#api-rest-api-2-mypermissions-get) and [v3](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-permissions/#api-rest-api-3-mypermissions-get) API's for "mypermissions" there appears to be only one `Required` param: permissions.

Permissions is supposed to be a str that exists with comma seperated values that represent Permission key's.

In the python API the call `get_permissions` makes a request to the aforementioned APIs ("/mypermissions" based on the URL's this call is making) however the python API doesn't seem to make it possible to pass the param at this time. 

I believe this would be a minor change/addition to the method signature of a `permissions` param and then providing it to the `param` dict (along with doc changes).
