### ISSUE TITLE
Which SDK to use?

### ISSUE THREAD

**Issue by RosterIn** [atlassian-api/atlassian-python-api#1027]
What is the difference between this SDK and https://github.com/pycontribs/jira/issues if I want to get records from Jira API?
Usually when there are 2 distinct SDKs for the same goal there is a reason

**Comment by gonchik** [comment]
Hi @RosterIn , 

the cause is object oriented request vs functional. 
More raw wrapper instead of complicated one. 

Also, the cause to have 1 package instead many wrappers (confluence, bb, bamboo, marketplace)


Cheers,
GT

**Comment by RosterIn** [comment]
Ah nice. thank you.. would be cool (I think) if this would be explained in the README as this is an important for anyone who decide to use
