### ISSUE TITLE
Is Cloud admin REST APIs in scope of this repository?

### ISSUE THREAD

**Issue by YugoHino** [atlassian-api/atlassian-python-api#1029]
Hi, 

Thank you so much to maintain this repository, our project is helped by it.

I have a question.

Our project uses Jira/Confluence cloud. There is Cloud admin REST APIs for the organization. This API allows us to get such like users in the organization, activities in the organization (audit logs).

https://developer.atlassian.com/cloud/admin/about/

This credentials to call APIs are organization id and token that managed by the organization. So, it's different from Jira, Confluence, and others because of which uses personal access token by each users.
Also, those Cloud admin REST APIs might be only for cloud, on-prem might have those kind of APIs.

On the other hand, this repository name is atlassian-python-api, it sounds including Cloud admin rest APIs as well. 
If it's included in this repository scope, I will try to create a PR for the APIs.

Thanks

**Comment by gonchik** [comment]
Hi, 
I think it's helpful, and why not to implement it :)

**Comment by YugoHino** [comment]
Great. Then I will try to do it.
