### ISSUE TITLE
Confluence CQL question

### ISSUE THREAD

**Issue by securityaspirations** [atlassian-api/atlassian-python-api#104]
Hi,

I am attempting to use cql to search for keywords throughout Confluence. I define the space key to search and then iterate over the results.  Using the following simple search works to some extent: 

`cql = "space.key= {}".format(space)`

However this only produces the 'excerpt' value in the resulting JSON and not the full page. So I am trying to expand the body in each page. Using the following search in the browser against the api returns the full page details as required:

> /rest/api/content/search?cql=space.key=S2&expand=space,body.view

However calling 'cql' via the atlassian-python-api gives the following:

`cql = "space.key={} +and+expand=space,body.view".format(space)`

`{'statusCode': 400, 'data': {'authorized': False, 'valid': True, 'allowedInReadOnlyMode': True, 'errors': [], 'successful': False}, 'message': 'Could not parse cql : space.key=X +and+expand=space,body.view', 'reason': 'Bad Request'}`

So it appears to be having trouble parsing the request - though the equivalent works in the browser. Is this a bug perhaps or am I missing something simple?

Many thanks

**Comment by gonchik** [comment]
Please, let me know if you have other idea.
