### ISSUE TITLE
[confluence] page full_width possible on create but not on update_or_create

### ISSUE THREAD

**Issue by styk-tv** [atlassian-api/atlassian-python-api#1047]
You can see full_width  is possible to set on page_create
https://github.com/atlassian-api/atlassian-python-api/blob/master/atlassian/confluence.py#L703-L705

but not on update_or_create
https://github.com/atlassian-api/atlassian-python-api/blob/master/atlassian/confluence.py#L1729-L1735

could someone please add this simple change next time you're doing the tests. thanks.

**Comment by gonchik** [comment]
Thanks for that @styk-tv 
Added the parameters.
