### ISSUE TITLE
confluence remove_content_history(page_id, version_number) method fails from version 3.26.0

### ISSUE THREAD

**Issue by manoharm28** [atlassian-api/atlassian-python-api#1048]
The method remove_content_history(page_id, version_number) was working fine until the release version **3.25.0**.
From the version **3.26.0** and newer we are getting below error:

File "/usr/local/lib/python3.10/site-packages/atlassian/confluence.py", line 1371, in remove_content_history
    self.delete(url)
  File "/usr/local/lib/python3.10/site-packages/atlassian/rest_client.py", line 371, in delete
    response = self.request(
  File "/usr/local/lib/python3.10/site-packages/atlassian/rest_client.py", line 242, in request
    self.raise_for_status(response)
  File "/usr/local/lib/python3.10/site-packages/atlassian/confluence.py", line 2780, in raise_for_status
    raise HTTPError(error_msg, response=response)
requests.exceptions.HTTPError: null for uri: https://confluence.sdl.com/rest/api/content/*********/version/1

Thank you.

**Comment by gonchik** [comment]
Hi @manoharm28 , 
noted, thanks. 
Let me check it later. 
Could you provide the Confluence version also, I will check on my docker env.

**Comment by manoharm28** [comment]
Hi @gonchik 
Our confluence version is 7.18.2.
We are running it inside docker container with image 'python:3' in Jenkins.

Thanks,
Manohar

**Comment by gonchik** [comment]
Hi @manoharm28 , 
noted. 
I will try to reproduce on my env soon.

**Comment by gonchik** [comment]
Updated and released 
https://github.com/atlassian-api/atlassian-python-
api/blob/dbcd26699745829bf1f2c9e9980ed874322eaf3b/atlassian/confluence.py#L1461

**Comment by gonchik** [comment]
dbcd26699745829bf1f2c9e9980ed874322eaf3b 
it fixed
