### ISSUE TITLE
[JIRA] receive the history of a ticket

### ISSUE THREAD

**Issue by ShadowZone** [atlassian-api/atlassian-python-api#1054]
Hi there,
I currently try to write a script to analyse the avg. ticket age of a team in each ticket status.

Therefore I want to use the ticket history and take the timestamps on each status change (data is available in Jira in the "History" tab).

![image](https://user-images.githubusercontent.com/976282/194041936-2704848c-7ddc-4249-9fd8-6f7c8f94d47c.png)

But I can't find the data if I retrieve the ticket via this package (jira.issue("XX-123") only contains current status).
Is there a way to get the full history of a ticket?

Best Regards
ShadowZone

**Comment by ShadowZone** [comment]
Ok, after analyzing the code I answered this question on my own.
The "History" is actually the changelog and can be requested like so:

`jira.get_issue_changelog("XX-123")`

But that should be added to the docs, I think...

**Comment by gonchik** [comment]
Hi @ShadowZone , 

Could you raise PR which include docs? 

Cheers,
Gonchik
