### ISSUE TITLE
[Confluence Cloud] get_page_as_pdf  is not working

### ISSUE THREAD

**Issue by rootsj** [atlassian-api/atlassian-python-api#1057]
log.error PDF conversion not successful

I used it well until October 6th,
but it's not working since October 7th.

**Comment by glenlobo** [comment]
Facing the same issue.
Throws a message "PDF conversion not successful."

**Comment by Zad2** [comment]
Me too, do you think that's related to https://developer.atlassian.com/cloud/confluence/changelog/#CHANGE-720 ?

**Comment by rootsj** [comment]
Yes, I think it's related.
I'm using it after customizing it temporarily.

**Comment by Zad2** [comment]
@rootsj can you share how you customized it to fix it?

**Comment by rootsj** [comment]
I modified def get_pdf_download_url_for_confluence_cloud of confluence.py.

`            long_running_task = True
            headers = self.form_token_headers
            log.info("Initiate PDF export from Confluence Cloud")
            response = self.get(url, headers=headers, not_json_response=True)
            response_string = response.decode(encoding="utf-8", errors="strict")
            task_id = response_string.split('name="ajs-taskId" content="')[1].split('">')[0]
            poll_url = "/services/api/v1/task/{0}/progress".format(task_id)
            while long_running_task:
                long_running_task_response = confluence.get(poll_url, headers=headers, not_json_response=True)
                long_running_task_response_parts = json.loads(long_running_task_response.decode(
                    encoding="utf-8", errors="strict"
                ))
                percentage_complete = long_running_task_response_parts["progress"]
                is_update_final = long_running_task_response_parts["progress"] == 100
                current_state = long_running_task_response_parts["state"]
                log.info("Sleep for 5s.")
                time.sleep(5)
                log.info("Check if export task has completed.")
                if is_update_final and current_state == "UPLOADED_TO_S3":
                    log.info(percentage_complete)
                    log.info("Downloading content...")
                    log.debug("Extract taskId and download PDF.")
                    download_url = long_running_task_response_parts["result"][6:]
                    long_running_task = False
                elif not is_update_final and current_state == "FAILED":
                    log.error("PDF conversion not successful.")
                    return None
                else:
                    log.info(percentage_complete)`

using def get_page_as_pdf
Then, you can know s3 url for pdf download.

`
s3_url = confluence.get_page_as_pdf(page_id)
response = requests.get(s3_url)
pdf_content = reponse.content
`

If you don't want to modify the lib,
refer to the code and make it separately

**Comment by gonchik** [comment]
@rootsj  Could you send PR please?

**Comment by rootsj** [comment]
@gonchik 
ok. I sent PR.

**Comment by ShakataGaNai** [comment]
Had this issue and patched in the PR manually, it resolved the problem.
