### ISSUE TITLE
update_or_create failing with KeyError: 'metadata' in version 3.31.0

### ISSUE THREAD

**Issue by YevgenyFarber** [atlassian-api/atlassian-python-api#1078]
data object missing the  "metadata": {"properties": {}}, row.
data from create_page method:
`data = {
            "type": type,
            "title": title,
            "space": {"key": space},
            "body": self._create_body(body, representation),
            "metadata": {"properties": {}},
        }`
data from update_page method:
`data = {
            "type": type,
            "title": title,
            "space": {"key": space},
            "body": self._create_body(body, representation),
        }`

**Comment by gonchik** [comment]
6021d76c8c0c6bd317490e1bc508cbff5010d834
