### ISSUE TITLE
[Confluence] how can i get the main body of confluence page?

### ISSUE THREAD

**Issue by command-z-z** [atlassian-api/atlassian-python-api#1085]
when i use following confluence API, i can get many json data, but i can't find the main body of page.
```
page_id = xxxxxxx
data = confluence.get_page_by_id(page_id, expand=None, status=None, version=None)
```
i need this content. So how can i solve this problem, witch methods or API is right for me;)

**Comment by ab623** [comment]
```python
data = confluence.get_page_by_id(83658356, expand="body.view", status=None, version=None)
print(data["body"]["view"]["value"])
```

**Comment by command-z-z** [comment]
> ```python
> data = confluence.get_page_by_id(83658356, expand="body.view", status=None, version=None)
> print(data["body"]["view"]["value"])
> ```

it works for me.Thank you:)

**Comment by gonchik** [comment]
@ab623  thanks for your answer!
