### ISSUE TITLE
Build for RHEL9 fails again

### ISSUE THREAD

**Issue by tuxmaster5000** [atlassian-api/atlassian-python-api#1094]
The problem is that my patch was reverted by
https://github.com/atlassian-api/atlassian-python-api/pull/1087
But RHEL don't support SHA1 any more, so signature_method must be
SIGNATURE_RSA_SHA512

**Comment by tuxmaster5000** [comment]
Now the tests fails with:
atlassian/rest_client.py:10: in <module>
    from oauthlib.oauth1 import SIGNATURE_RSA
E   ImportError: cannot import name 'SIGNATURE_RSA' from 'oauthlib.oauth1' (/usr/lib/python3.9/site-packages/oauthlib/oauth1/__init__.py)

**Comment by gonchik** [comment]
#1095 fixed looks like
