### ISSUE TITLE
[Confluence] Issue in removing content/page history

### ISSUE THREAD

**Issue by upengareri** [atlassian-api/atlassian-python-api#1102]
Module: `confluence.py`
Function: `remove_content_history`
Line : `url = "rest/api/content/{id}/version/{versionNumber}".format(id=page_id, versionNumber=version_number)`

iI looks like the `rest/api/content/{id}/version/{versionNumber}` endpoint is only valid for Confluence Cloud. I used it on Confluence Data Center and it did not work for me. I used `rest/experimental/content/{id}/version/{versionNumber}` and that worked. I am using Confluence version 7.19.3.

**Comment by gonchik** [comment]
Hi! 
You're right. 
Checked on the Confluence 7.19.1. 
That one will help
dbcd266
