### ISSUE TITLE
[Jira] Incorrect URL used by get_issues_for_backlog resulting in 404 also missing parameter options.

### ISSUE THREAD

**Issue by ejohansson** [atlassian-api/atlassian-python-api#1103]
The URL used by [this function](https://github.com/atlassian-api/atlassian-python-api/blob/master/atlassian/jira.py#L4220-L4225) seems to be wrong according to this documentation:
* https://docs.atlassian.com/jira-software/REST/7.0.4/#agile/1.0/board-getIssuesForBacklog
* https://developer.atlassian.com/cloud/jira/software/rest/api-group-board/#api-rest-agile-1-0-board-boardid-backlog-get

This is the message I received trying to call the API using the Jira client:
```
{"message":"null for uri: https://{org}.atlassian.net/rest/agile/1.0/{boardId}/backlog","status-code":404}
```

https://github.com/atlassian-api/atlassian-python-api/blob/fba0f976acf7eb0451cfab86997b0f1a752976ce/atlassian/jira.py#L4224

*Proposing this be changed to:*
```python
        url = "rest/agile/1.0/board/{board_id}/backlog".format(board_id=board_id)
```

**Comment by ejohansson** [comment]
Opened PR here: https://github.com/atlassian-api/atlassian-python-api/pull/1104

**Comment by gonchik** [comment]
Merged. 
Thanks for the request
