### ISSUE TITLE
GitHub release 3.32.2 missing

### ISSUE THREAD

**Issue by pomverte** [atlassian-api/atlassian-python-api#1110]
On [GitHub Release page](https://github.com/atlassian-api/atlassian-python-api/releases/), version 3.32.2 is missing

there is only until [3.32.0](https://github.com/atlassian-api/atlassian-python-api/releases/tag/3.32.0)

On [pypi page](https://pypi.org/project/atlassian-python-api/) : it shows 3.32.2

**Comment by gonchik** [comment]
@pomverte Thanks 
https://github.com/atlassian-api/atlassian-python-api/releases/tag/3.32.2
