### ISSUE TITLE
[Bamboo] Save bamboo chart generated via the rest-api

### ISSUE THREAD

**Issue by ppjmoors** [atlassian-api/atlassian-python-api#1118]
Can you please provide an example on how to save a chart after generating it with

chart(report_key, build_keys, group_by_period, date_filter=None, date_from=None, date_to=None, width=None, height=None, start_index=9, max_results=25)?

It is i.m.o. not clear from the documentation

**Comment by gonchik** [comment]
Hi @ppjmoors , 
at the moment I don't have test env with data to fully verify that methon

**Comment by hograthm** [comment]
@ppjmoors
Once you get a response from `chart()` method:
```
{
    "location": "jfreechart-onetime-7302896146105875461.png",
    "imageMapName": "G59vv_map",
    "imageMap": '<map id="G59vv_map" name="G59vv_map">\n<area shape="poly" coords="374,15,380,15,380,21,374,21,374,15,374,15" title="Unknown was utilized 1250.0 seconds for 9-February-2023" alt="" nohref="nohref"/>\n<area shape="poly" coords="89,261,95,261,95,267,89,267,89,261,89,261" title="Unknown was utilized 230.0 seconds for 26-January-2023" alt="" nohref="nohref"/>\n</map>',
    "width": 400,
    "height": 320,
}
```

We can get a chart image by making another GET request to Bamboo instance:
```
# Request URL
request_url = "https://bamboo.instance.com/chart"
# Payload. filename - "location" parameter from chart() dict
payload = {"filename": chart.get("location")}
# Here I use simpliests Login/Password auth. Dirty, but it works
r = requests.get(request_url, params=payload, auth=(BAMBOO_USERNAME, BAMBOO_PASSWORD))
# Saving r.content (it will be byte string) directly to a file. Also pretty dirty.
with open("chart.png", "wb") as f:
    f.write(r.content)
```

Initiall answed found here: https://community.atlassian.com/t5/Bamboo-questions/What-is-the-Bamboo-REST-API-Chart-Resource-image-quot-location/qaq-p/598733

As far as I understand there is no built-in method in [atlassian-python-api](https://github.com/atlassian-api/atlassian-python-api) to save this charts.

Another way might be to utilize `imageMap` string from `chart()` response and construct plot from this xml-like stuff. It seems like something from https://matplotlib.org/, but I'm not sure about it.

**Comment by ppjmoors** [comment]
Thanks @hograthm
