### ISSUE TITLE
[Confluence] Unable to pass attachment stored in memory to add_attachment method

### ISSUE THREAD

**Issue by dizoncruz** [atlassian-api/atlassian-python-api#1125]
In the official Python library for JIRA docs, JIRA's add_attachment method expects an issue_key and attachment.  It only expects a filename if the attachment is being passed from memory as a StringIO object .
https://jira.readthedocs.io/examples.html#:~:text=.name)-,2.1.11.%20Attachments,-%23

In the Atlassian Python API documentation, the add_attachment method only expects an issue_key and a filename.  This prevents the attachment of files stored only in memory.  
https://atlassian-python-api.readthedocs.io/jira.html

**Comment by gonchik** [comment]
@dizoncruz we can implement it.

**Comment by dizoncruz** [comment]
@gonchik Perfect, thank you!

**Comment by dizoncruz** [comment]
Thank you for implementing this so quickly.  I see that it's been merged to master, but I'm unable to use the new method.

Using apache-airflow-providers-atlassian-jira, which according to the docs utilizes this Atlassian JIRA SDK
https://airflow.apache.org/docs/apache-airflow-providers-atlassian-jira/stable/_api/airflow/providers/atlassian/jira/operators/jira/index.html

Code:
```
from airflow.providers.atlassian.jira.hooks.jira import JiraHook
hook = JiraHook('jira_web_staging')
jira = hook.client

getattr(jira,'add_attachment_object')(issue['key'],attachment=attachment)
```
Log output:
```
<atlassian.jira.Jira object at 0x7f6a28b3b1f0> <class 'atlassian.jira.Jira'>
AttributeError: 'Jira' object has no attribute 'add_attachment_object'
```

**Comment by gonchik** [comment]
@dizoncruz  I did not released yet that. 
Let me collect changes into 1 chunk and make a release.

**Comment by dizoncruz** [comment]
Hi @gonchik, thank you so much for implementing this.  I can confirm that the add_attachment_object method is working as intended.

One last question: the original add_attachment method takes in an optional filename string in cases where the attachment is a StringIO object in memory.  It looks like this new add_attachment_object does not though.  Would that functionality have to be built in as well, or is there another way I pass in a filename string so that the attached file isn't just called "file"?

**Comment by gonchik** [comment]
@dizoncruz  could you send a PR, i would like to see how do you want to implement it.
