### ISSUE TITLE
Running the API under Python 3.11

### ISSUE THREAD

**Issue by dimitris64bit** [atlassian-api/atlassian-python-api#1165]
Hi,

while trying to run the API under Python 3.11, I get the following error:
ImportError: cannot import name 'Mapping' from 'collections'

Even if I fix the import of the collection it breaks on another similar point e.g. importing formatargspec from inspect ...etc..etc.

Is there a new API compatible with Python 3.11?

Regards

**Comment by marcohoepner** [comment]
Hi,

i'm using Python 3.11.3 and langchain version 0.0.166.

My goal is to get content from an confluence system.

First Step:

from langchain.document_loaders import ConfluenceLoader

loader = ConfluenceLoader(
    url="https://xxxxx/wiki",
    username="xxxxx",
    api_key="xxxx"
documents = loader.load(space_key="xxxxx", include_attachments=False, limit=50)

The xxxx are filled with regular parameters.

works fine.

Step 2 :

from langchain.indexes import VectorstoreIndexCreator
index = VectorstoreIndexCreator().from_loaders([loader])

during the execution i get the follow error messages

ValueError                                Traceback (most recent call last)
Cell In[15], line 2
      1 from langchain.indexes import VectorstoreIndexCreator
----> 2 index = VectorstoreIndexCreator().from_loaders([loader])

File c:\Python311\Lib\site-packages\langchain\indexes\vectorstore.py:72, in VectorstoreIndexCreator.from_loaders(self, loaders)
     70 docs = []
     71 for loader in loaders:
---> 72     docs.extend(loader.load())
     73 return self.from_documents(docs)

File c:\Python311\Lib\site-packages\langchain\document_loaders\confluence.py:194, in ConfluenceLoader.load(self, space_key, page_ids, label, cql, include_restricted_content, include_archived_content, include_attachments, include_comments, limit, max_pages)
    166 """
    167 :param space_key: Space key retrieved from a confluence URL, defaults to None
    168 :type space_key: Optional[str], optional
   (...)
    191 :rtype: List[Document]
    192 """
    193 if not space_key and not page_ids and not label and not cql:
--> 194     raise ValueError(
    195         "Must specify at least one among `space_key`, `page_ids`,"
    196         "`label`, `cql` parameters."
    197     )
    199 docs = []
    201 if space_key:

ValueError: Must specify at least one among `space_key`, `page_ids`,`label`, `cql` parameters.

Form my point of view the space_key is set in Step1.

It would be awesome if you can support this case.

Best Regards
Marco

**Comment by gonchik** [comment]
Hi @dimitris64bit , 
checks on servers with 3.11 it works well. 
Suddenly on the github actions I see problem with mypy.

**Comment by CosmaP** [comment]
I have the same (ish) issue with the Jira import   (from atlassian import Jira)    ImportError: cannot import name 'formatargspec' from 'inspect'   The full error is 

Traceback (most recent call last):
  File "c:\Documents\!-Synced\OneDrive\!-DevProjects\Jira\Connect_to_Jira_03.py", line 8, in <module>
    from atlassian import Jira
  File "C:\Program Files\Python311\Lib\site-packages\atlassian\__init__.py", line 2, in <module>
    from .bitbucket import Bitbucket
  File "C:\Program Files\Python311\Lib\site-packages\atlassian\bitbucket\__init__.py", line 4, in <module>
    from deprecated import deprecated
  File "C:\Users\Cosma.papouis\AppData\Roaming\Python\Python311\site-packages\deprecated\__init__.py", line 15, in <module>
    from deprecated.classic import deprecated
  File "C:\Users\Cosma.papouis\AppData\Roaming\Python\Python311\site-packages\deprecated\classic.py", line 15, in <module> 
    import wrapt
  File "C:\Users\Cosma.papouis\AppData\Roaming\Python\Python311\site-packages\wrapt\__init__.py", line 10, in <module>     
    from .decorators import (adapter_factory, AdapterFactory, decorator,
  File "C:\Users\Cosma.papouis\AppData\Roaming\Python\Python311\site-packages\wrapt\decorators.py", line 34, in <module>   
    from inspect import ismethod, isclass, formatargspec
ImportError: cannot import name 'formatargspec' from 'inspect' (C:\Program Files\Python311\Lib\inspect.py)
 Cosma.Papouis@POA-PF3FXE9F  C:  Documents  !-Synced  OneDrive  !-DevProjects  Jira   

**Comment by gonchik** [comment]
@dimitris64bit  @CosmaP  now it it github check we have shown,
