### ISSUE TITLE
[Confluence] using update_page() does not update page, version and comment

### ISSUE THREAD

**Issue by nnako** [atlassian-api/atlassian-python-api#1181]
Hi,

I'm trying to update an existing Confluence page using the function `update_page()`. The page does not show any added `version` and `version comment` even though I set the argument `always_update=True` .

The function just returns the old page content. no error message, no warning, nothin to show me that my request was not answered properly.

When I upload an attachment to this "updated" page, it correctly gets appended to the list of attachments, though.

Are there any hidden tricks in order to properly update an existing page? and correctly set  the `version` and `version comment`?

**Comment by gonchik** [comment]
Hi! 
Nope, it should not be a problem. 
Could you share your Confluence env details please ?
is this Cloud or DC or Server ? 
Version if it's on prem 

Cheers,
GT

**Comment by nnako** [comment]
it seems to be the case that the API checks for actual changes. If I try to overwrite page content while the page content didn't change, the mentioned values don't get updated. Which makes sense.

Thanks.
