### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by simonprydden** [atlassian-api/atlassian-python-api#1192]
Hi, 

I'm having issue install atlassian-python-api on AWS MWAA environment with a requirement file that contains the following lines.
--find-links /usr/local/airflow/plugins
--no-index

This is the error i'm getting, both file exist in the plugins folder.  Only think I have noticed is that atlassian installs 1st

2023-06-23 20:48:43 Processing ./plugins/atlassian-python-api-3.39.0.tar.gz
2023-06-23 20:48:43   Installing build dependencies: started
2023-06-23 20:48:44   Installing build dependencies: finished with status 'error'
2023-06-23 20:48:44   error: subprocess-exited-with-error
2023-06-23 20:48:44   
2023-06-23 20:48:44   × pip subprocess to install build dependencies did not run successfully.
2023-06-23 20:48:44   │ exit code: 1
2023-06-23 20:48:44   ╰─> [4 lines of output]
2023-06-23 20:48:44       Looking in links: /usr/local/airflow/plugins
2023-06-23 20:48:44       Processing ./plugins/setuptools-66.1.1-py3-none-any.whl
2023-06-23 20:48:44       ERROR: Could not find a version that satisfies the requirement wheel (from versions: none)
2023-06-23 20:48:44       ERROR: No matching distribution found for wheel
2023-06-23 20:48:44       [end of output]
2023-06-23 20:48:44   
2023-06-23 20:48:44   note: This error originates from a subprocess, and is likely not a problem with pip.
2023-06-23 20:48:44 error: subprocess-exited-with-error
2023-06-23 20:48:44 
2023-06-23 20:48:44 × pip subprocess to install build dependencies did not run successfully.
2023-06-23 20:48:44 │ exit code: 1
2023-06-23 20:48:44 ╰─> See above for output.
2023-06-23 20:48:44 
2023-06-23 20:48:44 note: This error originates from a subprocess, and is likely not a problem with pip.
2023-06-23 20:48:44 
2023-06-23 20:48:44 [notice] A new release of pip available: 22.3.1 -> 23.1.2
2023-06-23 20:48:44 [notice] To update, run: pip3 install --upgrade pip

Are we missing a build-system section from the [pyproject.toml](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html)

```
[build-system]
requires = [
    "setuptools >= 65",
    "wheel >= 0.38,
]
build-backend = "setuptools.build_meta"
```

**Comment by djgoku** [comment]
```
2023-06-23 20:48:44 Processing ./plugins/setuptools-66.1.1-py3-none-any.whl
2023-06-23 20:48:44 ERROR: Could not find a version that satisfies the requirement wheel (from versions: none)

```

I don’t think the error is with `atlassian-python-api` but with the wheel for setup tools. I would at the wheel for that.

**Comment by simonprydden** [comment]
With mwaa I can only install upto apache-airflow-providers-atlassian-jira==1.1.0 verion, after this the lib changed.

Breaking changes
Changing atlassian JIRA SDK to official atlassian-python-api SDK (#27633)
https://airflow.apache.org/docs/apache-airflow-providers-atlassian-jira/stable/index.html#id5


Since moving to the offical SDK, we can not install in VPC only setup.

**Comment by simonprydden** [comment]
Here is a reproducable example


```dockerfile
FROM python:latest

WORKDIR /usr/src/app
RUN python3 -m pip download --src="/usr/src/app" atlassian-python-api
RUN python3 -m pip install --no-index --find-links="/usr/src/app" atlassian-python-api
```

```
6 [3/4] RUN python3 -m pip download --src="/usr/src/app" atlassian-python-api
#6 1.316 Collecting atlassian-python-api
#6 1.396   Downloading atlassian-python-api-3.39.0.tar.gz (157 kB)
#6 1.435      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 157.5/157.5 kB 4.2 MB/s eta 0:00:00
#6 1.455   Installing build dependencies: started
#6 2.881   Installing build dependencies: finished with status 'done'
#6 2.882   Getting requirements to build wheel: started
#6 3.016   Getting requirements to build wheel: finished with status 'done'
#6 3.019   Preparing metadata (pyproject.toml): started
#6 3.149   Preparing metadata (pyproject.toml): finished with status 'done'
#6 3.193 Collecting deprecated (from atlassian-python-api)
#6 3.209   Downloading Deprecated-1.2.14-py2.py3-none-any.whl (9.6 kB)
#6 3.267 Collecting requests (from atlassian-python-api)
#6 3.284   Downloading requests-2.31.0-py3-none-any.whl (62 kB)
#6 3.305      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 kB 2.9 MB/s eta 0:00:00
#6 3.335 Collecting six (from atlassian-python-api)
#6 3.349   Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
#6 3.384 Collecting oauthlib (from atlassian-python-api)
#6 3.404   Downloading oauthlib-3.2.2-py3-none-any.whl (151 kB)
#6 3.445      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 151.7/151.7 kB 4.1 MB/s eta 0:00:00
#6 3.473 Collecting requests-oauthlib (from atlassian-python-api)
#6 3.490   Downloading requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
#6 3.629 Collecting wrapt<2,>=1.10 (from deprecated->atlassian-python-api)
#6 3.643   Downloading wrapt-1.15.0-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (78 kB)
#6 3.667      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.9/78.9 kB 3.9 MB/s eta 0:00:00
#6 3.777 Collecting charset-normalizer<4,>=2 (from requests->atlassian-python-api)
#6 3.796   Downloading charset_normalizer-3.1.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (197 kB)
#6 3.843      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 197.3/197.3 kB 4.2 MB/s eta 0:00:00
#6 3.875 Collecting idna<4,>=2.5 (from requests->atlassian-python-api)
#6 3.887   Downloading idna-3.4-py3-none-any.whl (61 kB)
#6 3.908      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 3.2 MB/s eta 0:00:00
#6 3.965 Collecting urllib3<3,>=1.21.1 (from requests->atlassian-python-api)
#6 3.977   Downloading urllib3-2.0.3-py3-none-any.whl (123 kB)
#6 4.013      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.6/123.6 kB 3.7 MB/s eta 0:00:00
#6 4.055 Collecting certifi>=2017.4.17 (from requests->atlassian-python-api)
#6 4.068   Downloading certifi-2023.5.7-py3-none-any.whl (156 kB)
#6 4.113      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 157.0/157.0 kB 3.6 MB/s eta 0:00:00
#6 4.149 Saved ./atlassian-python-api-3.39.0.tar.gz
#6 4.150 Saved ./Deprecated-1.2.14-py2.py3-none-any.whl
#6 4.150 Saved ./oauthlib-3.2.2-py3-none-any.whl
#6 4.151 Saved ./requests-2.31.0-py3-none-any.whl
#6 4.151 Saved ./requests_oauthlib-1.3.1-py2.py3-none-any.whl
#6 4.151 Saved ./six-1.16.0-py2.py3-none-any.whl
#6 4.152 Saved ./certifi-2023.5.7-py3-none-any.whl
#6 4.152 Saved ./charset_normalizer-3.1.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
#6 4.153 Saved ./idna-3.4-py3-none-any.whl
#6 4.154 Saved ./urllib3-2.0.3-py3-none-any.whl
#6 4.158 Saved ./wrapt-1.15.0-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl
#6 4.158 Successfully downloaded atlassian-python-api deprecated oauthlib requests requests-oauthlib six certifi charset-normalizer idna urllib3 wrapt
#6 DONE 4.3s

#7 [4/4] RUN python3 -m pip install --no-index --find-links="/usr/src/app" atlassian-python-api
#7 0.554 Looking in links: /usr/src/app
#7 0.582 Processing ./atlassian-python-api-3.39.0.tar.gz
#7 0.603   Installing build dependencies: started
#7 0.886   Installing build dependencies: finished with status 'error'
#7 0.890   error: subprocess-exited-with-error
#7 0.890
#7 0.890   × pip subprocess to install build dependencies did not run successfully.
#7 0.890   │ exit code: 1
#7 0.890   ╰─> [3 lines of output]
#7 0.890       Looking in links: /usr/src/app
#7 0.890       ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)
#7 0.890       ERROR: No matching distribution found for setuptools>=40.8.0
#7 0.890       [end of output]
#7 0.890
#7 0.890   note: This error originates from a subprocess, and is likely not a problem with pip.
#7 0.891 error: subprocess-exited-with-error
#7 0.891
#7 0.891 × pip subprocess to install build dependencies did not run successfully.
#7 0.891 │ exit code: 1
#7 0.891 ╰─> See above for output.
#7 0.891
#7 0.891 note: This error originates from a subprocess, and is likely not a problem with pip.
#7 ERROR: process "/bin/sh -c python3 -m pip install --no-index --find-links=\"/usr/src/app\" atlassian-python-api" did not complete successfully: exit code: 1
------
 > [4/4] RUN python3 -m pip install --no-index --find-links="/usr/src/app" atlassian-python-api:
#7 0.890       [end of output]
#7 0.890
#7 0.890   note: This error originates from a subprocess, and is likely not a problem with pip.
#7 0.891 error: subprocess-exited-with-error
#7 0.891
#7 0.891 × pip subprocess to install build dependencies did not run successfully.
#7 0.891 │ exit code: 1
#7 0.891 ╰─> See above for output.
#7 0.891
#7 0.891 note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by djgoku** [comment]
What is the architecture you are trying to build against?

**Comment by djgoku** [comment]
```
FROM python:latest

RUN pip install atlassian-python-api
```

This works for me.

**Comment by simonprydden** [comment]
I'm on windows, and `pip install atlassian-python-api` works fine, the issue is with an `--no-index`  install.
We use AWS Amazon Managed Workflows for Apache Airflow and to be able to install libraries, we have to package them up into a [plugins.zip](https://docs.aws.amazon.com/mwaa/latest/userguide/best-practices-dependencies.html#best-practices-dependencies-python-wheels-s3) folder, as the webserver conponent does not have internet access.

We pip download atlassian-python-api, zip up the file then using `--no-index` method of pip install. 

Just found these 2 similar issues.
https://github.com/pyinstaller/pyinstaller/issues/4557
https://stackoverflow.com/questions/65712539/pip-install-is-not-recognizing-a-previously-installed-package

Will see if we can add `--no-build-isolation` flag. Do you think there is something missing to be able to build in isolation?

**Comment by gonchik** [comment]
@simonprydden is this still relevant? 
can we add the known issue page into doc ?

**Comment by simonprydden** [comment]
@gonchik yes, I'll still unable to install the library in offline mode. Sorry, I'm still learning python, but would adding build-systems in the pyproject fix this?

**Comment by gonchik** [comment]
@simonprydden  let's try it. 
could you send the PR please?

**Comment by simonprydden** [comment]
@gonchik I'm having some fun trying to get this to work on windows.
But I think have found an easier way.

```python
python -m pip install build twine
python -m build
twine upload dist/*
```

Successfully built atlassian-python-api-0.1.dev1593+g8b21108.tar.gz and atlassian_python_api-0.1.dev1593+g8b21108-py3-none-any.whl

This way I can use the pre-build whl file, would you be able to publish a whl file?

**Comment by gonchik** [comment]
@djgoku  I can do it.
 when you can test it ?

**Comment by gonchik** [comment]
https://pypi.org/project/atlassian-python-api/#files

**Comment by djgoku** [comment]
> @djgoku  I can do it.
> 
>  when you can test it ?

Did you mean to @djgoku me?

**Comment by gonchik** [comment]
Ooops,  @simonprydden   :) 
sorry for bothering you

**Comment by simonprydden** [comment]
I can test it later today. thank you

**Comment by simonprydden** [comment]
Using the whl, worked great thanks. Will uploading the whl be part of the release process now?
```
Processing ./plugins/mypy_boto3_s3-1.28.27-py3-none-any.whl
Processing ./plugins/asgiref-3.7.2-py3-none-any.whl
Processing ./plugins/atlassian_python_api-3.41.0-py3-none-any.whl
Requirement already satisfied: celery<6,>=5.2.3 in ./.local/lib/python3.10/site-packages (from apache-airflow-providers-celery==3.2.1->-r /usr/local/airflow/requirements/requirements.txt (line 7)) (5.2.7)
```

**Comment by gonchik** [comment]
@simonprydden  preparing as bash file for the process of deployment
