### ISSUE TITLE
tests/mockup.py missing from the PyPi source tarball

### ISSUE THREAD

**Issue by WOnder93** [atlassian-api/atlassian-python-api#1206]
The [latest tarball](https://files.pythonhosted.org/packages/b8/75/6090a372e9b1a9221f67be256e517c9e663cfd6bd5426815eb7de03f32b5/atlassian-python-api-3.39.0.tar.gz) doesn't contain the file, without which it is impossible to run the tests.

**Comment by gonchik** [comment]
@WOnder93  it's strange, as I use the standard mechanism of Github to generating tarball. 

I have uploaded a new release, please use it

**Comment by WOnder93** [comment]
Thanks, but I didn't mean the GitHub tarballs (those are fine), but the source tarballs on PyPI (https://pypi.org/project/atlassian-python-api/#files). The 3.40.0 tarball there is till missing the file.

**Comment by gonchik** [comment]
@WOnder93  noted

**Comment by gonchik** [comment]
Hi! 
on that commit extended package directory 8b90689c2bf9a0daf63cb4e8f7c404730707a443

**Comment by gonchik** [comment]
@WOnder93  now it should be ok

**Comment by WOnder93** [comment]
Thanks, but this solution doesn't seem correct. Now the package installs a toplevel `tests` package in addition to `atlassian`, which may conflict with some other package and likely isn't what users expect. Basically, when someone installs this version from PyPI, now they will end up with a `tests` directory under `site-packages` and if they do `import tests` anywhere, they will get the atlassian-python-api's `tests` package.

After I did some digging, I believe the right way to fix it is to undo the respective changes from 8b90689c2bf9a0daf63cb4e8f7c404730707a443 and add `recursive-include tests *` to `MANIFEST.in`, so that the directory (and all its contents) is included in the source tarball, but not installed as a package.

**Comment by gonchik** [comment]
@WOnder93  could you send a PR please?

**Comment by WOnder93** [comment]
Sure, opened #1215
