### ISSUE TITLE
[StatusPage] page_get_templates() wrong url

### ISSUE THREAD

**Issue by rschre** [atlassian-api/atlassian-python-api#1231]
Currently the method page_get_templates of the StatusPage class raises an HTTP-error, no matter what you do.
I figure this is because of the line 1559 in statuspage.py where the url is defined as `url = "v1/pages/{}/templates".format(page_id)`.

I managed to fix this for myself by changing the line to `url = "v1/pages/{}/incident_templates".format(page_id)`.

**Comment by gonchik** [comment]
@rschre you're right. https://developer.statuspage.io/#operation/postPagesPageIdIncidentTemplates
I really appreciate for that feedback,
