### ISSUE TITLE
advanced_mode flag is not passed to underlying `request` method preventing handling of 429 rate limit

### ISSUE THREAD

**Issue by 2ps** [atlassian-api/atlassian-python-api#1241]
several methods of `atlassian.rest_client.AtlassianRestAPI`, like the `post` method, do not propagate the `advanced_mode` flag to the underlying `request` method.  Because that flag is not propagated to the underlying call, rate limit exceptions are thrown and graceful handling of a 429 status code by using the response headers is not possible.  

Proposed fix:  pass the `advanced_mode` flag passed into functions like `post` to the underlying `request` method.

**Comment by gonchik** [comment]
@2ps please share PR

**Comment by Spacetown** [comment]
It will be better to handle the 429 on our own, hiding the logic from the user. The user never wants to abort the script because of rate limits.

We should work on #904.

**Comment by 2ps** [comment]
This can be closed, it is addressed in a merged PR.
