### ISSUE TITLE
unexpected AWS storage upload on pdf export

### ISSUE THREAD

**Issue by cforce** [atlassian-api/atlassian-python-api#1257]
I am bit confused that i get confirmation logs on console for upload to AWS S3 storage when calling the confluence pdf export.
Is Atlassian Cloud using AWS as backend and internal using an AWS S3 bucket to process and convert to pdf?

"
INFO: 25% - IN_PROGRESS
INFO: Check if export task has completed.
INFO: Task completed - UPLOADED_TO_S3
"

Message is produced here https://github.com/atlassian-api/atlassian-python-api/blob/29945d79c5553d8171421a7cc508e25b1e0bf344/atlassian/confluence.py#L2730

"Confluence cloud does not return the PDF document when the PDF
        export is initiated. Instead, it starts a process in the background
        and provides a link to download the PDF once the process completes.
        This functions polls the long-running task page and returns the
        download url of the PDF.
        :param url: URL to initiate PDF export
        :return: Download url for PDF file"

This links seems to be an S3 blob. How long is this blob kept until its wiped? How is this blob storage protected in an multi tenant cloud enviornment?

**Comment by gonchik** [comment]
Hm, that's interesting, I have not checked yet on Confluence Cloud. I usually testing on Confluence DC

**Comment by cforce** [comment]
Atlassian  answer:

"On all export tasks in Confluence, Confluence generates this file first, stores it in our media servers, and then allows downloads.
The generated file will then exist in our media servers for 2 to 7 days (depending on the type of export). If you're interested in knowing the exact amount of days, we can raise a query with engineering to get their input on this.
As for the security side, it is only possible to download files from our media servers through authenticated and authorized requests, so it is not possible for anyone to just download the files as long as they secure a copy of the download URL."
