### ISSUE TITLE
user_get_websudo is throwing throwing 'Expecting value: line 10 column 1 (char 9)'

### ISSUE THREAD

**Issue by amad1101** [atlassian-api/atlassian-python-api#1267]
The user_get_websudo method is throwing an `'Expecting value: line 10 column 1 (char 9)'` exception because of the lack of `not_json_response` parameter not being passed in the user_get_websudo method.

**Comment by amad1101** [comment]
In the jira.py, we need to update the call to `answer = self.get("secure/admin/WebSudoAuthenticate.jspa", self.form_token_headers, not_json_response=True)`

**Comment by amad1101** [comment]
I also had to decode the response as it comes in bytes
`answer = self.get("secure/admin/WebSudoAuthenticate.jspa", self.form_token_headers, not_json_response=True)
        decoded_answer = answer.decode()
        atl_token = None
        if answer:
            atl_token = (
                decoded_answer.split('<meta id="atlassian-token" name="atlassian-token" content="')[1]
                .split("\n")[0]
                .split('"')[0]
            )`

**Comment by gonchik** [comment]
@amad1101  please raise PR.

**Comment by amad1101** [comment]
@gonchik  - Created the following PR https://github.com/atlassian-api/atlassian-python-api/pull/1272
