### ISSUE TITLE
[Jira] issue_createmeta_fieldtypes doesn't support params

### ISSUE THREAD

**Issue by bhanu-atturu** [atlassian-api/atlassian-python-api#1276]
I would like to increase the maxResults param in issue_createmeta_fieldtypes endpoint, but this endpoint doesn't support params.https://github.com/atlassian-api/atlassian-python-api/blob/ddc67d4a899fbf93530f182d6020b03c995bd038/atlassian/jira.py#L1071

**Comment by gonchik** [comment]
@bhanu-atturu  created PR, will merge soon and deploy it. 

Feel free in the future send a PR request for other requests
