### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by badfiles** [atlassian-api/atlassian-python-api#132]
Hi, which error should I catch with except?

**Comment by gonchik** [comment]
Hi! 
It's depends on. 
Could you provide more detail info? 

Cheers,
Gonchik Tsymzhitov

**Comment by gonchik** [comment]
Hello, 
I would like to know your use case 
@badfiles 

Cheers,
Gonchik Tsymzhitov

**Comment by badfiles** [comment]
Hi,
I simply want to know what goes wrong in my code
```
try:
        confluence = Confluence(url=config.con_address,
                                username=config.con_user,
                                password=config.con_password,
                               )
        ....
        status = confluence.update_page(page_id=config.hw_page_id,
                                        parent_id=config.hw_page_parent,
                                        title=config.hw_page_title,
                                        body=body.get_html_string()
                                        )
     except ???:
```

**Comment by gonchik** [comment]
Hi! 

In this situation you can use just except :) 
https://docs.python.org/3/tutorial/errors.html

I will be happy if you provide more improvements for the logging side. :)

Cheers,
Gonchik Tsymzhitov
