### ISSUE TITLE
not working in Pycharm IDE via pip - various  exceptions

### ISSUE THREAD

**Issue by jan-dedalus** [atlassian-api/atlassian-python-api#1329]
clean install of package under python 3.12 is not working. Loading the package via import

from atlassian import Confluence

throws various exceptions 

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2023.3.3\plugins\python\helpers\pydev\pydevd.py", line 1534, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\JetBrains\PyCharm 2023.3.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\dev.user\PycharmProjects\pythonProject\startProject.py", line 7, in <module>
    from atlassian import Confluence
  File "C:\Users\dev.user\PycharmProjects\pythonProject\venv\Lib\site-packages\atlassian\__init__.py", line 2, in <module>
    from .bitbucket import Bitbucket
  File "C:\Users\dev.user\PycharmProjects\pythonProject\venv\Lib\site-packages\atlassian\bitbucket\__init__.py", line 13, in <module>
    class Bitbucket(BitbucketBase):
  File "C:\Users\dev.user\PycharmProjects\pythonProject\venv\Lib\site-packages\atlassian\bitbucket\__init__.py", line 1726, in Bitbucket
    @deprecated(version="1.15.1", reason="Use get_pull_request()")
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dev.user\PycharmProjects\pythonProject\venv\Lib\site-packages\deprecated\classic.py", line 276, in deprecated
    @wrapt.decorator(adapter=adapter)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dev.user\PycharmProjects\pythonProject\venv\Lib\site-packages\wrapt\decorators.py", line 427, in decorator
    return _build(wrapper, _wrapper, adapter=decorator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dev.user\PycharmProjects\pythonProject\venv\Lib\site-packages\wrapt\decorators.py", line 239, in _build
    return AdapterWrapper(wrapped=wrapped, wrapper=wrapper,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "_pydevd_bundle\\pydevd_pep_669_tracing_cython.pyx", line 504, in _pydevd_bundle.pydevd_pep_669_tracing_cython.PyRaiseCallback.__call__
  File "_pydevd_bundle\\pydevd_pep_669_tracing_cython.pyx", line 47, in _pydevd_bundle.pydevd_pep_669_tracing_cython.PEP669CallbackBase.frame
ValueError: wrapper has not been initialized

**Comment by gonchik** [comment]
Python 3.12. I will check. 
as I see mostly the decorator isses

**Comment by gkowalc** [comment]
hmm.. I was just installing the package on latest pycharm on macos and python3.12 interpreter without any issues. 
I have seen  exactly this stack tracer  with pycharm with enabled debugger + breakpoints.
How did you install the package? did you use git clone  + pip install -r requirements.txt?

**Comment by jan-dedalus** [comment]
I am using pycharm on windows and python3.12 interpreter. I downloaded the source and ran the pip command with requirements.txt succesfully. The package is visible under installed packages afterwards.

This is the stacktrace of the successful pip command:

 C:\Users\dev.user\PycharmProjects\pythonProject> pip install ./atlassian-python-api-master/ -r ./atlassian-python-api-master/requirements.txt
Processing c:\users\dev.user\pycharmprojects\pythonproject\atlassian-python-api-master
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting deprecated (from -r ./atlassian-python-api-master/requirements.txt (line 1))
  Downloading Deprecated-1.2.14-py2.py3-none-any.whl.metadata (5.4 kB)
Collecting requests>=2.8.1 (from -r ./atlassian-python-api-master/requirements.txt (line 2))
  Downloading requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting six (from -r ./atlassian-python-api-master/requirements.txt (line 3))
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting oauthlib (from -r ./atlassian-python-api-master/requirements.txt (line 4))
  Downloading oauthlib-3.2.2-py3-none-any.whl (151 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 151.7/151.7 kB 2.3 MB/s eta 0:00:00
Collecting requests_oauthlib (from -r ./atlassian-python-api-master/requirements.txt (line 5))
  Downloading requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Collecting requests-kerberos==0.14.0 (from -r ./atlassian-python-api-master/requirements.txt (line 6))
  Using cached requests_kerberos-0.14.0-py2.py3-none-any.whl (11 kB)
Collecting jmespath (from -r ./atlassian-python-api-master/requirements.txt (line 7))
  Downloading jmespath-1.0.1-py3-none-any.whl (20 kB)
Collecting beautifulsoup4 (from -r ./atlassian-python-api-master/requirements.txt (line 8))
  Downloading beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
Collecting lxml (from -r ./atlassian-python-api-master/requirements.txt (line 9))
  Using cached lxml-5.1.0-cp312-cp312-win_amd64.whl.metadata (3.6 kB)
Collecting cryptography>=1.3 (from requests-kerberos==0.14.0->-r ./atlassian-python-api-master/requirements.txt (line 6))
  Using cached cryptography-42.0.2-cp39-abi3-win_amd64.whl.metadata (5.4 kB)
Collecting pyspnego[kerberos] (from requests-kerberos==0.14.0->-r ./atlassian-python-api-master/requirements.txt (line 6))
  Using cached pyspnego-0.10.2-py3-none-any.whl.metadata (5.4 kB)
Collecting wrapt<2,>=1.10 (from deprecated->-r ./atlassian-python-api-master/requirements.txt (line 1))
  Using cached wrapt-1.16.0-cp312-cp312-win_amd64.whl.metadata (6.8 kB)
Collecting charset-normalizer<4,>=2 (from requests>=2.8.1->-r ./atlassian-python-api-master/requirements.txt (line 2))
  Downloading charset_normalizer-3.3.2-cp312-cp312-win_amd64.whl.metadata (34 kB)
Collecting idna<4,>=2.5 (from requests>=2.8.1->-r ./atlassian-python-api-master/requirements.txt (line 2))
  Downloading idna-3.6-py3-none-any.whl.metadata (9.9 kB)
Collecting urllib3<3,>=1.21.1 (from requests>=2.8.1->-r ./atlassian-python-api-master/requirements.txt (line 2))
  Downloading urllib3-2.2.0-py3-none-any.whl.metadata (6.4 kB)
Collecting certifi>=2017.4.17 (from requests>=2.8.1->-r ./atlassian-python-api-master/requirements.txt (line 2))
  Downloading certifi-2024.2.2-py3-none-any.whl.metadata (2.2 kB)
Collecting soupsieve>1.2 (from beautifulsoup4->-r ./atlassian-python-api-master/requirements.txt (line 8))
  Downloading soupsieve-2.5-py3-none-any.whl.metadata (4.7 kB)
Collecting cffi>=1.12 (from cryptography>=1.3->requests-kerberos==0.14.0->-r ./atlassian-python-api-master/requirements.txt (line 6))
  Using cached cffi-1.16.0-cp312-cp312-win_amd64.whl.metadata (1.5 kB)
Collecting sspilib>=0.1.0 (from pyspnego[kerberos]->requests-kerberos==0.14.0->-r ./atlassian-python-api-master/requirements.txt (line 6))
  Using cached sspilib-0.1.0-cp312-cp312-win_amd64.whl.metadata (7.4 kB)
Collecting pycparser (from cffi>=1.12->cryptography>=1.3->requests-kerberos==0.14.0->-r ./atlassian-python-api-master/requirements.txt (line 6))
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Downloading Deprecated-1.2.14-py2.py3-none-any.whl (9.6 kB)
Downloading requests-2.31.0-py3-none-any.whl (62 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 kB 3.3 MB/s eta 0:00:00
Downloading beautifulsoup4-4.12.3-py3-none-any.whl (147 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.9/147.9 kB 4.3 MB/s eta 0:00:00
Using cached lxml-5.1.0-cp312-cp312-win_amd64.whl (3.9 MB)
Downloading certifi-2024.2.2-py3-none-any.whl (163 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.8/163.8 kB 3.3 MB/s eta 0:00:00
Downloading charset_normalizer-3.3.2-cp312-cp312-win_amd64.whl (100 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.4/100.4 kB 5.6 MB/s eta 0:00:00
Using cached cryptography-42.0.2-cp39-abi3-win_amd64.whl (2.9 MB)
Downloading idna-3.6-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.6/61.6 kB 1.6 MB/s eta 0:00:00
Downloading soupsieve-2.5-py3-none-any.whl (36 kB)
Downloading urllib3-2.2.0-py3-none-any.whl (120 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 120.9/120.9 kB 3.5 MB/s eta 0:00:00
Using cached wrapt-1.16.0-cp312-cp312-win_amd64.whl (37 kB)
Using cached cffi-1.16.0-cp312-cp312-win_amd64.whl (181 kB)
Using cached sspilib-0.1.0-cp312-cp312-win_amd64.whl (567 kB)
Using cached pyspnego-0.10.2-py3-none-any.whl (129 kB)
Building wheels for collected packages: atlassian-python-api
  Building wheel for atlassian-python-api (pyproject.toml) ... done
  Created wheel for atlassian-python-api: filename=atlassian_python_api-3.41.10-py3-none-any.whl size=171278 sha256=852b7f4cb94edc4a927da28908d13a54feaf709013014b23e0b2b0a8f5677409
  Stored in directory: c:\users\dev.user\appdata\local\pip\cache\wheels\22\ea\cc\22f1df75f969e9375d4b55ab3400810ee176a82a3ee2ea818f
Successfully built atlassian-python-api
Installing collected packages: wrapt, urllib3, sspilib, soupsieve, six, pycparser, oauthlib, lxml, jmespath, idna, charset-normalizer, certifi, requests, deprecated, cffi, beautifulsoup4, requests_oauthlib, cryptography, pyspnego, atlassian-python-api, requests-kerberos
Successfully installed atlassian-python-api-3.41.10 beautifulsoup4-4.12.3 certifi-2024.2.2 cffi-1.16.0 charset-normalizer-3.3.2 cryptography-42.0.2 deprecated-1.2.14 idna-3.6 jmespath-1.0.1 lxml-5.1.0 oauthlib-3.2.2 pycparser-2.21 pyspnego-0.10.2 requests-2.31.0 requests-kerberos-0.14.0 requests_oauthlib-1.3.1 six-1.16.0 soupsieve-2.5 sspilib-0.1.0 urllib3-2.2.0 wrapt-1.16.0

Again, when only importing the package without actually using it

from atlassian import Confluence

The error is the same:

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2023.3.3\plugins\python\helpers\pydev\pydevd.py", line 1534, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\JetBrains\PyCharm 2023.3.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\dev.user\PycharmProjects\pythonProject\startProject.py", line 7, in <module>
    from atlassian import Confluence
  File "C:\Users\dev.user\PycharmProjects\pythonProject\venv2\Lib\site-packages\atlassian\__init__.py", line 2, in <module>
    from .bitbucket import Bitbucket
  File "C:\Users\dev.user\PycharmProjects\pythonProject\venv2\Lib\site-packages\atlassian\bitbucket\__init__.py", line 13, in <module>
    class Bitbucket(BitbucketBase):
  File "C:\Users\dev.user\PycharmProjects\pythonProject\venv2\Lib\site-packages\atlassian\bitbucket\__init__.py", line 1726, in Bitbucket
    @deprecated(version="1.15.1", reason="Use get_pull_request()")
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dev.user\PycharmProjects\pythonProject\venv2\Lib\site-packages\deprecated\classic.py", line 276, in deprecated
    @wrapt.decorator(adapter=adapter)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dev.user\PycharmProjects\pythonProject\venv2\Lib\site-packages\wrapt\decorators.py", line 427, in decorator
    return _build(wrapper, _wrapper, adapter=decorator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dev.user\PycharmProjects\pythonProject\venv2\Lib\site-packages\wrapt\decorators.py", line 239, in _build
    return AdapterWrapper(wrapped=wrapped, wrapper=wrapper,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "_pydevd_bundle\\pydevd_pep_669_tracing_cython.pyx", line 504, in _pydevd_bundle.pydevd_pep_669_tracing_cython.PyRaiseCallback.__call__
  File "_pydevd_bundle\\pydevd_pep_669_tracing_cython.pyx", line 47, in _pydevd_bundle.pydevd_pep_669_tracing_cython.PEP669CallbackBase.frame
ValueError: wrapper has not been initialized
python-BaseException

**Comment by jan-dedalus** [comment]
I managed using Conda for virtual environments, and installed the package successfully via

conda install conda-forge::atlassian-python-ap

Thanks for you help anyways, I guess it is a python enviroment setup thing to get it running correctly.

**Comment by gonchik** [comment]
@jan-dedalus  I use pycharm did not reproduce it

**Comment by jan-dedalus** [comment]
@gkowalc seems to be a local python environment setup issue. Thank you anyways
