### ISSUE TITLE
BUG: Documentation https://atlassian-python-api.readthedocs.io

### ISSUE THREAD

**Issue by neomafo88** [atlassian-api/atlassian-python-api#1365]
> To authenticate to the Atlassian Cloud APIs Jira, Confluence, ServiceDesk:
> 
> ```
> # Obtain an API token from: https://id.atlassian.com/manage-profile/security/api-tokens
> # You cannot log-in with your regular password to these services.
> 
> jira = Jira(
>     url='https://your-domain.atlassian.net',
>     username=jira_username,
>     password=jira_api_token,
>     cloud=True)
> 
> confluence = Confluence(
>     url='https://your-domain.atlassian.net',
>     username=jira_username,
>     password=jira_api_token,
>     cloud=True)
> 
> service_desk = ServiceDesk(
>     url='https://your-domain.atlassian.net',
>     username=jira_username,
>     password=jira_api_token,
>     cloud=True)
> ```

`password=jira_api_token,` is copy-pasted across Jira, Confluence and ServiceDesk, without modification

**Comment by gkowalc** [comment]
It is a small thing but I agree  we should use more genering username/password examples in docs so that there is no confusion.  https://github.com/atlassian-api/atlassian-python-api/pull/1370
