### ISSUE TITLE
Comma in expand query param causes issue if URL encoded

### ISSUE THREAD

**Issue by amitjoy** [atlassian-api/atlassian-python-api#1386]
I just found out that if the comma in expand query param is URL encoded, the request returned 404 whereas if the comma is used in the expand param to separate the list, it is accessible

For example:

✅ https://SERVER/rest/api/content?spaceKey=PRS&limit=100&status=current&expand=body.storage,version&type=page
❌ https://SERVER/rest/api/content?spaceKey=PRS&limit=100&status=current&expand=body.storage%2Cversion&type=page

I am not able to retrieve the page content due to this issue at all. Could anyone kindly have a look?

**Comment by gonchik** [comment]
@amitjoy feel free to send PR
