### ISSUE TITLE
unexpected keyword argument 'paging_workaround' 

### ISSUE THREAD

**Issue by AnkeshThakur** [atlassian-api/atlassian-python-api#1397]
I was trying to use this library and while trying to get it work I find that this `paging_workaround` is wrong key here. Is it known issue?

The cause of it wrong param being passed to Jira._get_paged(). 

Stacktrace:

```Traceback (most recent call last):
  File "/workspace/dora/jira_project.py", line 49, in <module>
    p = jp.get_project()
        ^^^^^^^^^^^^^^^^
  File "/workspace/dora/jira_project.py", line 24, in get_project
    projects = self.jira.get_all_projects(included_archived=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/atlassian/jira.py", line 2416, in get_all_projects
    return self.projects(included_archived, expand)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/atlassian/jira.py", line 2434, in projects
    self._get_paged(
TypeError: Jira._get_paged() got an unexpected keyword argument 'paging_workaround' 

```

Fix is very simple - just remove `paging_workaround` in this call

```
self._get_paged(
                     self.resource_url("project/search"),
                     params,
                     paging_workaround=True,
                 )
``` 
Associated PR: https://github.com/atlassian-api/atlassian-python-api/pull/1344/files#diff-160cdaa88ad7a2a6a2d2abd51b32052252fe4ec234c82030006888b10aca1bb0R2367

**Comment by AnkeshThakur** [comment]
Happy to send the PR for the fix if I'm not the only one facing this and community agrees to it.

**Comment by gonchik** [comment]
@AnkeshThakur  feel free to send PR. 
regarding that get_paged, it's mix of cloud and non-cloud method. 
as I see time to wrap up

**Comment by jamesweakley** [comment]
I believe that paging workaround may have been due to https://github.com/atlassian-api/atlassian-python-api/issues/1310

So if you simply remove the parameter, it may go back to getting stuck in a loop for people with over 50 projects.

**Comment by Spacetown** [comment]
But then the parameter need to be handled in the _getPaged function.

**Comment by MarcelWilson** [comment]
#1344 seems to be when the change was made to `Jira._get_paged` but they forgot to add the new paging logic (as @jamesweakley pointed out) found in `BitbucketBase`
