### ISSUE TITLE
HTTP error with incorrect username and password

### ISSUE THREAD

**Issue by foster82** [atlassian-api/atlassian-python-api#140]
Hi , 

I am having problems while doing a confluence search with cql. If the username and password are correct everything is great. However if the username or password are incorrect i get a HTTP error. I want to capture this so it can just display authentication error rather than the full stack out put.

Can you advise where i capture this so that i can handle it as an except. Sorry if this is a little obvious, but i am new to python.

Thanks

Jonathan

**Comment by gonchik** [comment]
Hi! 

Sorry for the delay, from atlassian import Confluence
I am using like this
```
import config
import pprint
import logging

CONFLUENCE_URL = config.CONFLUENCE_URL
CONFLUENCE_LOGIN = config.CONFLUENCE_LOGIN
CONFLUENCE_PASSWORD = config.CONFLUENCE_PASSWORD

logging.basicConfig(level=logging.ERROR)

if __name__ == '__main__':
    confluence = Confluence(
        url=CONFLUENCE_URL,
        username=CONFLUENCE_LOGIN,
        password='blablabla'
    )
    pprint.pprint(confluence.cql('text ~ gonchik'))
```

then output will be like this 
![image](https://user-images.githubusercontent.com/12548235/50765336-a8e4df00-1286-11e9-8935-dc58907e2b50.png)

Otherwise we can implement other exception module.

Cheers,
Gonchik Tsymzhitov

**Comment by foster82** [comment]
great thanks that has helped to a degree , what i am looking do do though is hide this out put. Is that possible? Just need to show an authentication error.

**Comment by Woklex** [comment]
You can just throw a request and check that we are fine.
```
    confluence = Confluence(
        url=CONFLUENCE_URL,
        username=CONFLUENCE_LOGIN,
        password='blablabla'
    )
    out = confluence.request()
    if out.status_code == 200:
        confluence.cql('text ~ Wubba lubba dub dub!'))
    elif out.status_code == 401:
        print("AUTHENTICATED_FAILED")
    else:
        print("Another error. Do something.")
```

**Comment by gonchik** [comment]
@Woklex  Thanks for that. 
| have implemented here as well 
https://github.com/atlassian-api/atlassian-python-api/commit/dfd882bf348cd14e391bd644902a9726a3ef4434
