### ISSUE TITLE
bitbucket.project_list() only returns generators

### ISSUE THREAD

**Issue by pascalrobert** [atlassian-api/atlassian-python-api#1408]
Using Bitbucket 8.19 and Python 3.12. When I call bitbucket.project_list(), it returns a list of the correct length. But if I print it, it only show 'generator object'. If I iterate over the list with:

project_list = bitbucket.project_list()
for project in project_list:
  print(project)

I see the details, but it's a infinite loop, it's just iterate over and over again on the list of projects (1398 x X loops).

**Comment by pascalrobert** [comment]
I'm just plain stupid. My function was called in a loop, so it was really iterating many times because bitbucket.project_list() was called many times... Working fine now.

**Comment by Spacetown** [comment]
???
