### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Neil-Welsh** [atlassian-api/atlassian-python-api#1421]
an issue was fixed a few days ago which would is blocking some of our development can you please do a release with the latest code base in?
https://github.com/atlassian-api/atlassian-python-api/pull/1413

**Comment by djgoku** [comment]
Another option is installing the specific commit/branch.

```

python -m pip install -e 'git+https://git.repo/some_pkg.git#egg=SomePackage'          # from git
python -m pip install -e 'hg+https://hg.repo/some_pkg.git#egg=SomePackage'            # from mercurial
python -m pip install -e 'svn+svn://svn.repo/some_pkg/trunk/#egg=SomePackage'         # from svn
python -m pip install -e 'git+https://git.repo/some_pkg.git@feature#egg=SomePackage'  # from 'feature' branch
python -m pip install -e 'git+https://git.repo/some_repo.git#egg=subdir&subdirectory=subdir_path' # install a python package from a repo subdirectory
```

Taken from https://pip.pypa.io/en/stable/cli/pip_install/

**Comment by gonchik** [comment]
@djgoku  @Neil-Welsh  
deployed a new release. also, that info will be added into docs. 
Thanks for your helps and informings.
