### ISSUE TITLE
OAuth2 instead of BasicAuth?

### ISSUE THREAD

**Issue by niklasbeinghaus** [atlassian-api/atlassian-python-api#144]
While I understand that Basic Auth is quite simple to use at first hand, I think it would be nice (and much more secure) to have the opportunity to use other Authentification Methods offered by the Atlassian APIs, such as OAuth2.

Did you try implementing OAuth2 yet?

**Comment by gonchik** [comment]
Hi! 

I have not tried to implement yet OAuth support. 
Because mostly on premises product use the basic auth. BTW, I absolutely agree with for supporting the OAuth as additional possibility :) 👍 

Thanks for your request.


Cheers,
Gonchik Tsymzhitov

**Comment by wesinator** [comment]
this means the Bitbucket interface is not usable for cloud users that have 2FA enabled on their account. 

also, I'm not sure what the API endpoint URL for cloud would be , `'https://api.bitbucket.org/2.0/'` ? 
It would be good if there were examples for the cloud APIs.

p.s. is this an official Atlassian library ?
