### ISSUE TITLE
[Confluence] Fix docstring for two methods

### ISSUE THREAD

**Issue by Hummus-Ful** [atlassian-api/atlassian-python-api#1440]
Hi, 

I've noticed the same incomplete sentence in two docstrings under `Confluence.attach_file()` and `Confluence.attach_content()`.

The current sentences are: 
> :param content_type: Specify the HTTP content type. The default is

Based on the methods, the sentences should be; 
> :param content_type: Specify the HTTP content type. The default is "application/binary"

**Comment by gonchik** [comment]
@Hummus-Ful 
added there
f9d7faa77c4a5a19b4b0e889701af5b847689af6

I will be happy if you send next time a PR.
