### ISSUE TITLE
Add issue remote link

### ISSUE THREAD

**Issue by IncandescentChrysalis** [atlassian-api/atlassian-python-api#1448]
Adding a link to an application connected with a Jira instance through the `/rest/api/2/issue/{issueIdOrKey}/remotelink` Jira API route, an `application` section might be provided.
This might for instance be used to add Confluence links to a connected Confluence instance.
Cf. [Atlassian knowledge base about the different kind of links](https://confluence.atlassian.com/jirakb/how-to-use-rest-api-to-add-remote-links-in-jira-issues-1206556936.html).

**Comment by gonchik** [comment]
@IncandescentChrysalis  do you have a plan to continue ? :)
