### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by VadimRight** [atlassian-api/atlassian-python-api#1472]
I try to get info from Confluence version 7.4.11 using last version of this library and get error

```
  File "/home/user/PythonProjects/telegram_bot/venv/lib/python3.12/site-packages/atlassian/confluence.py", line 639, in get_all_pages_from_space
    ).get("results")
      ^^^
AttributeError: 'str' object has no attribute 'get'
```
I am trying confluence get_all_pages_from_space.

I think it is because no json response is accepted.

Is there any ccompatibility table for this library. Maybe last version of framework doesn't fit my Confluence version or something?

**Comment by gkowalc** [comment]
7.4.11 is very old version, not supported by Atlassian anymore. Are you able to replicate this problem on one of the most recent LTS version (for example 8.5)?

**Comment by VadimRight** [comment]
No I can't do it.
But I think problem is solved.
I just changed URL of Confluence in initiation of Confluence object.

My url was
`confluence = Confluence("url.com/#get_all_updates", username, password)`

And I it changed to
`confluence = Confluence("url.com", username, password)`
