### ISSUE TITLE
searching a project for issues in jira

### ISSUE THREAD

**Issue by foster82** [atlassian-api/atlassian-python-api#152]
Hi guys, i have been looking over the documentation and can cant quite work out how to search a project in jira for a project.

Any direct you could give would be great.

**Comment by gonchik** [comment]
Hi! 
Do you mean abou that ? 
https://docs.atlassian.com/software/jira/docs/api/REST/7.13.1/#api/2/project-getProject
or that with additional filter
https://docs.atlassian.com/software/jira/docs/api/REST/7.13.1/#api/2/project-getAllProjects

Cheers,
Gonchik Tsymzhitov

**Comment by foster82** [comment]
I am trying to search a project and then a type within that project. However i am struggling to get a response with the wrapper.

**Comment by gonchik** [comment]
Like this https://github.com/atlassian-api/atlassian-python-api/blob/master/atlassian/jira.py#L159 ?

**Comment by gonchik** [comment]
@foster82  Could you clarify, please ?

**Comment by SLRover** [comment]
@foster82 Tell me, please what do you need? Do you trying to get a list of projects? Or to get the Project ID from particular issue? Or may be are you trying to get a list of issue types?

**Comment by gonchik** [comment]
During inactivity that issue is closed
