### ISSUE TITLE
Authenticating with App Password on public bitbucket.

### ISSUE THREAD

**Issue by Skarlso** [atlassian-api/atlassian-python-api#153]
Hi. 

I'm trying to authenticate like this on the public bitbucket site:

```python
        username = os.environ['CRONOHUB_BITBUCKET_USERNAME']
        password = os.environ['CRONOHUB_BITBUCKET_PASSWORD']
        url = os.environ['CRONOHUB_BITBUCKET_URL']
        bitbucket = Bitbucket(
                url=url,
                username=username,
                password=password)
        data = bitbucket.project_list()
```

where username is my username, the password is an App password that I generated ( I don't have a password since I created my account via Google Oauth ) and url is `https://bitbucket.org`.

All I get back is this:

```
b''
HTTP Error occurred
Response is: b''
Expecting value: line 1 column 1 (char 0)
```

Which tells me nothing.

**Comment by JosephCastro** [comment]
Same issue here.
I think we need to connect using Oauth (I have 2FA)

**Comment by Skarlso** [comment]
@JosephCastro I abandoned trying to use this package. :/

**Comment by gonchik** [comment]
@Skarlso @JosephCastro 
I hope that PR will help you #202

**Comment by wesinator** [comment]
Using app password to access 2FA cloud account works from the official client https://pypi.org/project/pybitbucket/ 

But it also isn't documented, so good luck figure out how to use that ☝️ (which I'm in the process of having to do unfortunately). 

Atlassian (a company that makes software supporting devs and PM) can't bother to document their own 💩 , apparently
