### ISSUE TITLE
Confluence - Get Child Pages 

### ISSUE THREAD

**Issue by mattwakeman** [atlassian-api/atlassian-python-api#154]
Please add support for getting child pages of a given page by its ID or Title. 

My use case is that I want to create a load of pages based upon a confluence pages from Jira JQL (one page per Epic), then label each one so I can easily create a Page Properties table.

**Comment by gonchik** [comment]
Hi! 
Do you want cover all tree or only one level? 
If only one level you can use exist method, and I added a small override method #165 

Cheers,
Gonchik

**Comment by gonchik** [comment]
This one is covered
https://github.com/atlassian-api/atlassian-python-api/blob/master/atlassian/confluence.py#L70
