### ISSUE TITLE
get_project_issues_count should escape project name

### ISSUE THREAD

**Issue by springfan** [atlassian-api/atlassian-python-api#155]
[jira.py](https://github.com/atlassian-api/atlassian-python-api/blob/master/atlassian/jira.py)'s  `get_project_issues_count` def should escape project name. Otherwise one may face issues like this if project key contains reserved JQL words:

```
ERROR:atlassian:{'errors': {}, 'errorMessages': ["Error in the JQL Query: 'INPUT' is a reserved JQL word. You must surround it in quotation marks to use it in a query. (line 1, character 11)"]}
```

**Comment by gonchik** [comment]
Let's reuse that commit. 
#165 

I am going to upload a new release

Cheers,
Gonchik Tsymzhitov
