### ISSUE TITLE
Searching for strings containing special characters

### ISSUE THREAD

**Issue by securityaspirations** [atlassian-api/atlassian-python-api#156]
Hi,

If I use the CQL search to look for a string containing a special character then I get a status code 400. 
For example searching for the word 'C#ess' fails with status code 400 and:
`'message': 'Could not parse cql'`

Searching for the same string via the Confluence UI seems to parse the special character by replacing with %23. For example:
`cql=siteSearch+~+"C%23ess"`

I've tried escaping the special characters to no avail and also used CQL to search directly for  C%23ess - but then I run into the problem of using another special character so it still won't work.

Am I missing something here or is this a bug?

Thanks very much

**Comment by SLRover** [comment]
Hi!
You can not use special characters in CQL, because Rest API don't support them.
You can see request [here](https://jira.atlassian.com/browse/CONFSERVER-55559).

**Comment by securityaspirations** [comment]
Ah that's a shame -  I hadn't realised that. 
Thanks for the info though.
