### ISSUE TITLE
Compatible with Atlassian cloud?

### ISSUE THREAD

**Issue by gabrielke** [atlassian-api/atlassian-python-api#173]
Hi,

Is this library compatible with the Atlassian Cloud? 
Please include this info into the documentation too, thanks!

Regards,
Akos

**Comment by gonchik** [comment]
Hi, 

Good question. I have played with Cloud last year. 
Now as I see, a lot of things was changed. 

Thanks 
I will play around that in nearest project with Cloud.

Cheers,
Gonchik Tsymzhitov

**Comment by gonchik** [comment]
@gabrielke  Let's evaluate on that way
#428

**Comment by dom-insytesys** [comment]
Any update on this?   I'm trying to figure out how to authenticate for Confluence Cloud.  I'm not sure what the differences are compared to vanilla Confluence, but I have discovered that "basic" username/password authentication is disabled for REST API.   Atlassian want you to use "API tokens" ([link](https://developer.atlassian.com/cloud/confluence/oauth-2-authorization-code-grants-3lo-for-apps/)).  This looks similar to oauth, but I cannot figure out how ouath fields would map to username/token pair.

**Comment by jkodroff** [comment]
@dom-insytesys Oh good lord did it ever help someone (me).  Thank you so much - you've saved me hours of frustration!

**Comment by jkodroff** [comment]
Did my best to pay it forward: https://github.com/atlassian-api/atlassian-python-api/pull/509

**Comment by gabrielke** [comment]
Ah, this is a pretty old issue. 
Thanks for the contribution, I guess I will close this, it is at most a duplicate anyway.
