### ISSUE TITLE
[Confluence]: Method to obtain page content

### ISSUE THREAD

**Issue by argysamo** [atlassian-api/atlassian-python-api#180]
It would be nice to have a method to obtain the body of a given page. 
You could then update a page, making modifications to its body. 
This method will have as an input the page_id and return the page body content formatted as html. 
I will soon submit a PR to fix this issue. 

(If I am not mistaken, the current `update_or_create()` method replaces the content of the page.)

Kind regards,
Argyris

**Comment by gonchik** [comment]
Hi! 
I hope that commit will cover your request 
https://github.com/atlassian-api/atlassian-python-api/commit/1b875e87d8d2d51b5e69404652f5c52d9f4e7f95

Cheers,
Gonchik Tsymzhitov

**Comment by kierun** [comment]
1b875e8 seems to be about _appending_ to a page. As far as I understand @argysamo request, this is about getting the whole content of a page. 

As simple use case would be:
- Get the page's data.
- Find some field within said data -- for example a page property.
- Update said field to a new value.
- Upload the new page content.

Or is that already possible and I somehow missed it?

**Comment by gonchik** [comment]
@kierun  Well, you can do in different ways i.e.
`old_content = confluence.get_page_by_id(123).expand='storage.view'
body = (((result.get('body') or {}).get('view') or {}).get('value') or {})
body.replace("oldvalue", "new_value")
confluence.updade_page(old_content.get('id'), body=body)
`

https://github.com/atlassian-api/atlassian-python-api/blob/master/atlassian/confluence.py#L505
https://github.com/atlassian-api/atlassian-python-api/blob/master/atlassian/confluence.py#L541

**Comment by freeyland** [comment]
@gonchik When trying previous i am getting:
AttributeError: 'dict' object has no attribute 'expand'

**Comment by freeyland** [comment]
Found it :)
confluence.get_page_by_id(page_id, expand='storage.view')

**Comment by gonchik** [comment]
@freeyland  on which did you try it?

**Comment by freeyland** [comment]
It is working, made a mistake in my code. Thnx for quick reply

**Comment by freeyland** [comment]
When Updating Im getting:
 {'statusCode': 400, 'message': 'org.codehaus.jackson.map.JsonMappingException: Instantiation of [simple type, class com.atlassian.confluence.api.model.content.id.ContentId] value failed: Can\'t parse as a ContentId: <p>Hallo</p> (through reference chain: com.atlassian.confluence.api.model.content.Content["ancestors"]->com.atlassian.confluence.api.model.content.Content["id"])'}
`
body.replace("Hallo", "Hallo2")
result = confluence.update_page(
            parentID, pageID, 'Versions & Changelogs', body, 'page', 'wiki')
`

**Comment by gonchik** [comment]
Please, check the order of variables
https://github.com/atlassian-api/atlassian-python-api/blob/master/atlassian/confluence.py#L687
