### ISSUE TITLE
Atlassian API GDPR Changes

### ISSUE THREAD

**Issue by CSimpiFoN** [atlassian-api/atlassian-python-api#181]
Hello Guys,

Is this module prepared for the Atlassian's GDPR API changes?
https://blog.developer.atlassian.com/app-opt-in-api-migration/

**Comment by gonchik** [comment]
Hi @CSimpiFoN , 

In this weekend I will set extended header to be complient with GDPR changes.
Or I will be happy, if you provide me a PR :)

Cheers,
Gonchik Tsymzhitov

**Comment by gonchik** [comment]
Hi @CSimpiFoN , 
as I see that lib works without that headers well, 
or I can't reproduce it. 
Could you help me, please? 

Cheers,
Gonchik
