### ISSUE TITLE
Page update without overwrite

### ISSUE THREAD

**Issue by TamilarasanR** [atlassian-api/atlassian-python-api#182]
Hi,
function "confluence.update_page" and "confluence.update_or_create" is overwriting the content. 
Is there any way where we append the new content with the existing content in the page?

**Comment by argysamo** [comment]
Hey, I started working on that for issue #180 
I'll come back with a PR, soon.

Argyris

**Comment by gonchik** [comment]
Hi Argyris, 
Thanks.

**Comment by TamilarasanR** [comment]
Thank you Argyrios.

**Comment by gonchik** [comment]
I hope the #218 will cover it
