### ISSUE TITLE
Upload Plugin For Jira Not Working

### ISSUE THREAD

**Issue by machinecode** [atlassian-api/atlassian-python-api#185]
Hi,

Upload plugin for Jira is not working since creating url function removes trailing spaces but Atlassian's API not responding without trailing space. 🤦‍♂️

**Comment by gonchik** [comment]
Hi @machinecode , 

you are right :) 
Sorry for that, hence I have added trailing mode. 
https://ecosystem.atlassian.net/wiki/spaces/UPM/pages/6094960/UPM+REST+API
In next release, it will be fixed

Cheers,
Gonchik Tsymzhitov

**Comment by gonchik** [comment]
Could you update the library, please? 
@machinecode
