### ISSUE TITLE
PDF export does not return a pdf file

### ISSUE THREAD

**Issue by andreacapriplexure** [atlassian-api/atlassian-python-api#199]
When running conflunce.export_page(page['id']) we get back the download page

**Comment by ysfiqbl** [comment]
Hi @andreacapriplexure ,

Could you please let me know which version of Confluence you are testing against?
I just tested it on Confluence 6.0.3 and the `export_page(page_id)` function returns `bytes`.

Here's the code I used.

```
if __name__ == '__main__':
    space = 'SPACE_KEY'
    page_title = 'PAGE TITLE'
    page_id = confluence.get_page_id(space, page_title)
    content = confluence.export_page(page_id)
    print(type(content))
    with open(page_title + ".pdf", 'wb') as pdf_file:
        pdf_file.write(content)
        pdf_file.close()
        print("Completed")
```

**Comment by andreacapriplexure** [comment]
Hi @ysfiqbl I used the near exact code to call this, the issue is that the bytes returned are of the page where the filestore link is displayed. i.e. it returns an html page. 
This is my about confluence:
![image](https://user-images.githubusercontent.com/50006394/57109319-3e9e0000-6d89-11e9-874f-746a1d5cfff7.png)
Now I could try and find the link to the file but unfortunately the html is a mixture of scripts which, after the file is ready, display the link to the page.

**Comment by ysfiqbl** [comment]
Hi @andreacapriplexure 

It looks like the Confleunce cloud version does not return the PDF document, instead it starts a process in the background and provides a link to download the PDF once completed.
![image](https://user-images.githubusercontent.com/676653/57189905-b9a21a80-6f31-11e9-826e-33b2cb58b534.png)

![image](https://user-images.githubusercontent.com/676653/57189910-c0c92880-6f31-11e9-8638-2cd2883f01d1.png)

So you need to poll the page and download the PDF after this process has finished. 

I created a quick and dirty fix for this. You can find at the link below. 
https://github.com/ysfiqbl/atlassian-python-api/tree/issue/199

Will be submitting a PR for it after I do a bit of clean up.

**Comment by andreacapriplexure** [comment]
That sounds fantastic, thank you for coming up with a fix! I suppose it makes sense that the cloud version creates jobs for long running tasks like this.

**Comment by andreacapriplexure** [comment]
I verified that your branch works :)

**Comment by ysfiqbl** [comment]
@andreacapriplexure you are welcome and thank you for validating it. 
Submitted [PR](https://github.com/atlassian-api/atlassian-python-api/pull/201)

**Comment by gonchik** [comment]
@ysfiqbl  @andreacapriplexure  Thanks for collaboration. 
I have upload into latest version of module. 
Feel free to update it
