### ISSUE TITLE
There was a problem confirming the ssl certificate

### ISSUE THREAD

**Issue by StanislavTomilov** [atlassian-api/atlassian-python-api#216]
Hello, I'm trying to install atlassian-python-api. Used this command 
`pip3 install atlassian-python-api`
but got an error

 ERROR: Could not find a version that satisfies the requirement atlassian-python-api (from versions: none)
ERROR: No matching distribution found for atlassian-python-api
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443)

Am I understand right, that I'm had to download the certificate from pypi.org and put it somewhere? And where I should put it?

**Comment by gonchik** [comment]
Hi! 
I have double check from different OS (Oracle Linux, Windows 10, MacOS) that operation. 
Unfortunately, I can't reproduce it. 
Cheers,
Gonchik Tsymzhitov

**Comment by gonchik** [comment]
I have checked from different places, unfortunately, I can't reproduce it :(
