### ISSUE TITLE
Create pull request

### ISSUE THREAD

**Issue by echoe** [atlassian-api/atlassian-python-api#222]
Hi,

Is there any reason that there's no way to create a pull request within this API? This would be a greatly appreciated feature. (This is obviously a feature request ... I'm working on providing this myself though, YMMV.)

**Comment by gonchik** [comment]
Hi, 

@echoe  Thanks for your initiative

**Comment by echoe** [comment]
@gonchik In testing I've been having issues using anything that's in the bitbucket part of this plugin with my internal repo, it appears like they're being passed as GETs. I wrote a script outside of this plugin that works without issue, calling the same API URLs that I've been testing with this here. My script to test the plugin is basically:

from atlassian import Bitbucket
  
bitbucket = Bitbucket(url,user,pass)
data = bitbucket.project_list()
print(data)
test=bitbucket.add_pull_request_comment('project', 'repo', 'pull request number', 'text')
print(test)

The get request and doing a project list works fine, but for the post test - adding the PR comment - I get:

ERROR:atlassian.rest_client:Received: 400
 Bad request 

{u'errors': [{u'message': u'The path query parameter is required when retrieving comments.', u'exceptionName': None, u'context': None}]}

This seems like something that would only be required with a get. Testing my own branch, I get the output of hitting the same part of the API with a GET request, as well, as listed here:

https://docs.atlassian.com/bitbucket-server/rest/4.9.1/bitbucket-rest.html#idp2046528



Do you know if there's an issue with the plugin's POSTs, specifically in the bitbucket part of it? My usecase is resolved with the secondary script I wrote (we actually can't use user/pass authentication either ...) but I'd like to also add the functionality to this if possible.

**Comment by gonchik** [comment]
Hi @echoe !
Could you check, please,  using that app 
https://marketplace.atlassian.com/apps/1211542/atlassian-rest-api-browser?hosting=server&tab=overview

Looks like it is related to the REST API break

**Comment by echoe** [comment]
@gonchik I'm sadly not the administrator for my work's instance but I could likely get them to install this plugin. However, I'm able to POST to this exact function via script outside of this plugin, using multiple forms of authentication, so it can't be due to issues with the API endpoints not being able to accept this query.

**Comment by gonchik** [comment]
@echoe I have updated the contributing page.
https://github.com/atlassian-api/atlassian-python-api/blob/master/CONTRIBUTING.rst

I hope it will help in the future provide more interesting features here

**Comment by wesinator** [comment]
It would be good if this was documented with an example. 
https://github.com/atlassian-api/atlassian-python-api/blob/0142cdf24fffcbe9a0bb6c1a34ecf6966a4802c9/atlassian/bitbucket.py#L735

Thanks !

**Comment by gonchik** [comment]
https://github.com/atlassian-api/atlassian-python-api/commit/3e7a2e66798630a1f38854716effbd1aef96f282

**Comment by echoe** [comment]
Nice, thank you!
I'm sorry I didn't actually push my changes, I ended up implementing it in another way in-office and didn't have coding energy outside of work to get this properly into the codebase here.

**Comment by wesinator** [comment]
> Nice, thank you!
> I'm sorry I didn't actually push my changes, I ended up implementing it in another way in-office and didn't have coding energy outside of work to get this properly into the codebase here.

For what it's worth, I implemented creating pull requests in Bitbucket cloud using the official pybitbucket client - https://github.com/wesinator/Bitbucket-PyRs 

Uses app password for auth with 2FA.

**Comment by gonchik** [comment]
@wesinator Thanks for that mention. 
I see that's good idea this lib based on schema
https://github.com/wbrefvem/python-bitbucket/blob/b5002a97f0dd9d02dfc60f81b3a13d966abad9aa/pybitbucket/pullrequest.py#L29

Do you use only bitbucket for automation ? If so, could you provide a PR for the improvements, please ? 
Because the main idea that lib was support server releases info and do a requests.
Also, I just somewhere provide an internal API requests, because which is not documented, but I need to use during the migration, integration of Atlassian suite and somethings
