### ISSUE TITLE
Bitbucket API v2

### ISSUE THREAD

**Issue by oscarverona** [atlassian-api/atlassian-python-api#232]
Hello,

It seems that Bitbucket removed the version 1 of their API on May 29. I cannot make it work. ¿Is it planned to update the api client to version 2?

Thanks

**Comment by gonchik** [comment]
Hi! 

Sure!

**Comment by SilverJan** [comment]
Hi, by when can we expect the update?

**Comment by tuxmaster5000** [comment]
It looks like to get complicated, because V2 are only supported on the cloud version of it.
The self hosted one use V1. Like it is called here:
https://community.atlassian.com/t5/Bitbucket-questions/Does-the-rest-api-2-0-exist-for-server/qaq-p/881631
Or have someone other information's?

**Comment by gonchik** [comment]
@tuxmaster5000  Thanks ! 
@SilverJan  @oscarverona I hope you will raise a PR for the improvements :)
