### ISSUE TITLE
Confluence cloud docs are thin and wrong URI gives internal error

### ISSUE THREAD

**Issue by ajs** [atlassian-api/atlassian-python-api#252]
When starting out I tried accessing the URL `https://<org>.atlassian.net/` (first parameter to the `Confluence` class initialization), but because the docs are thin regarding cloud access, it wasn't clear exactly what I was supposed to be doing. Worse, I got this exception:

```
self = <atlassian.confluence.Confluence object at 0x7fb157559fd0>, space = 'SOMESPACE', title = 'SOMETITLE', start = None, limit = None

    def get_page_by_title(self, space, title, start=None, limit=None):
        """
            Returns the list of labels on a piece of Content.
            :param space: Space key
            :param title: Title of the page
            :param start: OPTIONAL: The start point of the collection to return. Default: None (0).
            :param limit: OPTIONAL: The limit of the number of labels to return, this may be restricted by
                                fixed system limits. Default: 200.
            :return: The JSON data returned from searched results the content endpoint, or the results of the
                     callback. Will raise requests.HTTPError on bad input, potentially.
                     If it has IndexError then return the None.
            """
        url = 'rest/api/content'
        params = {}
        if start is not None:
            params['start'] = int(start)
        if limit is not None:
            params['limit'] = int(limit)
        if space is not None:
            params['spaceKey'] = str(space)
        if space is not None:
            params['title'] = str(title)
        try:
>           return (self.get(url, params=params) or {}).get('results')[0]
E           TypeError: 'NoneType' object is not subscriptable

...lib/python3.5/site-packages/atlassian/confluence.py:118: TypeError
```

It turns out, I just needed to append `/wiki` to my URL, but there was little in the way of information that would tell me this.

**Comment by gonchik** [comment]
Hi! 
Thanks for that. 
Looks like it's the same issue with #189

**Comment by ajs** [comment]
Note that this report is in two parts. One is the error. The other is the fact that the docs aren't clear about the correct URL format for the three Confluence URL types:

* Local install
* Generic cloud service
* Private domain cloud service

Each of these are slightly different for each of the three products and the docs should be made clearer with examples for the complete matrix of the above offerings and specific sub-product.

**Comment by gonchik** [comment]
@ajs  You are right, as I see need to redesign exist rest_client
I have added that small hacky fix
https://github.com/atlassian-api/atlassian-python-api/pull/268/commits/f16c1dd8398984119921cc674c0cf104b6ae9706
