### ISSUE TITLE
v1.13.16 is broken

### ISSUE THREAD

**Issue by CpHarding** [atlassian-api/atlassian-python-api#253]
In conflueunce.py ~ line 550 - the argument representation='storage', has been removed, but is still used in the function

**Comment by gonchik** [comment]
Could you provide a please, a log ?

**Comment by osolopsamsung** [comment]
Hey, in `update_page(self, page_id, title, body, parent_id=None, type='page', minor_edit=False)` function there is no `representation` value, but you still use it in the data->body `'body': self._create_body(body, representation)`. Can you fix it?

**Comment by osolop** [comment]
Hey, in update_page(self, page_id, title, body, parent_id=None, type='page', minor_edit=False) function there is no representation value, but you still use it in the data->body 'body': self._create_body(body, representation). Can you fix it?
Here is log:
File "/home/o.solop/.pyenv/versions/3.6.5/lib/python3.6/site-packages/atlassian/confluence.py", line 613, in update_page 'body': self._create_body(body, representation), NameError: name 'representation' is not defined

**Comment by gonchik** [comment]
@osolop  @CpHarding  Ooops, sorry

**Comment by gonchik** [comment]
Could you update to latest version, please?

**Comment by osolop** [comment]
It works, thanks!
