### ISSUE TITLE
Construct the authorization header

### ISSUE THREAD

**Issue by arodzik** [atlassian-api/atlassian-python-api#256]
Hello, 
Is there an option to construct the authorization header and supply it using this api instead of oauth and username/pass? As it is explained here https://developer.atlassian.com/server/jira/platform/basic-authentication/ (Base64 encoding)

**Comment by gonchik** [comment]
Hi @arodzik , 
Hm, username/pass generate the authorization header through requests module.
Could you, please, describe your use case? 

Cheers,
Gonchik Tsymzhitov

**Comment by arodzik** [comment]
Hello,
 Thanks for response. What i want to achieve is to connect to JIRA using enocded username:pass (Base64) as it is described in JIRA Rest API doc. 

```If you need, you can construct and send the basic authorization header yourself as follows:
Build a string of the form username:password.
Encode the string to Base64.
Supply an authorization header with format Authorization: Basic {encoded-string}. Make sure to replace {encoded-string} with your encoded string from Step 2.
For example, if your username and password are both fred then the string "fred:fred" encodes to ZnJlZDpmcmVk in Base64. 
```
OAuth in my particular problem do not work and i don't want to pass credentials directly in the script code.
Is there a possibility to pass encoded string as credentials, if so how to do this? In documentation i found only info how to log using user/pass or OAuth.

Thanks,
Adrian

**Comment by mintmi01** [comment]
I'm also attempting to accomplish the same. Is there any solution to this request?
- Thanks

**Comment by gonchik** [comment]
@mintmi01 @arodzik  I can provide base64encode and decode function, which will works for exist methods as login and password? but for you it's extra method with base64

**Comment by arodzik** [comment]
@mintmi01 I have already worked it around in simple way witch was fine in my case. 
1. I've provided base64 encoded string (username:password)
2. With `base64` library ive decoded provided credentials and saved them to dict: 
`my_dict = str(base64.b64decode(my_str)).lstrip("b'").rstrip("'").split(':')`
3. Decoded credentials saved in dict are easly accesible to rest of the script but not straight visible in code.

@gonchik I think it would be nice to have such authorization method in API. It could be considered as additional feature in future ;)

**Comment by gonchik** [comment]
Hi @arodzik , 
Could you provide PR, please ? 
I would say if it really needed let's implement it :)
Cheers,
Gonchik Tsymzhitov

**Comment by arodzik** [comment]
In my particular case the API is used to perform CI. We have an separate account in Active Directory to perform CI operations. We do not want to spread the credentials to this account and anchor it straight in the code in repository, because if too much people know and use this account there is always problem that account is being locked (probably to much invalid password attempts). This completely ruins automatic environment  as the account is usually locked for 3 days. It's not perfect solution for this issue but somehow working :)

**Comment by gonchik** [comment]
@arodzik  It sounds you need to use OAuth :) which will cover your requests:)

**Comment by arodzik** [comment]
@gonchik Yes, it would be perfect, but we also use internal tools which do not support tokens and in my case this was impossible. In general this will be the best way :)

**Comment by gonchik** [comment]
@arodzik  Also, you can use a cookie file as auth method:)

**Comment by sunilm-css** [comment]
>>> import base64
>>> data="<email>:<password>"
>>> encoded=base64.b64encode(data.encode("utf-8"))
>>> encodedBytes=base64.b64encode(data.encode("utf-8"))
>>> encodedStr = str(encodedBytes, "utf-8")
>>> print(encodedStr)
c3V........dWRmYWJyaXguY29........hOA==

curl -H "Authorization: Basic c3V........dWRmYWJyaXguY29........hOA==" -X GET -H "Content-Type: application/json" https://api.bitbucket.org/2.0/user
