### ISSUE TITLE
Blog posts in Confluence trash is not deleted

### ISSUE THREAD

**Issue by Christian-Schou** [atlassian-api/atlassian-python-api#259]
Hi guys!

This is an amazing tool. I just tested this function:

`confluence.remove_page_from_trash(page_id)`

It removes the pages as the name says, but the problem is that Confluence got different content types, meaning that deleted blog posts in trash is not deleted only the deleted pages. Is it possible to develop functionality for deleting the posts too?

It would be amazing if that was possible. Then i will go ahead and configure our server with an automatic scheduler for running this job every week, cleaning up the Confluence instance for trashed items. :)

Thanks in advance!

**Comment by gonchik** [comment]
Hi! 

I have tested it works well for blog posts as well. 
because delete operations only related to the id of content
https://docs.atlassian.com/ConfluenceServer/rest/6.15.6/#api/content-delete

Therefore could you please, double check remove remove_page_from_trash() method, I can evaluate extra overwrap for clear naming. like remove_content_from_trash

Cheers,
Gonchik Tsymzhitov

**Comment by Christian-Schou** [comment]
Hi Gonchik,

When i run this script: [https://github.com/atlassian-api/atlassian-python-api/blob/master/examples/confluence-trash-cleaner.py](https://github.com/atlassian-api/atlassian-python-api/blob/master/examples/confluence-trash-cleaner.py)

It doesn't show me the blog posts or deletes them from trash. Do you have an idea of what i might change for it to work with the blog posts?

I just tested again this morning and the pages are trashed but not posts.

Cheers! :)

**Comment by gonchik** [comment]
Let me reproduce it, please

**Comment by gonchik** [comment]
You were right :) 
and I have fixed, feel free to check exmaple

**Comment by Christian-Schou** [comment]
Amazing! I will fetch the latest version at run the script.

Thank you! :)
