### ISSUE TITLE
Key error on file upload

### ISSUE THREAD

**Issue by pojotmc** [atlassian-api/atlassian-python-api#260]
When attempting to upload a file to a page, i'm getting the following error:

 File "/usr/local/lib/python3.7/site-packages/atlassian/confluence.py", line 389, in attach_file
    if attachments['size']:
KeyError: 'size'

just using the line:
confluence.attach_file("new_logo.jpg", page_id="169476394", title="TEST", space="TEST", comment="Testing Attachments")

**Comment by pojotmc** [comment]
ah, ok it was a space issue that was surfacing in errors weirdly.

so for confluence it doesn't appear to automatically apply /wiki to the begining of the path. to be able to interact with it i need to set the base url to .atlassian.net/wiki' rather than just the domain.

**Comment by gonchik** [comment]
I have added that small hacky fix
https://github.com/atlassian-api/atlassian-python-api/pull/268/commits/f16c1dd8398984119921cc674c0cf104b6ae9706
