### ISSUE TITLE
Deleting a Confluence page label 

### ISSUE THREAD

**Issue by bobgott** [atlassian-api/atlassian-python-api#266]
How can I delete a Confluence page label?  I can see how to retrieve and add labels but it is not clear how to remove a label.

**Comment by bobgott** [comment]
I wrote my own function which deletes a confluence label.  It would seem this function would be in the API. I'm wondering if the function I have below is the correct way? (running on confluence server 6.13.5)

```
def delete_page_label(self, page_id, label_name):
""" Delete Confluence page label

:param page_id: (str) Unique page id
:param label_name: (str) label to delete
:return: (dict) HTTP Response
"""
params = {"name": label_name}
url = f'rest/api/content/{page_id}/label'
try:
    return self.request('DELETE', path=url, headers=None, params=params)
except Exception as e:
    log.error(f"Error while deleting label '{label_name}' - {str(e)}")

```

**Comment by gonchik** [comment]
Hi! 
Sorry, for delay. 
Please, use that method on latest version.
https://github.com/atlassian-api/atlassian-python-api/pull/268/files#diff-0e4db85ea6e5747df6b8c187ca57993bR491

Method name remove_page_label(self, page_id, label):

Cheers,
Gonchik Tsymzhitov
