### ISSUE TITLE
Workaround limitation of 1000 in csv export for Jira

### ISSUE THREAD

**Issue by NathanShanners** [atlassian-api/atlassian-python-api#267]
I appreciate Jira 8.2 and upwards allow the config to be edited to increase the limitation of 1000 for the CSV export, but is there a way to iterate over this (aggregate the csv) if the user requests the limit above 1000?  Our Jira server is current on version 8 and upgrades are slow progress in our business so I wondered if this could easily be handled in the python call.

**Comment by gonchik** [comment]
Hi! 
I think you can split through jql splits. 
Typically you need to use functions like create > startofYear(-1)

**Comment by gonchik** [comment]
Could you provide, please, a full story of that?

**Comment by NathanShanners** [comment]
The Atlassian update for removing the limitation on the query is here

- https://confluence.atlassian.com/jirakb/exporting-a-filter-result-containing-more-than-1000-issues-191500982.html

The python I'm running just now is simply `csv_data = jira.csv(query, limit=max_results)` where if max_results is greater than 1000 I get a "Forbidden" error.  Currently I want to retrieve around 2,500 results and then write to a CSV file.  

For the jql split you recommend, would this require a for iterator and then multiple queries?  If so, how would you pass the starting index into the JQL string (variable called "query" in my example snippet)

**Comment by gonchik** [comment]
You can use this workaround 
https://confluence.atlassian.com/jirakb/exporting-a-filter-result-containing-more-than-1000-issues-191500982.html
it's dirty
you can use other wah like 
review you query

**Comment by NathanShanners** [comment]
Ok, thanks for the replies.
