### ISSUE TITLE
body.storage missing when searching by cql within Confluence

### ISSUE THREAD

**Issue by bobgott** [atlassian-api/atlassian-python-api#269]
I am doing a Confluence search using the cql() method but my results seem to be ignoring the 'expand' argument.

My cql search is as follows:

```
cql_str = 'space=\'DRAFT17D\' and type=\'page\' and parent=\'25476963\' order by title'
child_pages = self.cql(cql=cql_str, expand='body.storage)

```
The result, child_pages' is missing the dict element 'body' from the list items within 'results.

I can retrieve body.storage data when using the get_page_by_id() method.  Is this a bug or am I doing something wrong.

**Comment by gonchik** [comment]
Hi! 
@bobgott  I have checked on Confluence 7.2, it works well.
