### ISSUE TITLE
[Jira] Worklog Retrieval - Wrapper for limitation workaround of 20 worklogs

### ISSUE THREAD

**Issue by NathanShanners** [atlassian-api/atlassian-python-api#270]
As stated on the Atlassian site for Jira, there is a limitation for worklog retrieval of 20.  I currently have a bunch of issues worked on by multiple people with more than 20 worklogs and I see this limitation when running Jira.jql(query="key", limit=1000.  Is there a direct way of getting these worklogs using another method in the Jira library?  I have done something similar for the limit of 1000 issues (batch loop through dateCreated using date increments), I am at a loss currently of how to do something similar for worklogs however.

**Comment by gonchik** [comment]
Hi @NathanShanners , 
which method do you use?

**Comment by NathanShanners** [comment]
I currently use the jql method.  This provides worklogs in the list of dictionaries returned, but it is limited to 20 entries.  Thanks for all of your quick response BTW, they are greatly appreciated! :-)

**Comment by gonchik** [comment]
@NathanShanners  Sorry for the delay I have added the get worklogs the built-in method.
I will be happy if you provide more PRs
