### ISSUE TITLE
Is the library compatible with Jira v7?

### ISSUE THREAD

**Issue by philippeboyd** [atlassian-api/atlassian-python-api#273]
I'm using the python library to make calls to our Jira (v7.13.2) and I keep getting HTTP 406. Here's my simple test:

```python
jira = Jira(
    url='https://jira.company.com',
    username='user',
    password='password'
)

print(jira.user_properties(username="some_user")) # returns 406
print(jira.get_all_fields()) # returns 406
```

Is the library compatible with Jira v7?

**Comment by gonchik** [comment]
Hi! 
Yes, that library compatible with Jira 7. 
Also, methid is compatible/
https://docs.atlassian.com/software/jira/docs/api/REST/7.13.2/#api/2/field-getFields


Could you provide please, a debug logs ?

**Comment by gonchik** [comment]
Yes, it is compatible
