### ISSUE TITLE
install ssl error

### ISSUE THREAD

**Issue by swcrandell** [atlassian-api/atlassian-python-api#278]
I am new to python so I may have missed something but, I installed python 3.7.4 on WIndows 10. This included PIP 19.0.3. When I try to run the "pip install atlassian-python-api" I get the following errors and looking for some direction in resolving them:

Could not fetch URL https://pypi.org/simple/atlassian-python-api/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/atlassian-python-api/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)'))) - skipping
  Could not find a version that satisfies the requirement atlassian-python-api (from versions: )
No matching distribution found for atlassian-python-api
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)'))) - skipping

**Comment by swcrandell** [comment]
Some background: I am an admin on a Confluence Server 6.13.5 and I had a request to figure out a way to export a page as a PDF and send it to another server on the network through API as a JSON object with some metadata. The reporter would ideally want some sort of button on the page to trigger the export but, that is a whole other issue that I am trying to do it through a Confluence User Macro but, the most I can do is put a button the functions the same as the "Export to PDF" link.

**Comment by gonchik** [comment]
Hi! 

Could you install the pycharm ? 
https://www.jetbrains.com/pycharm/download
The community edition is enough. 

I hope that's IDE will cover all your problems
