### ISSUE TITLE
confluence.attach_file() can not upload a new version of an attached file

### ISSUE THREAD

**Issue by andreas-j-hauser** [atlassian-api/atlassian-python-api#279]
**Bug description**
If I try to upload a new version of an attached file with the function `confluence.attach_file()` nothing happend. Upload a completly new file the function works as expected. 

**Bug reason**
The bug based of two parts:
* The complete file name (including path) is used as name of the attachment if a new file is upload.
* The base file name (without path) is used to check if a attachment with this name already exists and upload a new version of the file.
=> The check if the file already exists fails and the function tries to upload a new file. This fails because the file already exists.

**Solution**
- Use the base file name as attachment name at the inital file upload

**Screenshot**
A screenshot of the attachments. The first attachment is uploaded by `confluence.attach_file()` the second attachment by hand.
![confluence_attachment_list](https://user-images.githubusercontent.com/53021429/61436204-9b499980-a93a-11e9-851e-a975a49e98c4.png)

**Comment by andreas-j-hauser** [comment]
I don't know the return value of confluence.attach_file() if I try to upload a new version of an attachment. I'll be check the return value of confluence.attach_file(). But I expected a response code not equal 200.

**Comment by gonchik** [comment]
@andreas-j-hauser  Is this works for you? 
For it works well

**Comment by gonchik** [comment]
It works.
