### ISSUE TITLE
new method confluence.attach_content() similar to confluence.attach_file()

### ISSUE THREAD

**Issue by andreas-j-hauser** [atlassian-api/atlassian-python-api#280]
## Description
Content which is generated in a script should be attached directly as a file to a confluence page, without the detour via the file system. 

The benifit of this improvment is to avoid orphan file artefacts (write content in a temporary file, read the file in `confluence.attach_file()` and hopfully do not miss to remove the temporary file).

The new method `confluence.attach_content()` should be work like `confluence.attach_file()` with the different that the content is give in a new parameter and not loaded from a file.

## Method signature
- The new mandatory parameter `content` gives the content which should be attached. The type should be binary.
- The existing parameter `filename` (change to name?) is used to specify the name of the attachment.
- An optional new parameter named `content_type` is used to specify the HTTP content type by caller. If no content type specified the existing auto-detection from function confluence.attach_file() is used.

```
    def attach_content(self, name, content, content_type=None, page_id=None, title=None, space=None, comment=None):
        """
        Attach (upload) a content to a page, if it exists it will update the
        automatically version the new file and keep the old one.
        :param title: The page name
        :type  title: ``str``
        :param space: The space name
        :type  space: ``str``
        :param page_id: The page id to which we would like to upload the file
        :type  page_id: ``str``
        :param name: The name of the attachment
        :type  name: ``str``
        :param content: Contains the content which should be uplaoded
        :type  content: ``binary``
        :param content_type: Specify the HTTP content type
        :type  content_type: ``str``
        :param comment: A comment describing this upload/file
        :type  comment: ``str``
        """
```
## Additional improvements
The implementation of `confluence.attach_file()` can be based on the new method `confluence.attach_content()`.

**Comment by gonchik** [comment]
@andreas-j-hauser  Looks like it's obsolete. 
If you still need something feel free to raise a pull request
