### ISSUE TITLE
Make method confluence.attach_file() more flexible

### ISSUE THREAD

**Issue by andreas-j-hauser** [atlassian-api/atlassian-python-api#281]
**Description of the improvements**
With following two improvements makes the method `confluence.attach_file()` more flexible. Both improvments will be very easly implemented if the implemenation of `confluence.attach_file()` based on `confluence.attach_content()` (see #280).

**Improvement 1: Attachment name regardless from filename**
The new optional parameter named `name` (type string) gives the caller the freedom to specifies the name of the attachment which is not based on the filename.  Benefit: Name of the attachment and the name of the file becomes independent.

If parameter name not given the method use the existing method to extract the attachment name from the file name.

**Improvement 2: Content type regardless from file extension**
The new optional parameter named `content_type` (type string) gives the caller the freedom to specify the HTTP content type of the of the attachment regardless to the extension of the file. 

If parameter content_type not given the method use the existing method to specify the content type by the file name extension.

**Comment by gonchik** [comment]
As I see that #284 cover your request :) 
Thanks for your PR
