### ISSUE TITLE
Confluence.get_page_by_title() should be work similar to Confluence.get_page_by_id()

### ISSUE THREAD

**Issue by andreas-j-hauser** [atlassian-api/atlassian-python-api#286]
As user I expect that `Confluence.get_page_by_title()` and `Confluence.get_page_by_id()` works very similar and returns the same result. At the moment both function are different.

- `Confluence.get_page_by_id()` allows me to customize the `expand` parameter, `Confluence.get_page_by_title()` not

If I had only the title and I need additional page attributes like content I have to call `confluence.get_page_by_title()` to get the page id. With the page id and the expand parameter I can call `confluence.get_page_by_id()` to get the content. 

**Changes/Improvement**
- Add parameter `expand` to function `confluence.get_page_by_title()` 
- Remove parameters `start` and `limit` from function `confluence.get_page_by_title()`. Both parameters are useless, because only the first result is returned. 
- Reduce the data transfer by set rest-api parameter `limit` fix to 1 for the rest api call in `confluence.get_page_by_title()`

**Examples**
Both functions `Confluence.get_page_by_title()` and `Confluence.get_page_by_id()` return equal data in the default case.
```
page_a = confluence.get_page_by_title(space, title)
page_b = confluence.get_page_by_id(page_a['id'])
```

Get content from a page if you have only the space and page name. You have to call two function. First call to get the page id from page name and the second function to get the content
```
page_id = confluence.get_page_id(space, title) # get_page_id calls get_page_by_title()
page_c = confluence.get_page_by_id(page_id,expand='body.storage,version')
print(page_c['body']['storage']['value'])
```

After the improvement you can do this by one call
```
page_c = confluence.get_page_by_title(space, title, expand='body.storage,version')
print(page_c['body']['storage']['value'])
```

**Effects**
Changes should be backward compatible. With a little restriction: function parameter start and limit are not longer available. But the usage of the parameter make no sense. Parameter `start` have to be 0 if it used. Parameter `limit` have to be 1 or greater if it used, but without any effects. In all other cases the function will be return `None`.

In case the parameters start and limit are used you will get a type error exception (`TypeError: get_page_by_title() got an unexpected keyword argument 'start'`)

**Additional**
```
def get_page_by_title(self, space, title, start=None, limit=None):
    """
    Returns the list of labels on a piece of Content.
    :param space: Space key
    :param title: Title of the page
    :param start: OPTIONAL: The start point of the collection to return. Default: None (0).
    :param limit: OPTIONAL: The limit of the number of labels to return, this may be restricted by
                        fixed system limits. Default: 200.
    :return: The JSON data returned from searched results the content endpoint, or the results of the
             callback. Will raise requests.HTTPError on bad input, potentially.
             If it has IndexError then return the None.
    """
```

```
def get_page_by_id(self, page_id, expand=None):
    """
    Get page by ID
    :param page_id: Content ID
    :param expand: OPTIONAL: expand e.g. history
    :return:
```

**Comment by gonchik** [comment]
Now I hope it will be better :)
