### ISSUE TITLE
Bibucket: Are hash_oldest and hash_newest backwards?

### ISSUE THREAD

**Issue by MironVeryanskiy** [atlassian-api/atlassian-python-api#287]
Is there a mixup of hash_oldest/hash_newest in the call signature of the bitbucket.get_diff() function?

**Example:**
For the following git commit log:
```
33333333 "Newest commit added"
22222222 "Another Commit"
11111111 "Some Commit'
00000000 "First Commit"
```
The **newest** commit added is "**33333333**", right?
The **oldest** commit in the repo is "**00000000**", right?

But when calling bitbucket.get_diff, the argument names need to be reversed to see a diff.
```
bitbucket.get_diff(
    project, 
    repository, 
    path, 
    hash_oldest="33333333", 
    hash_newest="00000000")
```

If this is intentional, please let me know if I'm misunderstanding the meaning of "hash_oldest" and "hash_newest".

**Comment by gonchik** [comment]
Hi! 

Sorry, I am little bit misunderstood your question. 
BTW, I used for my use case that reference:
https://docs.atlassian.com/bitbucket-server/rest/6.5.1/bitbucket-rest.html#idp220

For get diff

Cheers,
Gonchik Tsymzhitov

**Comment by MironVeryanskiy** [comment]
Hi @gonchik ,

No worries. Let me try to clarify using an example:

If I am looking to get the diff over the following 4 commits from the git log, which commit hash is "hash_oldest" and which is "hash_newest"?
```
33333333 (HEAD) "Newest commit added" <1 day ago>
22222222 "Another Commit" <2 days ago>
11111111 "Some Commit' <3 days ago>
00000000 "First Commit" <4 days ago>
```

**Comment by gonchik** [comment]
Hi! 
@MironVeryanskiy  I would say the method naming was incorrect I should to use the to and from notation for easier work with that. 

Once I will extend method naming add more info for that.

**Comment by gonchik** [comment]
Looks it works well
