### ISSUE TITLE
account password isn't support for api

### ISSUE THREAD

**Issue by ansonGitHub** [atlassian-api/atlassian-python-api#293]
password isn't supported since Jun 5th 2019 and api token replaced it by JIRA. is there any solution to invoke api by account password not api token

**Comment by gonchik** [comment]
Hi! 
Now I can't provide some solution

**Comment by kwilson-hapyak** [comment]
@ansonGitHub If you are are on a Cloud version, you can generate an API token here: https://id.atlassian.com/manage/api-tokens.  Then just use the token as your password when authenticating.

**Comment by MxBlu** [comment]
@ansonGitHub This is a restriction put in place by Atlassian, you cannot circumvent the need for an API key.
