### ISSUE TITLE
Lables and Profiles

### ISSUE THREAD

**Issue by mabusalah** [atlassian-api/atlassian-python-api#294]
Thank you guys for the great library that made our life easy. Would it be possible to include Add/Delete Labels to a page, also edit about me and profile fields.
Thank you

**Comment by SLRover** [comment]
Hi, @mabusalah!
Which software do you mean? Jira or Confluence? Or both?

**Comment by mabusalah** [comment]
Confluence

**Comment by SLRover** [comment]
Ok!
You can use `set_page_label` and `remove_page_label` methods.
Description of this methods is missing in docs. But we will add it in future.

**Comment by SLRover** [comment]
The full syntax is `set_page_label(page_id, label)` and `remove_page_label(page_id, label)`.

**Comment by mabusalah** [comment]
Thank you for your response and assistance.

**Comment by SLRover** [comment]
We added info about labels to docs.

**Comment by SLRover** [comment]
Thanks for your task!
