### ISSUE TITLE
Getting projects active sprints

### ISSUE THREAD

**Issue by arodzik** [atlassian-api/atlassian-python-api#296]
Hello, 

Is there a chance to get info from api about active sprints in particular project? Or even more - create an issue and add active sprint value to it

**Comment by gonchik** [comment]
Let's run that jql
`project = PROJECT_KEY and Sprint is not EMPTY `
Than get spint field ID and put into set

I hope after that you can fix it

**Comment by isaac-philip** [comment]
Are we looking for Active Sprints within a board? - https://docs.atlassian.com/jira-software/REST/8.9.0/#agile/1.0/sprint-getSprint

```python
Jira.get_all_sprint(board_id, state, start, limit)
```

can help with it.

**Comment by gonchik** [comment]
Closing. as it's obsolete

**Comment by meramsey** [comment]
In case anyone ends up referencing this like I did.

just the sprint id
```
active_sprints = jira.get_all_sprint(board_id, state="active", start=0, limit=50)
sprint_id = active_sprints["values"][0]["id"]
```

or if you want the nice name and id maybe you could do something like this or pass back the whole dict even
```
def get_active_sprint_id_name(board_id, jira):
    """
    Get the active sprint id and nice name.
    Args:
        board_id (str): 11
        jira (atlassian.Jira): Jira atlassian object with connection details

    Returns:
        dict: {'sprint_id': 5567, 'sprint_name': 'CoolProject Sprint XXXX'}

    """
    active_sprints = jira.get_all_sprint(board_id, state="active", start=0, limit=50)
    active_sprint = {"sprint_id": active_sprints["values"][0]["id"], "sprint_name": active_sprints["values"][0]["name"]}
    return active_sprint
```

**Comment by gonchik** [comment]
@meramsey feel free to provide example via PR :)
I will merge it
