### ISSUE TITLE
jira - get_all_sprint() method returns: {'errorMessages': ["Illegal value ['active'] for param state."], 'errors': {}}

### ISSUE THREAD

**Issue by arodzik** [atlassian-api/atlassian-python-api#300]
Hello,

I've spotted an issue with get_all_sprint() method. While i want to pass an state='active' argument it throws: {'errorMessages': ["Illegal value ['active'] for param state."], 'errors': {}}

I think this is caused by the  ```params['state'] = [state]```. Shouldn't this be like the ```params['startAt'] = start``` argument without square braces?

Maybe im using this metod in wrong way:
```jira.get_all_sprint(1053, state='active', start=250)```
```
...
    params = {}
    if start:
        params['startAt'] = start
    if limit:
        params['maxResults'] = limit
    if state:
        params['state'] = [state]
    url = 'rest/agile/1.0/board/{boardId}/sprint'.format(boardId=board_id)
    return self.get(url, params=params)

```

**Comment by gonchik** [comment]
@arodzik  looks like you you requesting in correct way. 
Because in my common instances the same result. 
I'll check it
