### ISSUE TITLE
Only the first 50 issues retrieved by query

### ISSUE THREAD

**Issue by SrancsikAtBitrise** [atlassian-api/atlassian-python-api#301]
It seems the `jira.jql()` does not support pagination. Only the first 50 issues are retrieved.
Using Jira Cloud.

**Comment by AlexanderLill** [comment]
@SrancsikAtBitrise please checkout the documentation in the code, I think you can try adding the `limit` parameter: https://github.com/atlassian-api/atlassian-python-api/blob/4eb49fcefd5a4ad105be609c594ce0c84ca6a97d/atlassian/jira.py#L55

**Comment by SrancsikAtBitrise** [comment]
Thanks, Alexander, for the quick response. I missed the default. Sadly, it still seems to be limited to 100.
