### ISSUE TITLE
Confluence delete_attachment_by_id doesn't work

### ISSUE THREAD

**Issue by Vanderhoof** [atlassian-api/atlassian-python-api#315]
Confluence method `delete_attachment_by_id` doesn't work:

```python
>>> res = con.get_attachments_from_content(27410959)
>>> att = res['results'][0]
>>> att['id']
'att27411717'
>>> con.delete_attachment_by_id(att['id'], None) # nothing happens
```

Nothing happens. If I use the `delete_attachment` method everything works:

```python
>>> con.delete_attachment(27410959, att['id'], None)
{'errorMessage': 'You are not permitted to perform this operation.'}
```

It's correct here, the user doesn't have permissions to delete attachments. If it had the permission, the latter method would work (checked). And the prior wouldn't (checked too)

**Comment by gonchik** [comment]
Hi! 
As I see that delete_attachment_by_id used as experimental, which is provided from Atlassian as is.
Hence it does not work. 
BTW, in which version do you know?

**Comment by gonchik** [comment]
Closed during inactivity
