### ISSUE TITLE
delete method doesn't return anything

### ISSUE THREAD

**Issue by Vanderhoof** [atlassian-api/atlassian-python-api#316]
[delete](https://github.com/atlassian-api/atlassian-python-api/blob/eddb0e34c4b0c0ebefcb5f9c308193309667f244/atlassian/rest_client.py#L217) method doesn't return anything. How can I find out if it worked or not?
Even in the docstring of the method it is stated that it should return empty dictionary. But there are no `return`s in the body of the method at all!

As consequence all methods which depend on this one (for example `Confluence.remove_content`) don't return anything either. That's awful!

**Comment by gonchik** [comment]
@Vanderhoof 
Feel free to check the latest version

Also, Thanks for your feedback :) 
I am happy for your PR :)

**Comment by Vanderhoof** [comment]
@gonchik 
Thank you!
