### ISSUE TITLE
Jira - Accessing ticket changelog in JQL

### ISSUE THREAD

**Issue by mattwakeman** [atlassian-api/atlassian-python-api#318]
Hello,

I cannot seem to access to a Jira Ticket Changelog via the Python wrapper.

`issues = jira.jql(
    jql_request,
    expand=changelog
    )`

Throws an error

When I look at the /issues/{0}/expand in the JSON response it lists an entry for Changelog, but I do not know how to access.

Any guidance would appreciated

Thanks

Matt

**Comment by mattwakeman** [comment]
Solved

'jql = jira.jql(
    jql_request,
    limit = 1,
    fields={
        'key',
        'summary',
        'self',
        'created'
        },
    expand='changelog.histories'
    )'

**Comment by YesimSem** [comment]
What did your jql request included? I try to solve that issue: https://stackoverflow.com/questions/21846194/jira-how-to-get-sprint-information but I failed...
