### ISSUE TITLE
Upload Plugin for other products

### ISSUE THREAD

**Issue by machinecode** [atlassian-api/atlassian-python-api#320]
Is there any roadmap for confluence, bitbucket and bamboo to upload plugins over this API?

**Comment by gonchik** [comment]
Hi! 
Do you need it? 
If so, sure we can add it. 
Because all that apps use the UPM, which works under the same REST endpoint :)

**Comment by machinecode** [comment]
Yeap, I need it :)

Thanks!

**Comment by gonchik** [comment]
https://github.com/atlassian-api/atlassian-python-api/commit/a1ab25e087ad0b4b4e839538b3f983f415e974a4

**Comment by machinecode** [comment]
Thanks!
