### ISSUE TITLE
Unable to query JIRA as URL is suffixed with '/wiki'

### ISSUE THREAD

**Issue by nullin** [atlassian-api/atlassian-python-api#321]
Using `atlassian-python-api==1.13.28`

Our JIRA instance is accessible at https://company.atlassian.net/ and Confluence at https://company.atlassian.net/wiki.

After the commit https://github.com/atlassian-api/atlassian-python-api/commit/d4e843b20ea7e91873aac95529b8513e3b62aae2#diff-a519e0301a0f249eae8b763ced476674, we are unable to query for data because the rest client automatically suffixes `/wiki` to the URL we pass in for communicating with JIRA.

On reverting this change, our scripts start working again.

**Expected**:

```
curl --user user@email.com:token 'https://company.atlassian.net/rest/api/2/issue/JEDI-18821?fields=*all'
{"expand":"renderedFields,names,schema,operations,editmeta,changelog,versionedRepresentations",
"id":"99725",
"self":"https://company.atlassian.net/rest/api/2/issue/99725",
"key":"JEDI-18821"
...
...
```

**Actual**:

```
>>> jira = Jira('https://company.atlassian.net/', 'user@email.com', 'token')
>>> jira.issue('JEDI-18821')
{'message': 'null for uri: https://company.atlassian.net/wiki/rest/api/2/issue/JEDI-18821?fields=*all', 
'status-code': 404}
```

**Comment by gonchik** [comment]
That commit will fix it
https://github.com/atlassian-api/atlassian-python-api/commit/d74e7ec25d09806b70b642ee4e1d0a7e1cbb5808
