### ISSUE TITLE
Support for Kerberos authentication

### ISSUE THREAD

**Issue by cfinkenstadt** [atlassian-api/atlassian-python-api#322]
I see there is support for both `Basic` and `OAuth1` authentication into the Atlassian products.  For those folks who have installed Kerberos SSO support (from `Kantega` in this case), would it be possible to support automatic logon?  This assumes that `curl` in the system path supports it:

*GSS-Negotiate* is the most important option to build in to Curl.

```
$ curl --version
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.36 zlib/1.2.7 libidn/1.28 libssh2/1.4.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz unix-sockets

$ curl -v --negotiate -u : https://wiki.example.com/login.action
```

The successful result of this is a `Set-Cookie: JSESSIONID=$COOKIE; Path=/; HttpOnly` HTTP header; likely the same as the output the other authenticators.

**Comment by offa** [comment]
I have a working Kerberos implementation for windows, but it can be ported to other systems easily. I can provide a PR, hopefully within the next days.
