### ISSUE TITLE
[Confluence] Index Error when looking up page by title

### ISSUE THREAD

**Issue by LeoPROld** [atlassian-api/atlassian-python-api#323]

**Comment by gonchik** [comment]
Hi! 
Could you attach the DEBUG  logs, please?

**Comment by drryu** [comment]
@gonchik seems like if the page does not exist, the code tries to parse through an empty array

DEBUG:atlassian.rest_client:curl --silent -X GET -H 'Content-Type: application/json' -H 'Accept: application/json'  'https://confluence.ascensus.com/rest/api/content'
DEBUG:urllib3.connectionpool:Resetting dropped connection: confluence.ascensus.com
DEBUG:urllib3.connectionpool:https://confluence.ascensus.com:443 "GET /rest/api/content?spaceKey=GLOBAL&title=SamplePage HTTP/1.1" 200 None
DEBUG:atlassian.rest_client:Received: 200
 {'results': [], 'start': 0, 'limit': 25, 'size': 0, '_links': {'self': 'https://confluence.ascensus.com/rest/api/content?spaceKey=GLOBAL&title=SamplePage', 'base': 'https://confluence.ascensus.com', 'context': ''}}
ERROR:atlassian.confluence:list index out of range

**Comment by jlwvb21** [comment]
When the page does not exist on get_page_by_title you log out the error:
        try:
            return (self.get(url, params=params) or {}).get('results')[0]
        except IndexError as e:
            log.error(e)
            return None
Can you remove the log?

**Comment by gonchik** [comment]
@jlwvb21  @drryu @LeoPROld 
Now it works like this 
`            try:
                return (self.get(url, params=params) or {}).get('results')[0]
            except (IndexError, TypeError) as e:
                log.error("Can't find '{title}' page on the {url}!".format(title=title, url=self.url))
                log.debug(e)
                return None`

and on my systems works well. 
Feel free reopen if it's needed
