### ISSUE TITLE
[Confluence] Add method to move Confluence documents between spaces

### ISSUE THREAD

**Issue by jsjohnst** [atlassian-api/atlassian-python-api#326]
I needed the ability to move a bunch of pages from one Space to another in Confluence and it is very poorly supported it seems. Thankfully, I found a way to do it, so sharing this in hopes someone else will find it useful (and/or maybe you can officially support it).

```
from atlassian import Confluence

confluence = Confluence(url='YOUR_INSTANCE_URL',
                 username='YOUR_USERNAME',
                 password='YOUR_API_KEY')

page_id = '' # ID of the page you want to move
space_key = '' # the Space key of the destination Space
title = '' # The title of the new parent page in the destination Space

confluence.get("/pages/movepage.action?pageId=%s&spaceKey=%s&targetTitle=%s&position=append" % (page_id, space_key, title),
                  headers={'x-atlassian-token': 'no-check'}
                 )
```

If you are doing it in a script, I highly recommend adding a `time.sleep(5)` after the move call otherwise you will get errors occasionally (I also tested with a sleep of 2 seconds, but got a few errors, but never any with a sleep of 5).

Reference: https://community.atlassian.com/t5/Answers-Developer-Questions/Move-Page-Confluence-Rest-API/qaq-p/503204

**Comment by gonchik** [comment]
@jsjohnst  Thanks for that. 
I will be happy if you next time provide PR as well :)
