### ISSUE TITLE
[Bitbucket] add method for modifying a file directly on bitbucket

### ISSUE THREAD

**Issue by rjlardizabal** [atlassian-api/atlassian-python-api#327]
Something like:

def commit_api_file_on_branch(content, message, branch):
    data = {
        "content": content,
        "message": message,
        "branch", branch
    }

put(url='/rest/api/1.0/projects/{projectKey}/repos/{repositorySlug}/browse/new-file.txt')

**Comment by gonchik** [comment]
@rjlardizabal I did not find any reference https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Bworkspace%7D/%7Brepo_slug%7D/downloads/%7Bfilename%7D

**Comment by Spacetown** [comment]
@gonchik This is done by a [POST](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Bworkspace%7D/%7Brepo_slug%7D/downloads#post) request.

**Comment by gonchik** [comment]
Thank you!
