### ISSUE TITLE
Confluence: Export to word API

### ISSUE THREAD

**Issue by gsemet** [atlassian-api/atlassian-python-api#337]
This would be nice to have the `exportword` exposed as a `get_page_as_word` method in the confluence object. Thanks

**Comment by gsemet** [comment]
Done through the following function:
```python

    def get_page_as_word(self, page_id):
        """
        Export page as standard word exporter.

        :param page_id: Page ID
        :return: Word File
        """
        headers = self.form_token_headers
        url = 'exportword?pageId={pageId}'.format(pageId=page_id)
        return self.get(url, headers=headers, not_json_response=True)

```

**Comment by gonchik** [comment]
@gsemet  Feel free to provide a PR :)

**Comment by gonchik** [comment]
Just added
https://github.com/atlassian-api/atlassian-python-api/commit/e18f91d5e8ddd1d40fbd1c367a982d26d02bc233

**Comment by batchuchaitanya** [comment]
get_page_as_word is giving data in bytes for .doc format and not .docx. Do we have any method to get .docx format

**Comment by TestEg-Tian** [comment]
Why can't I find the ExportWord API on the official website

**Comment by gonchik** [comment]
@batchuchaitanya  @TestEg-Tian  could you raise a dedicated  ticket ? 
I will prepare for Confluence DC method
