### ISSUE TITLE
bamboo max-result url param

### ISSUE THREAD

**Issue by xinfared** [atlassian-api/atlassian-python-api#346]
Looking at the Bamboo class in bamboo.py most the calls are passing max_results=25 kwarg to the base_list_call which converts this to a max-results param. Trying to override this does not change the number of results returned.

Looking at the bamboo api documentation (https://developer.atlassian.com/server/bamboo/bamboo-rest-resources/) the proper param should be 'max-result' (ex: /rest/api/latest/project?max-result=10)

**Comment by djachkov** [comment]
Hi @xinfared !
This is an issue with the generator, which sends you all pages of the results
I've fixed it in the new PR
