### ISSUE TITLE
Make kerberos dependency optional

### ISSUE THREAD

**Issue by gsemet** [atlassian-api/atlassian-python-api#349]
Kerberos package is a mess to install on some environment such as alpine or on Windows (it requires VC++14, ...). I do not need it, so I wonder if this dependency cannot be made optional ?

**Comment by coldoch** [comment]
The Kerberos changes since 1.13.31 have also broken the pip3 install of the package on Ubuntu and Debian Linux.

**Comment by offa** [comment]
I've opened a work-in-progress PR to address this. There are still some issues left, so helping hands and comments are welcome.

**Comment by gonchik** [comment]
I would say now everything works well :) 
Thanks @offa for your effort
