### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'strip' for all confluence calls

### ISSUE THREAD

**Issue by DataistDogma** [atlassian-api/atlassian-python-api#356]
Hi,

All calls I make using the confluence API return the same error.
E.g.

page_id = '530779447'
confluence.get_page_by_id(page_id, expand=None)
----------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-180-a482ad50fc1f> in <module>()
      1 page_id = '530779447'
----> 2 confluence.get_page_by_id(page_id, expand=None)

C:\Program Files\Anaconda3\lib\site-packages\atlassian\confluence.py in get_page_by_id(self, page_id, expand)
    146             params = {'expand': expand}
    147         url = 'rest/api/content/{page_id}'.format(page_id=page_id)
--> 148         return self.get(url, params=params)
    149 
    150     def get_page_labels(self, page_id, prefix=None, start=None, limit=None):

C:\Program Files\Anaconda3\lib\site-packages\atlassian\rest_client.py in get(self, path, data, flags, params, headers, not_json_response, trailing)
    182         """
    183         answer = self.request('GET', path=path, flags=flags, params=params, data=data, headers=headers,
--> 184                               trailing=trailing)
    185         if not_json_response:
    186             return answer.content

C:\Program Files\Anaconda3\lib\site-packages\atlassian\rest_client.py in request(self, method, path, data, flags, params, headers, files, trailing)
    106         :return:
    107         """
--> 108         self.log_curl_debug(method=method, path=path, headers=headers, data=data, trailing=None)
    109         url = self.url_joiner(self.url, path, trailing)
    110         if params or flags:

C:\Program Files\Anaconda3\lib\site-packages\atlassian\rest_client.py in log_curl_debug(self, method, path, data, headers, trailing, level)
     79             headers=' -H '.join(["'{0}: {1}'".format(key, value) for key, value in headers.items()]),
     80             data='' if not data else "--data '{0}'".format(json.dumps(data)),
---> 81             url='{0}'.format(self.url_joiner(self.url, path=path, trailing=trailing)))
     82         log.log(level=level, msg=message)
     83 

C:\Program Files\Anaconda3\lib\site-packages\atlassian\rest_client.py in url_joiner(url, path, trailing)
     87     @staticmethod
     88     def url_joiner(url, path, trailing=None):
---> 89         url_link = '/'.join(s.strip('/') for s in [url, path])
     90         if trailing:
     91             url_link += '/'

C:\Program Files\Anaconda3\lib\site-packages\atlassian\rest_client.py in <genexpr>(.0)
     87     @staticmethod
     88     def url_joiner(url, path, trailing=None):
---> 89         url_link = '/'.join(s.strip('/') for s in [url, path])
     90         if trailing:
     91             url_link += '/'

**AttributeError**: 'dict' object has no attribute 'strip'

**Comment by gonchik** [comment]
Hi @DataistDogma 
Sorry, I can't reproduce it. 
Could you reproduce on latest?

**Comment by gonchik** [comment]
Hi @DataistDogma , 
Sorry I can't reproduce your request
