### ISSUE TITLE
[Confluence] Better error handling for large Confluence servers.

### ISSUE THREAD

**Issue by thatguyfig** [atlassian-api/atlassian-python-api#360]
I am getting this error when attempting to use update_or_create(), I believe the underlying function get_page_by_title() which iterates through the list of pages is far too unstable. Too often it will return the below error and break the rest of the process.

This could be isolated to underspec'd confluence servers with way too many pages, as i tend to see this issue when the server is heavily used. I have tried to make a workaround for this issue but ultimately I need to get access to the page_id to do anything with the pages themselves.

Any suggestions would be greatly appreciated.

```
Traceback (most recent call last):
  File "make-docs.py", line 81, in <module>
    body=str(html_pretty)
  File "C:\tools\Anaconda3\envs\py36\lib\site-packages\atlassian\confluence.py", line 773, in update_or_create
    if self.page_exists(space, title):
  File "C:\tools\Anaconda3\envs\py36\lib\site-packages\atlassian\confluence.py", line 37, in page_exists
    if self.get_page_by_title(space, title):
  File "C:\tools\Anaconda3\envs\py36\lib\site-packages\atlassian\confluence.py", line 128, in get_page_by_title
    return (self.get(url, params=params) or {}).get('results')[0]
AttributeError: 'str' object has no attribute 'get'
```

**Comment by gonchik** [comment]
Hi! 
I am going to migrate a big Confluence, then I will try to reproduce that. 
in common use case I just extend the timeout which helps me :)

Cheers,
Gonchik Tsymzhitov

**Comment by thatguyfig** [comment]
Hey Gonchik,

Thanks for taking the time to reproduce. 

As for the timeout you mentioned, that's not something I've seen in documentation anywhere. Is that a parameter within the confluence client? Or in individual methods like that of update_or_create()?

Do you have an example you can share?

FYI - I managed to get a workaround for obtaining child page IDs through the REST API when querying the parent metadata. Can share if anyone is interested.

Cheers

**Comment by gonchik** [comment]
Hi! 
I meant that timeout which is in the rest_client module, 
https://github.com/atlassian-api/atlassian-python-api/blob/master/examples/confluence-subtree-cleaner.py#L17

so in reality it's requests timeout parameter
https://realpython.com/python-requests/#timeouts

**Comment by thatguyfig** [comment]
Hi, 

Thanks for finding that, I will give that a try but I suspect it could be the server playing up. 

Cheers

**Comment by gonchik** [comment]
So I am played with huge instances, looks like it works well. 
Just timeout help enough
