### ISSUE TITLE
[Bitbucket] set repo default branch

### ISSUE THREAD

**Issue by tuxmaster5000** [atlassian-api/atlassian-python-api#363]
Please add an function to set/get the default branch of an repo.

**Comment by gonchik** [comment]
Hi! 

Feel free use the latest version where you can find the method to set a default branch
https://github.com/atlassian-api/atlassian-python-api/commit/8312b0627bdbd10d48b0c4312302c684e7a2a39f#diff-2047315f8d9af8f3abda412fbffc45c3R501

Cheers,
Gonchik Tsymzhitov
