### ISSUE TITLE
TypeError: string indices must be integers when password invalid

### ISSUE THREAD

**Issue by jpeckham** [atlassian-api/atlassian-python-api#365]
> Traceback (most recent call last):
>   File "c:\Users\James\.vscode\extensions\ms-python.python-2019.10.41019\pythonFiles\ptvsd_launcher.py", line 43, in <module>
>     main(ptvsdArgs)
>   File "c:\Users\James\.vscode\extensions\ms-python.python-2019.10.41019\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 432, in main
>     run()
>   File "c:\Users\James\.vscode\extensions\ms-python.python-2019.10.41019\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 316, in run_file
>     runpy.run_path(target, run_name='__main__')
>   File "C:\Users\James\Anaconda3\lib\runpy.py", line 263, in run_path
>     pkg_name=pkg_name, script_name=fname)
>   File "C:\Users\James\Anaconda3\lib\runpy.py", line 96, in _run_module_code
>     mod_name, mod_spec, pkg_name, script_name)
>   File "C:\Users\James\Anaconda3\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "c:\projects\jira-scripts\assign-environment-permissions.py", line 14, in <module>
>     for project in bamboo.projects():
>   File "C:\Users\James\Anaconda3\lib\site-packages\atlassian\bamboo.py", line 33, in _get_generator
>     results = response[elements_key]
> TypeError: string indices must be integers

I get the above error when my password isn't valid.

sample code:
```
for project in bamboo.projects():
    print(project)
```

**Comment by gonchik** [comment]
It has been fixed.
