### ISSUE TITLE
Issue with requests with data=null

### ISSUE THREAD

**Issue by YaronNetanel** [atlassian-api/atlassian-python-api#366]
We are migrating to some new version of Confluence (to work on cloud).
I see an issue that any HTTP request with data=null (coming from files=None) is taken as bad request.
This used to be ok for our current version (setup) of Confluence.
If I fix rest_client to be:

data='' if not data else json.dumps(data)

Instead of current code:
data = json.dumps(data)

then it works for me.
Is this a known issue? Does it make sense?

**Comment by gonchik** [comment]
Hi! 
Thanks for that catch :) 
Added that parameter into rest_client
`data = None if not data else json.dumps(data)`

**Comment by gonchik** [comment]
https://github.com/atlassian-api/atlassian-python-api/commit/fa9e320c7c8dbe2c8023f6b696f998f440bcedb8
