### ISSUE TITLE
Atlassian-Cloud Integration

### ISSUE THREAD

**Issue by arne21a** [atlassian-api/atlassian-python-api#369]
I have some questions about this project in combination with Atlassian cloud.

It looks like there are hardcoded api versions and paths in the bitbucket module.
e.g. 
`        url = 'rest/api/1.0/projects/{projectKey}/repos?limit=1000'.format(
            projectKey=project_key)
        return self.get(url)
`
this seems to be not compatible with bitbucket cloud.

I also did not find any implementation for oauth2, which would also help to use the cloud services.

Am I missing something?
If not, are there a plan to implement this project for cloud services?

**Comment by gonchik** [comment]
@arne21a  @wesinator Let's try to use the last version.
https://github.com/atlassian-api/atlassian-python-api/blob/master/atlassian/bitbucket.py
I will be happy if you provide more Pull Requests :)

Cheers,
Gonchik Tsymzhitov
