### ISSUE TITLE
tempo_timesheets_get_worklogs by epic or issue

### ISSUE THREAD

**Issue by lmorroni** [atlassian-api/atlassian-python-api#380]
Hello,
I am looking to pull worklogs for a given epic/issue based on a date range.  Looking at tempo_timesheets_get_worklogs and I do not see the ability to pass in an issue id or epic.  I am wondering if this is something that is possible with this library.
Thank You,
Larry

**Comment by gonchik** [comment]
Thanks @djachkov  
@lmorroni  for the raising issue!
