### ISSUE TITLE
[2.14.3] wrong egg path

### ISSUE THREAD

**Issue by tuxmaster5000** [atlassian-api/atlassian-python-api#384]
The files are placed at:
/usr/lib/python3.6/site-packages/atlassian_python_api-1.14.3-py3.6.egg-info
instant of:
/usr/lib/python3.6/site-packages/atlassian_python_api-2.14.3-py3.6.egg-info

**Comment by gonchik** [comment]
Hi! 
Sorry, it should be 1.14.3, I made a type on both release. 
BTW, time to release 1.14.4 with new methods

**Comment by gonchik** [comment]
I have released 1.14.4.
