### ISSUE TITLE
[Question] - how to properly segment out connection

### ISSUE THREAD

**Issue by lia-cha-avalara** [atlassian-api/atlassian-python-api#388]
Not sure how to ask this but I can authenticate with OAuth fine if i just write the script from top down. I wanted to make it a bit cleaner by separating out the connection piece in a separate class/module and importing that into my main module. I did something like...

`from atlassian import Jira
import os

 class JiraAccount(Jira):
 def __init__(self):
 super().__init__():
self.access = os.environ['ACCESS_KEY']
self.secret = os.environ['SECRET_KEY']

key_cert = None
key_file = "path\to\rsa.pem"
with open(key_file, "r") as key_cert_data:
    key_cert = key_cert_data.read()

oauth_dict = {
        'access_token': CLIENT_ACCESS,
        'access_token_secret': CLIENT_SECRET,
        'consumer_key': 'get-jira-issue',
        'key_cert': key_cert
    }

 jira = Jira(url="jira_server_url", oauth=oauth_dict)
 return jira
`

Then in my main module i'd do something like

jira = JiraAccount()

But then I get some error about JiraAccount not being an iterable. If i just threw the above code into a regular function in my main module, things work okay...

**Comment by gonchik** [comment]
Hi! 
Have you reordered the super.init() method ?

**Comment by gonchik** [comment]
Hi 
You can do a call method with exist fields. 
`from atlassian import Jira
from var import config
from pprint import pprint
import logging

ATLASSIAN_USER = config.JIRA_LOGIN
ATLASSIAN_PASSWORD = config.JIRA_PASSWORD

logging.basicConfig(level=logging.ERROR)

jira = Jira(
    url=config.JIRA_URL,
    username=ATLASSIAN_USER,
    password=ATLASSIAN_PASSWORD)
jira.get_all_custom_fields()
`
