### ISSUE TITLE
[Jira] bulk_issue endless recursion

### ISSUE THREAD

**Issue by Cyber-Bro** [atlassian-api/atlassian-python-api#389]
I got this, then user pass a few invalid keys, and none of them are in Jira. Example JQL values:

> key in ("TEST-f4123", "TEST-14g334g", "fdf34f")

Function in jira.py:
```    
def bulk_issue(self, issue_list, fields='*all'):
        """
        :param fields:
        :param list issue_list:
        :return:
        """
        missing_issues = list()
        jql = 'key in ({})'.format(', '.join(['"{}"'.format(key) for key in issue_list]))
        query_result = self.jql(jql, fields=fields)
        if 'errorMessages' in query_result.keys():
            for message in query_result['errorMessages']:
                for key in issue_list:
                    if key in message:
                        missing_issues.append(key)
                        issue_list.remove(key)
            query_result, missing_issues = self.bulk_issue(issue_list, fields)
        return query_result, missing_issues
```

So it goes to `issue_list.remove(key)`, removes invalid keys one by one and enters endless recursion cycle on line 516 with following error:

`Error in JQL Query: Expecting either a value, list or function but got \')\'. You must surround \')\' in quotation marks to use it as a value. (line 1, character 9)`

**Comment by gonchik** [comment]
Hi! 
It's so specific situation. 
I have added an additional checker based on official regex expression matcher

**Comment by Cyber-Bro** [comment]
Still facing it in 1.14.5

**Comment by Cyber-Bro** [comment]
> I have added an additional checker based on official regex expression matcher
@gonchik 

Hi!
I'm still facing it in 1.14.5

**Comment by gonchik** [comment]
And did you use that scope issue_list of items  - "TEST-f4123", "TEST-14g334g", "fdf34f" 
which is covered by
 https://github.com/atlassian-api/atlassian-python-api/blob/master/atlassian/jira.py#L579

**Comment by Cyber-Bro** [comment]
Sure

**Comment by gonchik** [comment]
@Cyber-Bro  Is it reproducible?

**Comment by Cyber-Bro** [comment]
> @Cyber-Bro Is it reproducible?

Unfortunately, I no longer have the opportunity to quickly check this. Have you changed anything else in the repository?

**Comment by gonchik** [comment]
Yeap. 
`       jira_issue_regex = re.compile(r'[A-Z]{1,10}-\d+')
        matched_issue_keys = list()
        for key in issue_list:
            if re.match(jira_issue_regex, key):
                matched_issue_keys.append(key)`

And now also, made set before generating jql

**Comment by gonchik** [comment]
https://github.com/atlassian-api/atlassian-python-api/commit/33bec0e78e5351b61c2d631e2a7772bd02cbf9ab
