### ISSUE TITLE
[Bitbucket] Merge a Pull Request using bitbucket.py?

### ISSUE THREAD

**Issue by ddj116** [atlassian-api/atlassian-python-api#398]
I'm loving the python interface so far, but there's one thing I can't seem to do using function calls in `bitbucket.py` -- merge a pull request. Is this just not supported? It appears to exist as a functionality in [the bitbucket REST API](https://docs.atlassian.com/bitbucket-server/rest/6.8.0/bitbucket-rest.html), with this form: 
```
/rest/api/1.0/projects/{projectKey}/repos/{repositorySlug}/pull-requests/{pullRequestId}/merge?version
```
Just wondering if I'm missing something. Can/should I use `AtlassianRestAPI::post` to directly POST the URL I need?

Nice project and thanks in advance!

**Comment by djachkov** [comment]
@ddj116 I've added some PR management methods in the #400

**Comment by gonchik** [comment]
Thanks @djachkov

**Comment by ddj116** [comment]
Thanks so much @djachkov ! 👍
