### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by masics** [atlassian-api/atlassian-python-api#402]
I get an error while using a library function:
File "confluence_publish.py", line 98, in update_branch_page
    main_page_id = confluence.get_page_id(SPACENAME, MAINPAGE)
  File "/home/test/confluence_publish/venv/lib/python3.8/site-packages/atlassian/confluence.py", line 87, in get_page_id
    return (self.get_page_by_title(space, title) or {}).get('id')
  File "/home/test/confluence_publish/venv/lib/python3.8/site-packages/atlassian/confluence.py", line 130, in get_page_by_title
    return (self.get(url, params=params) or {}).get('results')[0]

**Comment by gonchik** [comment]
Hi @masics , 
which version do you use?

**Comment by gonchik** [comment]
This is on last version
`            try:
                return (self.get(url, params=params) or {}).get('results')[0]
            except IndexError as e:
                log.error("Can't find {title} page on the {url}!".format(title=title, url=self.url))
                log.debug(e)
                return None`

**Comment by masics** [comment]
It's not enough. I've created a pull request #410

**Comment by gonchik** [comment]
Thanks!

**Comment by gonchik** [comment]
@masics  That PR was merged and uploaded, 
feel free to use the last version
