### ISSUE TITLE
Add documentation for confluence.append_page()

### ISSUE THREAD

**Issue by LudovicRousseau** [atlassian-api/atlassian-python-api#403]
The method `confluence.append_page()` is NOT documented anywhere in https://github.com/atlassian-api/atlassian-python-api/blob/master/docs/confluence.rst

I had to read the source code to find the method I needed in https://github.com/atlassian-api/atlassian-python-api/blob/master/atlassian/confluence.py#L746

**Comment by gonchik** [comment]
Hi! 
As I see it has been added, 
btw. feel free to provide a PR for the improve library :) 

Cheers,
Gonchik Tsymzhitov
