### ISSUE TITLE
[Confluence] Add documentation for expand= parameter

### ISSUE THREAD

**Issue by LudovicRousseau** [atlassian-api/atlassian-python-api#404]
In https://github.com/atlassian-api/atlassian-python-api/blob/master/docs/confluence.rst I could not find the documentation for the `expand=` parameter.

I want to get the page content and I had to read the source code to find that `confluence.get_page_by_id(page_id, expand='body.storage')` does what I want.

**Comment by gonchik** [comment]
Do you mean that one? 
https://docs.atlassian.com/ConfluenceServer/rest/7.1.0/#api/content-getContentById

**Comment by LudovicRousseau** [comment]
It is better.
But he link you give is the documentation of the REST server API, not the documentation of the Python module.
And the field expand is not completely documented. The default value is indicated, 2 possible values are also listed. But the complete list of the valid values is not provided.

How I am supposed to guess what possible value I can use for expand=?

**Comment by gonchik** [comment]
So that info is not provided in official doc, but I can add from source code.

**Comment by gonchik** [comment]
As I see nowhere provided the clear docs around that.
