### ISSUE TITLE
Execute Build function always returns None response after triggering the build in Bamboo

### ISSUE THREAD

**Issue by lakhangulati** [atlassian-api/atlassian-python-api#405]
I faced this issue and on debugging I found that the headers in the _execute_build_ function in _bamboo.py_ is setting the HTML headers in the _post_ request and then trying to convert the response into json using .json() method that always fails and catch block returns the _None_ response.

I fixed this error by changing the below in the _execute_build_ function. 
From : **headers = self.form_token_headers**
To: _headers = self.default_headers_

Could you please review and fix in the code?

Please note that I am getting permission errors while pushing this change so raised an issue for you guys. please see to it. 

Thanks
Lakhan

**Comment by lakhangulati** [comment]
Hi Gonchik,

I see that you have fixed the issue in the api. Could you please publish new version of the API so that I can use it.

**Comment by gonchik** [comment]
Hi @lakhangulati 
It's published. 
Feel free reuse it. 
Sorry for delay

Cheers,
Gonchik Tsymzhitov
