### ISSUE TITLE
1.13.29 version disapeared on Pypi?

### ISSUE THREAD

**Issue by gsemet** [atlassian-api/atlassian-python-api#407]
Hi. It looks like at least one version previously available on Pypi (1.13.29) my lockfile was refering to has been removed. Please avoid removing published version !

**Comment by fmarmar** [comment]
Version 1.14.1 is gone too.

**Comment by gonchik** [comment]
Hi! 
Yes, a few releases was removed. 
Is this possible in lcokfile just notify about the removements of releases?
I am planning to remove old versions

**Comment by fmarmar** [comment]
You shouldn't remove old versions, at least not from official repositories like pypi.org. There is no way to notify consumers about a release been removed, and not everybody can update or downgrade to other version easily

**Comment by gonchik** [comment]
@fmarmar Got it.

**Comment by gsemet** [comment]
Thanks. You can do pretty much everything you want with prerelease (.dev1,...) but "releases" should be always avalaible, even if they are buggy, deprecated or even if they do not work. Publish new versions.
PS: I do not understand why pypi allows removing of published packages.
