### ISSUE TITLE
DeprecationWarning invalid escape sequence from atlassian.Jira

### ISSUE THREAD

**Issue by JnyJny** [atlassian-api/atlassian-python-api#409]
**Environment**:
- atlassian-python-api 1.14.5, Jira module
- python 3.7.5
- pytest 3.10.1

After adding `atlassian.Jira` to my project, I started seeing this warning in the pytest output:

```
=========================================== warnings summary ============================================
../lib/python3.7/site-packages/atlassian/jira.py:579
../lib/python3.7/site-packages/atlassian/jira.py:579: DeprecationWarning: invalid escape sequence \d
    jira_issue_regex = re.compile('[A-Z]{1,10}-\d+')

-- Docs: https://docs.pytest.org/en/latest/warnings.html
================================= 3 passed, 1 warnings in 1.69 seconds ==================================
```

The answer to this Stackoverflow [question](https://stackoverflow.com/questions/50504500/deprecationwarning-invalid-escape-sequence-what-to-use-instead-of-d)  advocates using a raw string instead of a Unicode string as the argument to `re.compile`.

Modifying line 529 of `jira.py` to:

```
    jira_issue_regex = re.compile(r'[A-Z]{1,10}-\d+')
```

fixes the warning in pytest.

**Comment by gonchik** [comment]
@JnyJny Thanks for that caught, 
Feel free for the next time provide a PR :) 

Cheers,
Gonchik Tsymzhitov
