### ISSUE TITLE
[Confluence] AttributeError: 'Response' object has no attribute 'get' in update_page in advanced mode

### ISSUE THREAD

**Issue by mikitachab** [atlassian-api/atlassian-python-api#412]
Hi,
I get an error while calling `Confluence.update_page`  in advanced mode:
```
  File "/.../venv/lib/python3.6/site-packages/atlassian/confluence.py", line 705, in update_page
    if self.is_page_content_is_already_updated(page_id, body):
  File "/.../venv/lib/python3.6/site-packages/atlassian/confluence.py", line 665, in is_page_content_is_already_updated
    confluence_content = (((self.get_page_by_id(page_id, expand='body.storage') or {})
AttributeError: 'Response' object has no attribute 'get'
```
looks like  code at [this line](https://github.com/atlassian-api/atlassian-python-api/blob/88156a507873eea75d52436f09ff872435590450/atlassian/confluence.py#L696) expects that `self.get_page_by_id` always returns `dict` object but  [AtlassianRestAPI.get](https://github.com/atlassian-api/atlassian-python-api/blob/88156a507873eea75d52436f09ff872435590450/atlassian/rest_client.py#L191) method, which is used inside of `get_page_by_id`, can also return `Response` in advanced mode or `str` in case of any errors.

**Comment by gonchik** [comment]
Could you provide please, in debug more the info? 
I will add more try catch contructions

**Comment by mikitachab** [comment]
My env:

- Ubuntu 18.10
- Python 3.6
- atlassian-python-api==1.14.2

Sample code to reproduce the error:
```py
import os
import atlassian
from constants import CONFLUENCE_PAGE_TITLE, CONFLUENCE_URL, CONFLUENCE_PAGE_ID

confluence = atlassian.Confluence(
    url=CONFLUENCE_URL,
    username=os.environ.get('ATLASSIAN_USER'),
    password=os.environ.get('ATLASSIAN_PASS'),
    advanced_mode=True
)
confluence.update_page(CONFLUENCE_PAGE_ID, CONFLUENCE_PAGE_TITLE, '<h1>hello world!</h1>')
```
Full trace-back generated by code above:
```
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    confluence.update_page(CONFLUENCE_PAGE_ID, CONFLUENCE_PAGE_TITLE, '<h1>hello world!</h1>')
  File "/.../venv/lib/python3.6/site-packages/atlassian/confluence.py", line 705, in update_page
    if self.is_page_content_is_already_updated(page_id, body):
  File "/.../venv/lib/python3.6/site-packages/atlassian/confluence.py", line 665, in is_page_content_is_already_updated
    confluence_content = (((self.get_page_by_id(page_id, expand='body.storage') or {})
AttributeError: 'Response' object has no attribute 'get'
```

**Comment by gonchik** [comment]
Hi!

I can not reproduce your problem. :( 
Did you fix it?
Cheers,
Gonchik Tsymzhitov

**Comment by djachkov** [comment]
@mikitachab hi!
I made a quick fix for an issue in #433
And I want to make a more solid solution later.

**Comment by mikitachab** [comment]
Hi @djachkov,
thanks!
I did review your PR, please check it out.

**Comment by mikitachab** [comment]
@djachkov oh, i did not carefully read your comment. Please fill free to ignore my findings if you planing to return to this issue in the future.
