### ISSUE TITLE
bitbucket get_repo renamed repository

### ISSUE THREAD

**Issue by tbugfinder** [atlassian-api/atlassian-python-api#415]
Hi,

I'm running into a weird issue and don't know if this is due to the library or rather bitbucket server. I'm wondering if anybody else noticed such?

Setup:
BitBucket Server: Atlassian Bitbucket v5.13.0
python3.7
atlassian-python-api   1.14.4.1

Steps:

1. Clone a repo from github named "myrepo" using bare

1. Create a bitbucket repo "myrepo"

1. Set remote in myrepo to created bitbucket repo und run `git push --all`

1. Start python, open bitbucket connection and query for the repo "myrepo" using `bitbucket.get_repo('myprojectspace','myrepo')`
=> RESULT: the repo details of myrepo are listed.

1. Rename the repo to "mynewrepo" and query for the repo "myrepo" using `bitbucket.get_repo('myprojectspace','myrepo')`
=> EXPECTED: repo is not listed
=> RESULT: repo is listed as before

1. query for the repo "mynewrepo" using `bitbucket.get_repo('myprojectspace','mynewrepo')`
=> EXPECTED: repo is listed
=> RESULT: repo is listed

1. Move mynewrepo to a different project space "somewhereelse".

1. query for the repo "myrepo" using `bitbucket.get_repo('myprojectspace','myrepo')`
=> EXPECTED: repo is **not** listed
=> RESULT: **repo is listed**, although it's neither in the given project space nor its name/slug matches..

Could anybody explain that?

**Comment by gonchik** [comment]
Hi! 
Is it reproducible on latest version?

**Comment by Spacetown** [comment]
Hi,
bitbucket server redirects the old url to the new url if a repo is renamed. If a new repo with the old name is added, the redirection is removed.

**Comment by Spacetown** [comment]
@gonchik I think this can be closed as the behavior is as described in the last post.

**Comment by gonchik** [comment]
Great, thank!
