### ISSUE TITLE
Is there an api i can use to link an attachment to the confluence wiki

### ISSUE THREAD

**Issue by ganeshaf** [atlassian-api/atlassian-python-api#422]
I have a requirement to capture system configuration details on the linux box and attach the files to the confluence page as links. Currently i'm not finding one. Can someone help. Thank you.

**Comment by gonchik** [comment]
Hi! 
Could you clarify with examples, please?
Cheers,
Gonchik Tsymzhitov

**Comment by ganeshaf** [comment]
Like below i need to attach a file in the body of the page.

![image](https://user-images.githubusercontent.com/14043832/72042939-df0fd100-32d5-11ea-895a-c898afd0096d.png)

**Comment by gonchik** [comment]
@ganeshaf  sorry, I can't see that attachment

**Comment by djachkov** [comment]
@ganeshaf hi there!
You can look at #431 
For your case, you just need to use different content markup.

**Comment by ganeshaf** [comment]
Thank you @djachkov and @gonchik . I'm able to link the file now.
