### ISSUE TITLE
Is there any way to cherry pick a merge to branch with Bitbucket?

### ISSUE THREAD

**Issue by mashayev** [atlassian-api/atlassian-python-api#434]
I'm trying to cherry pick a merge to branch with Bitbucket, same as we can do with `cherry-pick` command, example:
```
git checkout <some-brnach>
git cherry-pick -m1 <some-hash>
```

Thanks for the help :)

**Comment by gonchik** [comment]
Hi @mashayev , 
Bitbucket is just UI for VCS (like git). Hence better to do through git :) 
in UI as I know it's now possible to do that

**Comment by mashayev** [comment]
@gonchik Thanks, but my question was for the Rest API or with the `atlassian-python-api`

**Comment by gonchik** [comment]
So now :(

**Comment by mashayev** [comment]
@gonchik I was trying to check in https://developer.atlassian.com/bitbucket/api/2/reference/resource/ but I didn't find any way, I don't mind it add it as a new feature to atlassian-python-api for [Bitbucket](https://github.com/atlassian-api/atlassian-python-api/blob/master/atlassian/bitbucket.py), just need to understand if it can be done with the API.

**Comment by gonchik** [comment]
Looks like nope :(
