### ISSUE TITLE
Question: Does the documented "username=...." "password=..." access method still work?

### ISSUE THREAD

**Issue by WaterSibilantFalling** [atlassian-api/atlassian-python-api#439]
This is not related to the irrelevant access errors https://github.com/atlassian-api/atlassian-python-api/issues/332 

I know that and API access string is now required   me.name@some.domain.com:oSDFue982759kaljf

I can see the documentation saying use  
"username='me.name@some.domain.com' "  
"password='oSDFue982759kaljf' "

I know that curl access works with a --user  {me.name@some.domain.com:oSDFue982759kaljf}

I can see that 
```
confluence = Confluence(
    url='https://aaabbbccc.atlassian.net/wiki/spaces/P2/pages/88274592837/Foo+my+Bar,
    username='me.name@some.domain.com'',
    password='oSDFue982759kaljf')
```
doesn't work via the atlassian python api, but does work via curl

My question is: Where is my mistake?

**Comment by gonchik** [comment]
Hi! 
could you put that parameter url='https://aaabbbccc.atlassian.net/wiki/' , please ?

**Comment by WaterSibilantFalling** [comment]
Ah, there is my mistake. Solved. 

Is it obvious that the url should only point towards the wiki as a whole?

**Comment by gonchik** [comment]
yeap :) 
maybe it's need to be reviewed
