### ISSUE TITLE
'Jira.issue_exists' and 'Jira.issue_deleted' are invalid

### ISSUE THREAD

**Issue by wy-z** [atlassian-api/atlassian-python-api#444]
https://github.com/atlassian-api/atlassian-python-api/blob/89f9858f1b9df400eb1e1d5ab75cb11b7523372a/atlassian/jira.py#L906
https://github.com/atlassian-api/atlassian-python-api/blob/89f9858f1b9df400eb1e1d5ab75cb11b7523372a/atlassian/jira.py#L919
Unless 'response.raise_for_status' is called, 'requests' does not throw any exceptions.

**Comment by djachkov** [comment]
@wy-z thank you for observation. Can you prepare a PR or I can fix it myself?

**Comment by wy-z** [comment]
https://github.com/atlassian-api/atlassian-python-api/pull/445
Here is my PR, I'm not sure if this is suitable enough~
Feel free to review or close it~
Thank you very much for your contribution. @djachkov
