### ISSUE TITLE
Use Proxies in Confluence

### ISSUE THREAD

**Issue by Jmontes7** [atlassian-api/atlassian-python-api#449]
confluence = Confluence(url=config['CONNECT'].get('CONFserver'), username=config['CONNECT'].get('username'), password=self.decryptPass(), proxies=proxies)
TypeError: __init__() got an unexpected keyword argument 'proxies'

This argument works in the jira class.

**Comment by gonchik** [comment]
Hi! 
hm, confluence and jira are inherited from AtlassianRestAPI -> use the requests.

**Comment by Jmontes7** [comment]
The argument proxies=proxies works with jira class but it does not with confluence. Please, do you have any examples of creating the confluence connection using proxies? . it would be much appreciated

**Comment by gonchik** [comment]
Here was implement exact parameters
#462
