### ISSUE TITLE
jira.issue_create_or_update bug

### ISSUE THREAD

**Issue by Melon-PieldeSapo** [atlassian-api/atlassian-python-api#451]
In the function issue_create_or_update of the jira api, on the 5th line :
del fields["issuekey"] 
fails if there is no issuekey
it shall instead do
fields.pop("issuekey",None)
In the same way as the get in the begining on the function

there is an easy work arround for users: 
Always populate the "issuekey" in your fields dictionary with None by default.

**Comment by gonchik** [comment]
Hi! 

Good caught. I am going to publish the last version
https://github.com/atlassian-api/atlassian-python-api/commit/d14e6aa9c7f69b599e87940803990a63bfad24f3
