### ISSUE TITLE
advanced_mode for service_desk failing

### ISSUE THREAD

**Issue by eos-13** [atlassian-api/atlassian-python-api#453]
Hi,

I tried to use advanced mode for Jira Service Desk. Got an issue with get_service_desks. Using it showed the following error: 
e.cls:[AttributeError], e.bytes:['Response' object has no attribute 'get'],

May I suggest to replace it with:
```
def get_service_desks(self):
    """
        Returns all service desks in the Jira Service Desk application
        with the option to include archived service desks

        :return: Service Desks
        """
    service_desks_list = self.get('rest/servicedeskapi/servicedesk')
    if self.advanced_mode:
        return service_desks_list.json().get('values')
    else:
        return service_desks_list.get('values')
```

Also have quite same issue in get_organisations but did not have time to dig into it

**Comment by gonchik** [comment]
Hi! 
I will be happy if you provide a PR requests :)

**Comment by gonchik** [comment]
Hi! 

done
https://github.com/atlassian-api/atlassian-python-api/commit/597d911b21273ad462225e03ed33de279797dd0b
