### ISSUE TITLE
ServiceDesk - add_users_to_organization - using user_list is deprecated

### ISSUE THREAD

**Issue by eos-13** [atlassian-api/atlassian-python-api#454]
Hi,

According to Jira API documentation, using user_list for adding an user into organization is deprecated. Here is a suggestion of code to implement to goes around deprecation :+1: 

`
def add_users_to_organization_arrayId(self, organization_id, array_list):
    """
    Adds users to an organization
    users_list is a list of accountId

    :param self: object
    :param organization_id: str
    :param array_list: list
    :return:
    """
    logger.info('Adding users...')
    url = 'rest/servicedeskapi/organization/{}/user'.format(organization_id)
    data = {'accountIds': array_list}

    return self.post(url, headers=self.experimental_headers, data=data)
`

Best regards,

**Comment by SLRover** [comment]
Hi, eos-13!

You can make Pull Request. It would be a good decision. 👍 
Or you can wait. 😉
