### ISSUE TITLE
Service Desk API Inconsistency

### ISSUE THREAD

**Issue by Sh4yy** [atlassian-api/atlassian-python-api#456]
Some of the methods in the service desk class return the entire api response and some return the value field in the api response. For example, the get_service_desks method is only returning the values field of the body,
https://github.com/atlassian-api/atlassian-python-api/blob/ff593ed0e56352cad9f88ada6ed336916c774158/atlassian/service_desk.py#L29
and the get_organization method is returning the entire body
https://github.com/atlassian-api/atlassian-python-api/blob/ff593ed0e56352cad9f88ada6ed336916c774158/atlassian/service_desk.py#L277
while both contain the value field in the response. I believe this introduces unnecessary inconsistency to the api and believe that all should follow the same pattern.

**Comment by gonchik** [comment]
Thanks. I have reviewed and do some normalizing. 
https://github.com/atlassian-api/atlassian-python-api/commit/55d9cebb6b61bb70e87c215248e51f72bb0073e0

Next time I will review better the request
