### ISSUE TITLE
How do I authenticate via API token

### ISSUE THREAD

**Issue by fopguy41** [atlassian-api/atlassian-python-api#467]
It seems like the 5 methods provided in the API are

username/password
key/cert
oauth
kerberos
cookie

But to login to the cloud, the recommended way is to use API-token. Can that be done with one of the 5 methods above?

**Comment by MathPlayer** [comment]
@fopguy41 How did you use your API token?

**Comment by MathPlayer** [comment]
I started to use this and the Personal API tokens by adding the custom header in a Serssion object and passing this session to the object being created:
```python
import requests
from atlassian import Bitbucket

s = requests.Session()
s.headers['Authorization'] = 'Bearer <token>'
b = Bitbucket(url='<url>', session=s)
```

**Comment by sunilm-css** [comment]
I tried this
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> from atlassian import Bitbucket
>>> s = requests.Session()
>>> s.headers['Authorization'] = 'Bearer xxxxxxxxxxxxxxxxxxxxxxxx'
>>> b = Bitbucket(url='https://api.bitbucket.org/', session=s)
>>> resp = b.get_users()
>>> print(resp)
{'type': 'error', 'error': {'message': 'Access token expired.'}}

API Token generated from Personal Setting -> App Password -> "Create App Password" is 21 char length. Pretty small to be a bearer token.

**Comment by oaustegard** [comment]
Just in case anyone stumbles across this - the same approach should also work for Jira and Confluence. Note that your Personal access token is likely to be different for each product.

**Comment by rangelrey** [comment]
Tried for confluence without any success. I get the error:

_HTTPError: Current user not permitted to use Confluence_

```
s = requests.Session()

 s.headers['Authorization'] = f'Bearer {access_token}'
 
 confluence_client = Confluence(
        url=confluence_url,
        session=s)
```

Access token was generated [following the docs](https://developer.atlassian.com/cloud/jira/platform/oauth-2-3lo-apps/)

I even tried the oauth2 of the [python atlassian package](https://atlassian-python-api.readthedocs.io/index.html)
token = {"access_token": f'{access_token}', "token_type": "Bearer"}

       ```
 oauth2_dict = {
        "client_id": CONFLUENCE_CLIENT_ID,
        "token": token }

        confluence_client = Confluence(
        url=confluence_url,
        oauth2=oauth2_dict)
```
        
       But I get the same error message.
       
       Any insights ? Thanks in advance

**Comment by joaonc** [comment]
If it's the API token you generated, try
```
jira = Jira(url=JIRA_URL, username='<your@email.com>', password='your_api_token')
```

**Comment by abdullahkhawer** [comment]
The Atlassian user should have access to Confluence app, the `View` and `Add` permissions in the space on it and the `Can edit` permission on the page in that space. Also, you need to create an API token as the password won't work. After doing all of this, it worked for me.

My Python code:
```
from atlassian import Confluence

conf_site = os.getenv("CONFLUENCE_SITE")
conf_user = os.getenv("CONFLUENCE_USER_EMAIL_ID")
conf_pass = os.getenv("CONFLUENCE_USER_TOKEN")

conf = Confluence(url=conf_site, username=conf_user, password=conf_pass)
```

Python script reference: [GitHub > abdullahkhawer > find-secrets-in-code-to-alert-on-slack-and-track-on-confluence > main.py](https://github.com/abdullahkhawer/find-secrets-in-code-to-alert-on-slack-and-track-on-confluence/blob/v1.0.0/main.py)

**Comment by ishankaul1** [comment]
> Tried for confluence without any success. I get the error:
> 
> _HTTPError: Current user not permitted to use Confluence_
> 
> ```
> s = requests.Session()
> 
>  s.headers['Authorization'] = f'Bearer {access_token}'
>  
>  confluence_client = Confluence(
>         url=confluence_url,
>         session=s)
> ```
> 
> Access token was generated [following the docs](https://developer.atlassian.com/cloud/jira/platform/oauth-2-3lo-apps/) (I can authenticate without any issues with GET requests as stated in the documentation, but not with the Atlassian python package)
> 
> I even tried the oauth2 of the [python atlassian package](https://atlassian-python-api.readthedocs.io/index.html)
> 
> ```
> token = {"access_token": f'{access_token}', "token_type": "Bearer"}
> oauth2_dict = {
>        "client_id": CONFLUENCE_CLIENT_ID,
>        "token": token }
> 
> confluence_client = Confluence(
>        url=confluence_url,
>        oauth2=oauth2_dict)
> ```
> 
> But I get the same error message. Any insights ? Thanks in advance

@rangelrey Were you ever able to get it to work using oauth? Running into the exact same issue as you, and the rest of the comments just suggest basic auth

**Comment by ishankaul1** [comment]
update: got it to work. https://community.atlassian.com/t5/Confluence-questions/Re-Re-How-to-connect-to-Atlassian-python-API-using-Auth/qaq-p/2662096/comment-id/304104#M304104
