### ISSUE TITLE
[Bitbucket] Pipelines REST API wrapper

### ISSUE THREAD

**Issue by pylipp** [atlassian-api/atlassian-python-api#475]
Are there plans to wrap the [pipelines API](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Bworkspace%7D/%7Brepo_slug%7D/pipelines/) or parts of it at some point? Would you accept contributions?

**Comment by gonchik** [comment]
Hi!
Yeap, it sounds good and time to implement those rest end points.
Feel free to provide a PR, please.

Cheers, 
Gonchik

**Comment by pylipp** [comment]
Fixed in #477
