### ISSUE TITLE
add issue to sprint

### ISSUE THREAD

**Issue by sumau** [atlassian-api/atlassian-python-api#486]
Would it be possible to add a function to add issues to sprint?

Something like JIRA's add_issue_to_sprint() function:
[]https://skjira.readthedocs.io/en/latest/apidoc.html#jira.JIRA.add_issues_to_sprint

**Comment by isaac-philip** [comment]
sure I'll take this one

**Comment by sumau** [comment]
Thanks appreciate it!

**Comment by isaac-philip** [comment]
I checked that function `add_issues_to_sprint` using the same `jira` python package as per mentioned to be mimicked in our `atlassian-python-api` package.

The function works well to add Issues to a Sprint.
However, the jira api endpoint that it hits is 

    /rest/greenhopper/1.0/sprint/rank

Any clarity on why that api endpoint is used - greenhopper one?

I will be implementing our endpoint on [Jira-8.9.0 REST: Sprint:Move Issues To Sprint](https://docs.atlassian.com/jira-software/REST/8.9.0/#agile/1.0/sprint-moveIssuesToSprint)

Let me know if we need to use the greenhopper one?

**I am expecting guidance on this from the project maintainers.**

**Comment by isaac-philip** [comment]
any comments  ?

**Comment by gonchik** [comment]
Hi! @isaac-philip , 
greenhopper api was so long time ago introduced via Greenhopper app, 
now that name transferred to Jira Agile. 
However, sometimes I still use some where the old rest end point.

Thanks for fixing the request
