### ISSUE TITLE
Looking for example to use bitbucket.upload_file 

### ISSUE THREAD

**Issue by muz3** [atlassian-api/atlassian-python-api#499]
Hi team, when i run bitbucket.get_repo('..'), I could see my newly created empty repo. Then I want to upload a file to my new repo. So I tried to use bitbucket.upload_file, but nothing really happened. I guess I might use a wrong data format? what is the correct data format for content? binary or string?

An example would be really helpful. thanks.

data = {
content: string, ?
message: string,
branch: string
 }

**Comment by tbugfinder** [comment]
I'm also interested in proper call.

**Comment by muz3** [comment]
I ended up using gitpython.
