### ISSUE TITLE
[Confluence] websudo for Confluence

### ISSUE THREAD

**Issue by twang418** [atlassian-api/atlassian-python-api#505]
Hi there, 
Thanks for making this repo, it saves me tons of time. 
One thing I want to know is, I cannot make the request to everything behind the "websudo" on Confluence, even though I added my "password" and "authenticate" as the body in the request. 
Can you please let me know is there a workaround for this issue? 

Regards,
Tong

**Comment by gonchik** [comment]
Hi @wangtong4348 , 
so it's possible in 2 way. 
1. You can switch off the websudo in system
2. Do a parse work with ATL token.

So what exactly do you want to make behind websudo?
Cheers,
Gonchik Tsymzhitov

**Comment by wangtong4348** [comment]
Thanks for your reply @gonchik . 
Basically, we just want to automatically get the license info (like the expiration date), so it needs to get across the websudo.

As a workaround, we tried the following code, please take a look

```
    url = confluence.url + "/doauthenticate.action"
    userAndPass = b64encode((confluence.username + ':' + confluence.password.decode('utf-8')).encode('utf-8')).decode('ascii')
    payload = "password=" + confluence.password.decode(
        'utf-8') + "&authenticate=Confirm&destination=%2Fadmin%2Flicense.action"
    headers = {
        'cache-control': "no-cache",
        'content-type': "application/x-www-form-urlencoded",
        'authorization': "Basic %s" % userAndPass,
    }
    response = requests.request("POST", url, data=payload, headers=headers)
```

Regards,
Tong
