### ISSUE TITLE
Create Sprint

### ISSUE THREAD

**Issue by mattwakeman** [atlassian-api/atlassian-python-api#506]
Can we please get a Create Sprint API?

Passing in the board ID, name, start and end date.

**Comment by isaac-philip** [comment]
For implementing this, was searching the endpoint details for Sprint at [https://docs.atlassian.com/jira-software/REST/8.9.0/#agile/1.0/sprint](https://docs.atlassian.com/jira-software/REST/8.9.0/#agile/1.0/sprint)

Tested it too - this would be correct to use.

Allow me to take this one.

**Comment by isaac-philip** [comment]
Why didn't the issue auto-close since I referenced it in the commit.

Any pointers ?

**Comment by gonchik** [comment]
Released
