### ISSUE TITLE
Could we add labels towards Issue related to specific Atlassian product

### ISSUE THREAD

**Issue by isaac-philip** [atlassian-api/atlassian-python-api#529]
Requesting Maintainers to add labels on the issue(s) which are linked to specific Atlassian product like `jira`, `confluence`, etc

I tried to place but it seems its available for higher privileges only.

It will help in targeting issues to solve by filtering.

**Comment by gonchik** [comment]
@isaac-philip  Thanks for that request :)

**Comment by isaac-philip** [comment]
Thanks @gonchik for creating the Labels.

However you would also need to label the issues which are present.
Because when I click on them I cannot get much results which means that the Issues need individual labelling.

Somehow could you give the Issue creator the privilege to label it - that could greatly save your manual time also.
