### ISSUE TITLE
[confluence] update_or_create fails with 500 error since version 1.16.0

### ISSUE THREAD

**Issue by lars-wolter** [atlassian-api/atlassian-python-api#534]
Hi,

we do updating pages in Confluence by using `update_or_create` method. This worked fine with atlassian-python-api 
version 1.15.6. Since version 1.16.0 the same code breaks by 500 error:

`response = self.confluence.update_or_create(parent_id=parentPageId, title=self.page.get('title'), body=body, representation='storage')`
`   File "/usr/local/lib/python3.6/dist-packages/atlassian/confluence.py", line 1197, in update_or_create      version_comment=version_comment)`
`   File "/usr/local/lib/python3.6/dist-packages/atlassian/confluence.py", line 1062, in update_page response = self.put('rest/api/content/{0}'.format(page_id), data=data)`
`   File "/usr/local/lib/python3.6/dist-packages/atlassian/rest_client.py", line 207, in put trailing=trailing)`
`   File "/usr/local/lib/python3.6/dist-packages/atlassian/rest_client.py", line 161, in request response.raise_for_status()`
`   File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 941, in raise_for_status raise HTTPError(http_error_msg, response=self)`
` requests.exceptions.HTTPError: 500 Server Error:  for url: https://******/rest/api/content/112226271`

I don't find anything about this issue yet. Can you tell me what has changed? Or is it even a bug?

Greetings
Lars

**Comment by chrismahan** [comment]
I am experiencing the same issue. Creating the page when it does not exist works fine. When the page already exists it throws the 500 HTTPError lars-wolter showed.

**Comment by chrismahan** [comment]
when I error-handle and revert to update_page I get the same error

**Comment by chrismahan** [comment]
calling remove_page(...
before attempting the call update_or_create works. Sounds like the error is in the update_page(... call.

**Comment by chrismahan** [comment]
note that having two consecutive single quotes in the body `''` may have caused the update call to fail.

**Comment by gonchik** [comment]
Hi!
What values did you put? 
At the moment, I've not experienced that errors. 
Looks like some situation does not work properly

**Comment by lars-wolter** [comment]
@gonchik: What specific values do you request? The complete body parameter? Please specify.

**Comment by chrismahan** [comment]
When I examined the payload in the source code of conflience.py, line 1195 
`result = self.update_page(parent_id=parent_id, page_id=page_id, title=title, body=body,
                                      representation=representation, minor_edit=minor_edit,
                                      version_comment=version_comment)`
I did not find anything wrong. 
again, the call failed when I had two single quotes in the body. I replaced with `\'` and then it worked fine. I wonder if this is all it is.

**Comment by gonchik** [comment]
So that one will work much better
`body = body.replace('"', '\\"').replace('\n', '\\n').replace("'","\\'")`

**Comment by 99Kies** [comment]
> So that one will work much better
> `body = body.replace('"', '\\"').replace('\n', '\\n').replace("'","\\'")`
~~~
b'{"statusCode":400,"data":{"authorized":false,"valid":true,"allowedInReadOnlyMode":true,"errors":[],"successful":false},"message":"Error parsing xhtml: Unexpected close tag </span>; expected </img>.\\n at [row,col {unknown-source}]: [1,1031]","reason":"Bad Request"}'~~~
hey, How to solve this problem?

**Comment by gonchik** [comment]
@99Kies  it has been fixed later. 
I forgot to close it
