### ISSUE TITLE
A problem with picture content causing page creation to fail!

### ISSUE THREAD

**Issue by 99Kies** [atlassian-api/atlassian-python-api#542]
Hey, guys!
I have a problem!
I've got a body for Page. When I create again, those pages with photos fail!
What should I do!

**Comment by gonchik** [comment]
Hi! 
@99Kies  do you mean a mention to those picture does not work or during update in content format info does not correct?

**Comment by 99Kies** [comment]
emmmm, 
That's what I'm doing:
I synchronize the contents of space A to space B(real-time synchronization )
But When I transfer some articles with pictures, I always report an error.
![image](https://user-images.githubusercontent.com/45918704/88029159-3556aa00-cb6c-11ea-9da2-d8ffa8d3a786.png)
By the way, do you know who has open source software for syncing space articles, it's too much trouble to develop it yourself...

**Comment by 99Kies** [comment]
This is the content of Debug. 
~~~
{"statusCode":400,"data":{"authorized":false,"valid":true,"allowedInReadOnlyMode":true,"errors":[],"successful":false},"message":"A page with this title already exists: A page already exists with the title luping的主页 in the space with key ~huifeng.tang","reason":"Bad Request"}
~~~
I don't think the debug content is consistent with the facts

**Comment by 99Kies** [comment]
Hey, guys.
Is there a good solution to this problem?

**Comment by gonchik** [comment]
Looks like if we have xhtml code validator we can predict those problem

**Comment by 99Kies** [comment]
> 看起来如果我们有xhtml代码验证器，我们可以预测那些问题

But it doesn't seem that friendly to pictures?
