### ISSUE TITLE
[Jira] JQL query returns an empty set

### ISSUE THREAD

**Issue by hockeymikey** [atlassian-api/atlassian-python-api#543]
I'm trying some simple JQL queries just to get all the issues or issues of a project. If I try to get all projects I get an empty result set. I know the query is good because I grab the resulting rest call that it makes and it returns the values in the browser fine. I am using cloud, so I have cloud set to true and am using an api key, it shows that the script accesses the key on the website but for some reason it's not returning the right data. I tried using cookies too from my browser session with similar results. If I try to query for a particular project key like project = "BB" it complains that it doesn't exist, but the project does exist and I do have the right url (company.atlassian.net). Any initial ideas? I worked on it for a few hours last night, went through the files of the project with no real luck.

**Comment by isaac-philip** [comment]
Hello,

so if I understand correctly, 

the issue your mentioning,

1. occurs only on atlassian-cloud? 
2. maybe on atlassian-server or has not been checked?

**Comment by hockeymikey** [comment]
Only tested on atlassian cloud from what I remember.

**Comment by isaac-philip** [comment]
Hello  @hockeymikey  are you still facing the issue, 
I can help troubleshoot it and verify.

Could you give the command & output please.

**Comment by isaac-philip** [comment]
we also have a discord group where we can communicate more frequently, please feel free to join.

**Comment by hockeymikey** [comment]
I think I resolved it, somehow. Thanks!

**Comment by deepanshu11madan** [comment]
@hockeymikey did you by any chance figure out how was it resolved? I am running into a similar problem

**Comment by hockeymikey** [comment]
@deepanshu11madan I think our admin gave me admin permissions I wanna say.

**Comment by isaac-philip** [comment]
> @hockeymikey did you by any chance figure out how was it resolved? I am running into a similar problem

could you share the error here to help us help you
