### ISSUE TITLE
Key/cert based authentication

### ISSUE THREAD

**Issue by maniknarang** [atlassian-api/atlassian-python-api#549]
Hi,

I'm not sure if the API currently provides key/cert based authentication highlighted in the documentation in this pull request: #271

**Comment by indykish** [comment]
It is not supported.

**Comment by jensvog** [comment]
Created a PR to remove it from documentation: https://github.com/atlassian-api/atlassian-python-api/pull/682

**Comment by jensvog** [comment]
Hi @gonchik,
I think the issue can be closed, since the PR is merged.

**Comment by gonchik** [comment]
Thank you, 
you're right!
