### ISSUE TITLE
Add people on the restricted page

### ISSUE THREAD

**Issue by Qinjiaxin** [atlassian-api/atlassian-python-api#554]
How can I add people to the restricted page using API

**Comment by gonchik** [comment]
@Qinjiaxin  Did you figure out? If so feel free provide PR as example :)

**Comment by Qinjiaxin** [comment]
sorry,
did not get your point

**Comment by Qinjiaxin** [comment]
Can you give an example?

**Comment by Qinjiaxin** [comment]
@gonchik

**Comment by gonchik** [comment]
As I understood you wanted like this restricted is this right?
https://community.atlassian.com/t5/Answers-Developer-Questions/Set-Page-Restrictions-using-Confluence-REST-API-v5-5/qaq-p/487662
