### ISSUE TITLE
ServiceDesk - attach_temporary_file

### ISSUE THREAD

**Issue by kilsenp** [atlassian-api/atlassian-python-api#557]
For me, the attachTemporaryFile call is failing. 
Not sure if this is related to my specific server setting, but in the experimentalHeader the content type is set to json, which causes an error to me (I think it was 415).

It can be resolved by just not setting a content type, which is done automatically by the request module when passing a file.

I have a fix in place by just creating the headers in place. If you want, I can create a PR for that.

**Comment by gonchik** [comment]
Hi! 
Feel free to raise a PR
