### ISSUE TITLE
AtlassianRestAPI Client Enhancements

### ISSUE THREAD

**Issue by bl4ckst0ne** [atlassian-api/atlassian-python-api#566]
Hey,
I think the base rest client (`AtlassianRestAPI`) can be improved.
The improvments are small, thus I describe them in one issue.

### Problem
`requests.Session` should be closed after its usage, for closing its underlying adapter. It is a good practice to close the session. Therefore, I believe we should support it.
### Solution
We can add `close_session` (or `close`) method, to support closing the session manually. However, according to the best practices, we can support **context manager** for that. For example:
``` python
with Confluence(...) as confluence:
    # do something...
```
Using context managers allow us to close the session automatically, even if an unhandled exception has occured.

### Problem
For `post`, `put` and `delete` functions, the code is the same, which is a bad practice.

### Solution
We can use partial methods for that, but I don't think it will be an elegant solution here.
Instead, we might use decorators for the exception handling (at least). As a result, we won't have to write try & except blocks for every method.

I did not look for other places where we can use it. Yet, there might be other places where we should use it.

I will be glad to send PR for that :)

**Comment by gonchik** [comment]
Misclick. 
Sounds interesting, I will be to check and see the PR :)

**Comment by bl4ckst0ne** [comment]
I have opened a PR: https://github.com/atlassian-api/atlassian-python-api/pull/577 :-)

**Comment by gonchik** [comment]
That one is merged 👍 
#577
Let's prepare a new release.
