### ISSUE TITLE
Chat group availability

### ISSUE THREAD

**Issue by isaac-philip** [atlassian-api/atlassian-python-api#587]
Hello @gonchik,

   Was checking if we had a messaging/chat group where we can ask queries rather than having to raise issue and ask queries. 

Apologize but I may not be aware if we do have one at the moment?

  Think it could greatly help the project users.

**Comment by gonchik** [comment]
Hi @isaac-philip , 
how about telegram ? at the moment I use that one https://t.me/augspb
maybe to have some open chat channel

Cheers,
Gonchik Tsymzhitov

**Comment by isaac-philip** [comment]
ok i saw it. just dont understand the language hehe.

we could have an english channel in discord/gitter ?

could you help with creation, since ur maintainer would be better if u create, else I can support as needed.

thanks for the response @gonchik ! 🙂

**Comment by isaac-philip** [comment]
Hello @gonchik ,

https://discord.gg/3vX9qb

have created this discord chat channel.

i guess we can have multiple text channels on discord which will allow us to have different languages channels 😁

lemme know if i can proceed with a **badge PR** for this.

_this chat channel will help users to chat/discuss features existing & new to be incorporated._

**Comment by gonchik** [comment]
Hello @isaac-philip ,
First of all , thank you for your initiative
Btw, you made awesome step.
  
Feel free to make  PR with badge

**Comment by isaac-philip** [comment]
Please message here if the [chat-group](https://discord.gg/FCJsvqh) is able to be joined or not.

**Comment by gonchik** [comment]
@isaac-philip  could you transfer ownership of that discord server please?

**Comment by isaac-philip** [comment]
sure, just saw your message in discord 👍
