### ISSUE TITLE
HacktoberFEST participation for project

### ISSUE THREAD

**Issue by isaac-philip** [atlassian-api/atlassian-python-api#599]
`
Maintainers can opt-in to participate by classifying their projects with the hacktoberfest topic. 
`

text from [https://hacktoberfest.digitalocean.com/details/](https://hacktoberfest.digitalocean.com/details/)

Can we include our project too? 😏 

Can get good traffic this month end :sparkles:

**Comment by gonchik** [comment]
interesting

**Comment by isaac-philip** [comment]
whats your opinion on this @gonchik ?

its good move, 15 days remaining.
can benefit from the surge of traffic!

**Comment by gonchik** [comment]
Accepted early unfortunately, did not focus on that deeply :(

**Comment by isaac-philip** [comment]
no worries @gonchik !
