### ISSUE TITLE
[JIRA] do we have JIRA API for importing issues through csv

### ISSUE THREAD

**Issue by isaac-philip** [atlassian-api/atlassian-python-api#600]
❓ do we have JIRA API available for importing issues through csv ?

**Comment by gonchik** [comment]
Hi! 
Nope, just curious, did you find something?

**Comment by isaac-philip** [comment]
Hello  @gonchik !

I tried to check if the Jira Server Option available for the `importing of csv issues`.
It seems this option is available from a plugin - **Jira Importers Plugin** with the functionality called `bulkCreateCsv` at `/secure/BulkCreateSetupPage!default.jspa?externalSystem=com.atlassian.jira.plugins.jira-importers-plugin:bulkCreateCsv`

The main limiter for any REST interaction towards this is that its a multi-stage process executing at the server-end,
- Upload the CSV
- Import To Project i.e. setting Project details where to import
- Map fields
- Map values

**so I conclude that this facility doesn't seem to be REST friendly and so not 4 our usage**

_If we have some improvements in future or something I am unaware, it would be welcome addition to this issue._
