### ISSUE TITLE
[Bitbucket] Suggestion on data model

### ISSUE THREAD

**Issue by chouetz** [atlassian-api/atlassian-python-api#605]
Hello,

Wanted to know if you would agree on some proposal about data model on Bitbucket module, as we have a similar one on our premices and I would be interested by an open-source contribution.
1. Would you agree to have more than one class in Bitbucket module, to represent a Repository and a PullRequest? The idea would be to have smaller class with dedicated methods
```python
b = Bitbucket(url, user, password)
r = b.get_repository(project, repo_name)
p = r.get_pull_request(pr_number)
```
2. Would you agree these class to be UserDict? To be able to get `r['name']` when `r` being an instance of Repository class?

Thanks in advance

**Comment by gonchik** [comment]
Hello! 
1. Fully, agree
2, Yeap!

Cheers,
Gonchik

**Comment by chouetz** [comment]
Ok thanks a lot, then I'll try to contribute asap :)
Thanks

**Comment by gonchik** [comment]
@chouetz  Happy new year! :)

**Comment by Spacetown** [comment]
@gonchik I think this can be closed because it's already implemented.

**Comment by gonchik** [comment]
Thank you! @Spacetown
