### ISSUE TITLE
[Bitbucket] endPoint parameter not optional even-though the docs say so

### ISSUE THREAD

**Issue by csabaszilveszter** [atlassian-api/atlassian-python-api#608]
```
    def delete_branch(self, project, repository, name, end_point):
```
[This method definition](https://github.com/atlassian-api/atlassian-python-api/blob/e3a70b7e136140c87c63390c295ab99c0b1ae3aa/atlassian/bitbucket.py#L705) requires the `end_point` parameter which is passed to the `delete` method as `endPoint`.
But [the bitbucket-server documentation](https://docs.atlassian.com/bitbucket-server/rest/7.6.0/bitbucket-branch-rest.html#idp3) says it's optional.

References like `~` or `HEAD` don't seem to work. 
Only using the full SHA of the last commit ID on the branch (not the short one) as the value for the parameter works.

**Comment by gonchik** [comment]
Thank you're right. 
Also, feel free to make a PullRuquest if you see some changes are needed.

**Comment by gonchik** [comment]
https://github.com/atlassian-api/atlassian-python-api/blob/master/atlassian/bitbucket/__init__.py#L988
