### ISSUE TITLE
[BitBucket]: Suggestion for object oriented interface

### ISSUE THREAD

**Issue by Spacetown** [atlassian-api/atlassian-python-api#610]
My idea is to use a object oriented interface to the API points instead of using functions with many arguments. I've started to work on this on May fork.

All paged APIs shall return a generator object and the paging is down internally, removing all start and limit arguments from the user.
There will also be a single definition of the rest endpoint. 

In the first step I'll skip the outdated cloud entpoints. I also saw that a new function `get_repositories` was introduced instead of updating the existing function. I think that the cloud and the server should be splitted because of the different API structure. 

I've not checked if the current state is runnable. 

What do you think, shall I proceed?

https://github.com/Spacetown/atlassian-python-api/tree/bitbucket-object-oriented

**Comment by gonchik** [comment]
Hi! 

First of all, thank you for your steps. 
So what do you think if we do in 2 steps.

1. Bitbucket for Cloud will in object oriented 
2. The old we will prepare to deprecated the old steps. (Compatibility will be helpful in that steps) as I know a lot of scripts will be reflected. Hence better to keep compatibility
3. Backward with new way for Bitbucket server

Based on that I think we can proceed for start the bitbucket cloud steps

Cheers,
Gonchik

**Comment by Spacetown** [comment]
@gonchik I thought to do it the other way around. But nevertheless l can do it this way.

What Do you think about using `atlassian.bitbucket.cloud` for the cloud Implementation and a different package for the server implementation?
The existing bitbucket package can than use the new object oriented interface. Shall the old function be marked as deprecated

**Comment by gonchik** [comment]
Hi! 
About marking deprecated it's good. Let's start from that. (I hope we will keep it at least a few months)
That one it's so good to me
`atlassian.bitbucket.cloud` interesting to listen other opinions

**Comment by Spacetown** [comment]
@gonchik I've added deprecated decorators in the PR. The version is set to 2.0.1 and ust be updated before merging the PR. Also a example is added how the workspaces, projects and repositories are fetched.
