### ISSUE TITLE
[Bitbucket] Tag deletion does not work

### ISSUE THREAD

**Issue by Xendar** [atlassian-api/atlassian-python-api#619]
Hello,

Using the `delete_tag` method against a Bitbucket server instance, I got an error 405.
Checking the [documentation](https://docs.atlassian.com/bitbucket-server/rest/7.7.1/bitbucket-git-rest.html), it appears that tag deletion goes through the Bitbucket **git** API, so the path should be `rest/git` instead of `rest/api`.

Digging a bit the source code, i think that we would need to add the `api_root` parameter on the methods and sub-methods  invoked by the 
`delete_tag` one. Would that be the right fix?

Thanks

**Comment by Spacetown** [comment]
This error was introduce by a9c6159bcf98992a4bb892a2fb4ad8090c3bd836.
The api_root must be added to the call of `_url_repo_tags(...)` in:
https://github.com/atlassian-api/atlassian-python-api/blob/2ea0484739da991853ae07a5963d4b7caed26c60/atlassian/bitbucket/__init__.py#L1095-L1096

**Comment by Spacetown** [comment]
@Xendar, @gonchik I'm checking the endpoints before the refactoring and the current ones and will create a PR.
