### ISSUE TITLE
there is possiblity to support OAuth2?

### ISSUE THREAD

**Issue by MidoAhmed** [atlassian-api/atlassian-python-api#621]
i'm new user to this great package 👍, and i didn't know that is not supporting OAuth2, so any possibility or plan to support it ?
i need it to consume bitbucket Cloud Rest api 2.0

Thanks in advance.

**Comment by gonchik** [comment]
Hi! 
So Oauth2 is supported you can put token into password field

**Comment by MidoAhmed** [comment]
@gonchik thank you for the reply I will close this issue.
