### ISSUE TITLE
[Bitbucket] : Bitbucket cloud API do not seem to work

### ISSUE THREAD

**Issue by masarani597** [atlassian-api/atlassian-python-api#629]
In our company, we use bitbucket.org cloud product and I am using the following snippet to connect to it.

---------------------------
from atlassian import Bitbucket

def bitbucketHelp():
    bitbucket = Bitbucket(
        url='https://bitbucket.org',
        username='testuser@mycompany.com',
        password='testpassword')
-----------------------------
This does not seem to work. I get the following error.

    raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://bitbucket.org/api/2.0/projects

Am I doing something wrong ? I don't see any examples of how to connect to bitbucket cloud product.

**Comment by Spacetown** [comment]
The URL for the API is `https://api.bitbucket.org`.

**Comment by masarani597** [comment]
Thanks @Spacetown . I really appreciate your quick response. I changed the URL as per you mentioned.


def bitbucketHelp():
    bitbucket = Bitbucket(
        url='https://api.bitbucket.org',
        username='testuser@mycompany.com',
        password='mypassword')

    data = bitbucket.project_list(limit=5)


When I run the above snippet, I get the following error now.

---------------
line 268, in project_list
    return self._get_paged(url, params=params)
AttributeError: 'Bitbucket' object has no attribute '_get_paged'

-----------------

Could you kindly help ? :)

**Comment by Spacetown** [comment]
Please try the change in #630.

**Comment by masarani597** [comment]
Thanks @Spacetown .  I copied your changes in the base.py file and tried this.
---------
    data = list(bitbucket.project_list())
    print(data)
---------

and I get this error.

------------
line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.bitbucket.org/2.0/projects
--------------

**Comment by pablotoledo** [comment]
someone has broken this method!

**Comment by Spacetown** [comment]
@pablotoledo But this error is now related to #604 because this endpoint isn't part of the cloud API.

**Comment by Spacetown** [comment]
I've tested the commit e3a70b7e136140c87c63390c295ab99c0b1ae3aa before the refactoring of the URLs and the cloud isn't working there at all.

**Comment by pablotoledo** [comment]
> @pablotoledo But this error is now related to #604 because this endpoint isn't part of the cloud API.

I'm using bitbucket data center and I'm facing troubles since the ends of October with all new releases. I had to force all my pipelines in my company with 1.17.0

**Comment by Spacetown** [comment]
@pablotoledo At work I'm using bitbucket server with `cloud=False` and at home for testing the https://api.bitbucket.org with `cloud=True`.
I think that there is a problem with the cloud flag. The API version 2 is turned of on https://api.bitbucket.org and therefore the endpoints are not working anymore as described in #604.
Are you using `cloud=True` and the API version 2 is working in the data center?

**Comment by pablotoledo** [comment]
@Spacetown I tried by forcing cloud=False, but I have the same result. This update have broken all compatibility with DataCenter we had in previous versions

**Comment by Spacetown** [comment]
Can you try to use `cloud=True, api_root='rest/api'`? It seems, that in the data center the API version 2.0 is still active.

**Comment by pablotoledo** [comment]
My DataCenter supported version is a 6.7 edition. Let me try tomorrow.

**Comment by Spacetown** [comment]
@pablotoledo I've also updated #630 to use the same API root as in 1.17.7.
