### ISSUE TITLE
[Jira] can't create jira issue

### ISSUE THREAD

**Issue by python-jitser** [atlassian-api/atlassian-python-api#631]
After update Jira to v8.12.3
Python script stopped working with error:
`
requests.exceptions.HTTPError: 400 Client Error:  for url: https://{url}/rest/api/2/issue?updateHistory=false
`
I also update client version atlassian-python-api==2.1.1 but this didn't solve the problem

**Comment by gonchik** [comment]
Hi!
I am using the 8.13 and 8.5 - hm, it works. 

Could you double check the log?

Cheers,
Gonchik Tsymzhitov

**Comment by gonchik** [comment]
@python-jitser  Could you share the log please?

**Comment by gonchik** [comment]
Tested on diff env - so can not reproduce it :(
