### ISSUE TITLE
Confluence: Allow get_group_members() to page through results

### ISSUE THREAD

**Issue by bobgott** [atlassian-api/atlassian-python-api#638]
Confluence.get_group_members() returns response['results'] which works correctly if only 1 request is required.  In my case where there are many members per group, I need to page through the results by incrementing 'start' accordingly.

Perhaps you might want to return just 'response'?

This is easy to work around but thought you might want to address it in your code as well.

[feature request]

**Comment by gonchik** [comment]
Hi! 

@bobgott  Sorry for the delayed answer. 
So you can iterate until you did not get empty collection. 
In that commit provided the more clear example and added the method to provide all users
https://github.com/atlassian-api/atlassian-python-api/commit/1067b58288b2522ce6a45feecd3695e6cb99e991

**Comment by gonchik** [comment]
examples/confluence/confluence_get_group_members.py
