### ISSUE TITLE
bitbucket.set_branching_model broken for Bitbucket Server edition

### ISSUE THREAD

**Issue by aregier** [atlassian-api/atlassian-python-api#641]
Sometime after 1.16.0, when calling the `set_branching_model` API against a Bitbucket Server, a 404 is returned. 
The URL for this api is not set correctly.

1.16.0: `https://myserver.local/bitbucket/rest/branch-utils/1.0/projects/{projectSlug}/repos/{repoSlug}/branchmodel/configuration`

Latest: `https://myserver.local/bitbucket/rest/branch-utils/1.0/rest/api/1.0/projects/{projectSlug}/repos/{repoSlug}/branchmodel/configuration`

**Comment by Spacetown** [comment]
I'm checking this.

**Comment by gonchik** [comment]
#642 thanks for the merge request
