### ISSUE TITLE
confluence.create_page crashes with large body

### ISSUE THREAD

**Issue by lenoqt** [atlassian-api/atlassian-python-api#648]
When trying to input a large string object as body variable the method create_page behaves weird, which ignores completely the parent_id argument when passed or throws back a http 500 error.

```
Traceback (most recent call last):
  File "test.py", line 113, in <module>
    reporter.page_generator()
  File "test.py", line 104, in page_generator
    self.confluence.create_page(space=space, title=title_page, parent_id=parent_page_id, body=body)
  File "/Users/gustavo.barrios/.local/share/virtualenvs/Confluence-F16bH-8I/lib/python3.8/site-packages/atlassian/confluence.py", line 636, in create_page
    response = self.post(url, data=data)
  File "/Users/gustavo.barrios/.local/share/virtualenvs/Confluence-F16bH-8I/lib/python3.8/site-packages/atlassian/rest_client.py", line 290, in post
    response = self.request(
  File "/Users/gustavo.barrios/.local/share/virtualenvs/Confluence-F16bH-8I/lib/python3.8/site-packages/atlassian/rest_client.py", line 228, in request
    response.raise_for_status()
  File "/Users/gustavo.barrios/.local/share/virtualenvs/Confluence-F16bH-8I/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://rakutenmobile.atlassian.net/wiki/rest/api/content
(Confluence) sh-3.2$
```

This is a piece of my code, which basically passes a json string to the method.

```python

def page_generator(self):
   if self.confluence.page_exists(space, self.parent_title):
      title_page = 'Health Check ' + self.timeformat
       body = [json.dumps(x, indent=2) for x in self.hosts]
       self.confluence.create_page(space=space, title=title_page, parent_id=parent_page_id, body=body)
   else:
       raise ValueError("Main page seems to be gone...")
```

**Comment by taro-spb** [comment]
Faced this error in my code. This issue is definitely related to `body=` parameter. Will test more to figure out what causes this issue in my case.

**Comment by taro-spb** [comment]
@lenoqt After some digging, it seems to me that the **500** error is caused by an incorrect payload that is sent in the `body =` argument. Since you did not specify the format of your document in the ` representation=` argument, the API uses `representation = 'storage' `and expects a valid XHTML document in the `body=` argument, and since XHTML format is "strict", any typos or other errors in tags lead to rejection of the document.

Error 500 can be reproduced by sending payload with typo, like this one:
```xhtml
<ac:layou>
</ac:layout>
```

**Comment by lenoqt** [comment]
@taro-spb I made some tests and I was aware that ```'storage'``` argument expects a valid XHTML, but there is some sort of limitation on the size of it, I did split mine into 2 and it worked with no issues now.

**Comment by taro-spb** [comment]
@lenoqt What was the size of your payload?

**Comment by lenoqt** [comment]
5 to 20mb html table
