### ISSUE TITLE
[Bitbucket Cloud] Add more features for pull requests

### ISSUE THREAD

**Issue by sti0** [atlassian-api/atlassian-python-api#662]
When #655  was merged, there are much more things to be implemented:

- [ ] Participant: `is_default_reviewer()`
- [ ] Update / delete comments
- [ ] Activities
- [x] Link pipeline to pull request and vice versa
- [x] Add a new pull request
- [x] Statuses
- [ ] Tasks
- [ ] ...

[API Documentation](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Bworkspace%7D/%7Brepo_slug%7D/pullrequests/%7Bpull_request_id%7D)

**Comment by gonchik** [comment]
@sti0  do you have plan for extending methods
?
