### ISSUE TITLE
Docs: "readthedocs" build failed

### ISSUE THREAD

**Issue by jensvog** [atlassian-api/atlassian-python-api#665]
The documentation on "Read the Docs" looks a little bit older. I saw some builds were running recently, but they were failing: https://readthedocs.org/projects/atlassian-python-api/builds/12652629/

It looks like it is trying to install the `requirements-dev.txt`: `pip install --exists-action=w --no-cache-dir -r requirements-dev.txt`. It fails then because it cannot compile a C library: 
```
error: command 'gcc' failed with exit status 1
----------------------------------------
ERROR: Failed building wheel for kerberos
```

That behavior is expected: 
> We can’t support installing random C binaries on our system, ... [Source](https://docs.readthedocs.io/en/stable/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules)

I think the requirements from `requirements-dev.txt` are not required for the documentation build. I cannot see the admin configuration for the readthedocs-project. I guess you could take down the requirements file from the readthedocs project admin dashboard: [Specifying Dependencies - Read the Docs](https://docs.readthedocs.io/en/stable/guides/specifying-dependencies.html#using-the-project-admin-dashboard).

**Comment by Spacetown** [comment]
The problem is that the `requirement.txt` was added to `requirement-dev.txt`. In the `requirment.txt` kerberos is used and it seems that the shell isn't available on the machine.
When changing the project I suggest to use a [configuration file](https://docs.readthedocs.io/en/stable/config-file/index.html). This is also the recommend way according to the documentation.

**Comment by gonchik** [comment]
@Spacetown Thank you that's exactly needful thing

**Comment by jensvog** [comment]
Good suggestion! I created a PR for introducing a configuration file for Read the Docs: https://github.com/atlassian-api/atlassian-python-api/pull/670. You can have a look. I think this basic file should already be enough. What do you think?

**Comment by Spacetown** [comment]
> Good suggestion! I created a PR for introducing a configuration file for Read the Docs: #670. You can have a look. I think this basic file should already be enough. What do you think?

I'm with you. @gonchik should Check it against the admin configuration and remove this before merging #670.

**Comment by gonchik** [comment]
Checked - it works.
Thank you guys for your contribution!
