### ISSUE TITLE
Portfolio: Wrong repo tag

### ISSUE THREAD

**Issue by jensvog** [atlassian-api/atlassian-python-api#678]
Think there's a typo in the repo tags:
<img width="270" alt="portfolio" src="https://user-images.githubusercontent.com/62656589/103539261-045aff00-4e98-11eb-9e12-be68947942f4.png">
Should be portfolio instead of portofolio. Maybe also other Atlassian services can be added.

**Comment by gonchik** [comment]
Added and fixed 
@jensvog Thank you for caught it :)
