### ISSUE TITLE
[Bitbucket Cloud] Default Reviewer GET-Endpoint not working correctly

### ISSUE THREAD

**Issue by sti0** [atlassian-api/atlassian-python-api#679]
There is a bug in the Default Reviewer GET-Endpoint. The current implementation doesn't work.
https://github.com/atlassian-api/atlassian-python-api/blob/93a47b116ff7fdf4bd092f3780f9dff05d1ff67b/atlassian/bitbucket/cloud/repositories/defaultReviewers.py#L14

According to the [docs](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Bworkspace%7D/%7Brepo_slug%7D/default-reviewers/%7Btarget_username%7D) either `uuid` or `username` are valid values.

The `username` is not visible at any response (I didn't find one), but could used to query a default reviewer directly if known.
Currently the `display_name` is used for querying a default reviewer, but the `display_name` != `username`. 

E.g. `username` could be doejohn2021 but `display_name` could be John Doe.

Maybe there are cases where the `username` matches the `display_name` but thats not the right implementation.
The GET functionality must be changed to return a valid response for both `uuid` and `username`.

Additionally: there is a bug in the BB endpoint itself, therefore it's neccessary to query the `uuid` instead of using it directly ([BCLOUD-20706](https://jira.atlassian.com/browse/BCLOUD-20706)) until this is fixed.

> Workaround
> The existing API works fine for username. While using the same API with UUID of the target_user, use a filter for UUID
> 
> `2.0/repositories/ \{workspace}/\{repo_slug}/default-reviewers?q=uuid="{Target_user_UUID}"`

**Comment by sti0** [comment]
The bug was fixed by Atlassian. But the problem with `display_name` still persists.

**Comment by Spacetown** [comment]
@gonchik I think, this can be closed.
