### ISSUE TITLE
[Confluence] post method missing advanced mode parameter

### ISSUE THREAD

**Issue by VTimofeenko** [atlassian-api/atlassian-python-api#681]
Hi!

I want to include result of POSTing to a private Confluence API in my code to convert markdown to storage format. The way I am trying to use it is:

```python
    url = "rest/tinymce/1/markdownxhtmlconverter"
    # the endpoint returns plain text, need to redefine the default header
    headers = {"Content-Type": "application/json"}
    response = confluence.post(url, data={"wiki": text}, headers=headers)
    return response
```

The output will include a warning and is only intended to be used as fallback.

This endpoint returns plaintext, rather than json:

```
> curl -XPOST -u 'admin:pwd' http://localhost:8090/rest/tinymce/1/markdownxhtmlconverter -H 'Content-Type: application/json' -d '{"wiki": "# AAA\n * one\n * two"}'
<h1>AAA</h1> <ul> <li>one <li>two </ul>
```

so [`_response_handler`](https://github.com/atlassian-api/atlassian-python-api/blob/93a47b116ff7fdf4bd092f3780f9dff05d1ff67b/atlassian/rest_client.py#L139) cannot convert it.

In the [get method definition](https://github.com/atlassian-api/atlassian-python-api/blob/93a47b116ff7fdf4bd092f3780f9dff05d1ff67b/atlassian/rest_client.py#L250), it has a separate parameter "[`advanced_mode`](https://github.com/atlassian-api/atlassian-python-api/blob/93a47b116ff7fdf4bd092f3780f9dff05d1ff67b/atlassian/rest_client.py#L260)", but [post](https://github.com/atlassian-api/atlassian-python-api/blob/93a47b116ff7fdf4bd092f3780f9dff05d1ff67b/atlassian/rest_client.py#L298) method does not have it, relying on advanced_mode property of the AtlassianRestAPI instance. Is this by design?

If not, I would be glad to whip up a quick PR.

**Comment by Spacetown** [comment]
The `advanced_mode` was only needed for the GET. You can add it to the POST or better to all other request methods.

**Comment by VTimofeenko** [comment]
@Spacetown , thanks! I will do that. Does it have other intended meaning other than making the underlying methods return raw response?

**Comment by Spacetown** [comment]
As you can see, also the error handling is turned of.
https://github.com/atlassian-api/atlassian-python-api/blob/6ffed814288d09a755f04c59108d66f9f7a8e59d/atlassian/rest_client.py#L229-L248
