### ISSUE TITLE
[Bitbucket on-prem] Errors processing

### ISSUE THREAD

**Issue by AjaxOdessa** [atlassian-api/atlassian-python-api#688]
Hello,

I just recently started to use this framework and quickly found you myself writing a lot of "safety belts" with try/except. For example, if I want to check whether the Bitbucket repo exist, I would use `bitbucket.get_repo(project_key, repo_slug)` but it must be wrapped into try/except because if repo doesn't exist I won't receive `None` or something similar; instead, framework will fail with an exception and in order to process it properly I am parsing Exception's with something like `e.response.content.decode("utf8")["errors"]` in a try to find out what exactly happened.

I'm wondering what was the driving decision for this approach or maybe I am missing something such as proper errors processing, etc.

**Comment by Spacetown** [comment]
The function isn't for checking.  For checking the error code must be checked. 404 is if the repo wasn't found. There can also be exceptions for other errors. See also
https://github.com/atlassian-api/atlassian-python-api/blob/a2d1fb8e085a2123a1e9f6d9e8054ac7958a0268/atlassian/bitbucket/cloud/repositories/defaultReviewers.py#L56

**Comment by AjaxOdessa** [comment]
Correct me if I'm wrong but you are saying this is the limitation of the REST API, which return results in this way and only?

**Comment by Spacetown** [comment]
Yes, if you take a look at the Rest endpoint there are several http errors used. There should be a function to query if a repo exist. This function must check the error code of the response and refurn a bool value depending on it.

**Comment by AjaxOdessa** [comment]
> This function must check the error code of the response and refurn a bool value depending on it.

I ended up with this
```
    def repo_exists(bitbucket, project_key, repository_slug):
        """
        Check is given combination or project and repository exists and available
        :param bitbucket: Bitbucket connection object.
        :param project_key: Key of the project you wish to look for.
        :param repository_slug: url-compatible repository identifier you wish to look for.
        :return: False if requested repository doesn't exist in the project or not accessible with provided credentials.
        """
        exists = False
        try:
            repo = bitbucket.get_repo(project_key, repository_slug)
            if isinstance(repo, dict) and "slug" in repo and len(str(repo.get("slug"))) > 0:
                exists = True
        except requests.exceptions.HTTPError as e:
            errors = json.loads(e.response.content.decode("utf8"))
            for err in errors["errors"]:
                if "exceptionName" in err and str.endswith(err.get("exceptionName"), "NoSuchRepositoryException"):
                    exists = False
        return exists
```
Will try to find the place for it in this repo.

**Comment by Spacetown** [comment]
@AjaxOdessa Following code should be enough:
```python
        exists = False
        try:
            bitbucket.get_repo(project_key, repository_slug)
            exists = True
        except HTTPError as e:
            # 404: The specified repository does not exist.
            if e.response.status_code == 404:
                pass
            # 401: The currently authenticated user has insufficient permissions to see the specified repository.. Rethrow???

        return False
```

**Comment by AjaxOdessa** [comment]
I might not have found proper REST API endpoint. Well, if there are strict expected codes then indeed it can be simplified to the one you have.

**Comment by Spacetown** [comment]
@AjaxOdessa The endpoint is https://docs.atlassian.com/bitbucket-server/rest/7.9.0/bitbucket-rest.html#idp179

**Comment by AjaxOdessa** [comment]
Yeah, I got it by
>  401: The currently authenticated user…

Thank you!
