### ISSUE TITLE
confluence.py attach_content uses depreciated value for "X-Atlassian-Token" field HTTP header

### ISSUE THREAD

**Issue by pscheir** [atlassian-api/atlassian-python-api#696]
confluence.py attach_content function uses a depreciated HTTP header value for the "X-Atlassian-Token" field

"X-Atlassian-Token" should be set to “no-check” instead of “nocheck”.
See https://developer.atlassian.com/server/confluence/form-token-handling/

Otherwise the following warning will appear in the server log: 
[common.security.jersey.XsrfResourceFilter] hasDeprecatedHeaderValue Use of the 'nocheck' value for X-Atlassian-Token has been deprecated since rest 3.0.0. Please use a value of 'no-check' instead.

Also see PR #697

**Comment by gonchik** [comment]
Thanks for the fix #697
