### ISSUE TITLE
403 Error with create_page or update_page

### ISSUE THREAD

**Issue by i-amikron** [atlassian-api/atlassian-python-api#701]
I try to create a new page by create_page method or edit page by update_page method, but I get 403 error. At the same time, method page_exists and other which only get data (get_all_pages_from_space as example) executes without any troubles. What am I doing wrong?

this code executes succsesful:
`from atlassian import Confluence

confluence = Confluence(  
url='https://url...',  
username='username', 
password='pwd')

status = confluence.page_exists('Space name', 'Page title')

print(status) `

this code returns 403 error: HTTPError: 403 Client Error:  for url: https://smth.ru/rest/api/content
`from atlassian import Confluence

confluence = Confluence(  
url='https://url...',  
username='username', 
password='pwd')

status = confluence.create_page(  
space = 'Space name',
title = 'Page titile',
body = '<p> this page was generated by API </p>' )

print(status) `

**Comment by gonchik** [comment]
Hi @i-amikron , 
Thanks for the question. 
BTW, did you tried to check via GUI (browser) . I would like to understand is this permission issue or something other?

**Comment by i-amikron** [comment]
Hi @gonchik ! I have admin permission at space. I create pages in GUI without problems.

**Comment by gonchik** [comment]
@i-amikron  do we speak about cloud or on-prem installation ?

**Comment by i-amikron** [comment]
@gonchik it's on-prem installation.

**Comment by i-amikron** [comment]
@gonchik  have you any advice for me? what should I try to resolve the problem?

**Comment by i-amikron** [comment]
The problem is related to the peculiarities of authorization. There are no bugs in the module. This issue will be closed.
