### ISSUE TITLE
Template REST API endpoint not `experimental` anymore

### ISSUE THREAD

**Issue by clushie** [atlassian-api/atlassian-python-api#715]
https://github.com/atlassian-api/atlassian-python-api/blob/615219e9d4103ec9807015c4a1f30b36671b3bc9/atlassian/confluence.py#L674

The endpoint changed to `<>/wiki/rest/api/template/<>`, perhaps also with other versions.

I guess now that it's not experimental anymore, would be worth adding this feature to the API documentation too.

**Comment by dephekt** [comment]
Updating the URLs and also making sure the required/optional params are updated with what the current upstream documentation shows. Also adding support for the methods we don't support yet, e.g. create/update content templates, remove templates.

**Comment by dephekt** [comment]
@clushie would you be able to test the changes in #731? I don't have or use Confluence. I was pretty careful to match everything up with the REST API docs but someone should really confirm everything works. The new methods are:

- Confluence.create_or_update_template()
- Confluence.remove_template()

I also modified the following:

- Confluence.get_template_by_id()
- Confluence.get_all_blueprints_from_space()
- Confluence.get_all_templates_from_space()

Example usage for the new methods:
```
# Updating a content template
template_id = "<string>"
name = "<string>"
body = {"value": "<string>", "representation": "view"}
description = "<string>"
labels = [{"prefix": "<string>", "name": "<string>", "id": "<string>", "label": "<string>"}]
space = "<key_string>"

confluence.create_or_update_template(template_id=template_id, name=name, body=body, description=description, labels=labels, space=space)

# Creating a new content template
confluence.create_or_update_template(name, body, description, labels, space)
```
The behavior of the three existing methods I modified remains the same as it was before, except:
in `get_all_templates_from_space()` and `get_all_blueprints_from_space()`, `space` is optional now. E.g. you can run `confluence.get_all_templates_from_space()` without any arguments to get all global content templates.

**Comment by clushie** [comment]
Thank you for your fixes. I will check those changes out, though this week is quite busy so can't promise yet how soon I'll be able to test your changes.

**Comment by dephekt** [comment]
@gonchik I would like to refactor the names for these to match up with the REST API names. For instance:

- `get_template_by_id()` -> `get_content_template()`
- `get_all_templates_from_space()` -> `get_content_templates()`
- `get_all_blueprints_from_space() -> `get_blueprint_templates()`

Doing `get_content_templates()` without providing a `space` argument would result in getting all global content templates. Passing `space` would give you all content templates in the given space. Same behavior for `get_blueprint_templates()`.

Since these were undocumented previously and the function docstrings indicated they were experimental, it's probably safe and best to deal with this now, right? It's unlikely many folks are using these in production and, if they are, they clearly would have seen the methods were experimental and subject to change.

Any thoughts to the contrary before I go ahead and refactor the names?

**Comment by clushie** [comment]
I guess its safe, disclaimer I initially investigated whether I should script something around Atlassian APIs to improve some internal process, so I reviewed/experimented with that library but figured I'll just rework the process itself rather than automating it :). But I'm happy to test it, mostly left the issue because I felt it is worth notifying the maintainers.

**Comment by dephekt** [comment]
My thought is an outsider wouldn't even know these methods (in the Python library) existed unless they came here and looked at the source code, at which point they must have seen the clearly-marked docstrings (and endpoint URL) screaming "EXPERIMENTAL", so there should be no assumption these would not be broken in a future update by either us or the upstream REST API.

I'd rather the method names make sense and align with the REST API which would benefit more people than holding it back for the benefit of the likely small number of folks that would have used it. That said it's up to @gonchik how he wants to actually release the method name changes (e.g. in a minor release or hold it back for a major release).

That said, the methods won't work now anyway until this PR is merged, so I would lean towards a quick minor release.

**Comment by gonchik** [comment]
@dephekt  First of all, thank you for investigating that situation. 

I checked on old production code, looks like it's safe, one problem we are not aware for all other automations. 
So I agree with renaming methods, but sometimes better to have placeholder and deprecation info.  
like this
https://github.com/atlassian-api/atlassian-python-api/blob/master/atlassian/confluence.py#L509

Then we can easier remove in the future releases.

**Comment by dephekt** [comment]
@gonchik good idea. I’ll make a commit for that.
