### ISSUE TITLE
[Bitbucket] Regression: using wrong endpoint for get_changelog in API v1.0

### ISSUE THREAD

**Issue by cauebs** [atlassian-api/atlassian-python-api#737]
After #609, [`get_changelog` uses `/commits` instead of `/compare/commits`](https://github.com/atlassian-api/atlassian-python-api/blob/a605e19ab129dbae030dd4924afda06add2eee62/atlassian/bitbucket/__init__.py#L1665), no matter the API version you set. 

This leads to incorrect behaviour in the tool I'm maintaining. What was the reasoning behind those changes?

This also shows that tests are not covering `[/compare]/commits`.

**Comment by gonchik** [comment]
Hi! 

@cauebs  Suddenly, I did not test that one. 

I will be happy if you provide proper fix

**Comment by Spacetown** [comment]
@cauebs Will you provide a fix? There where several problems after this refactoring. For new endpoints a mockup was introduced to test the functions with a faked response.

**Comment by Spacetown** [comment]
@gonchik This can be closed.

**Comment by cauebs** [comment]
Thanks, @Spacetown!
