### ISSUE TITLE
Bitbucket Cloud lacks the "project_exists" and "repo_exists" methods available for Server

### ISSUE THREAD

**Issue by rodalli** [atlassian-api/atlassian-python-api#757]
So I'm running into this issue whereby attempting to create a project that already exists returns a 400 from Bitbucket Cloud. This seems makes sense and seems expected because looking at the [Projects class](https://github.com/atlassian-api/atlassian-python-api/blob/master/atlassian/bitbucket/cloud/workspaces/projects.py), it's using a POST operation for the "create" method.

Here's my code:

```
bitbucket_cloud = Cloud(
    url = 'https://api.bitbucket.org/',
    username=args.cloud_user,
    password=args.cloud_pass,
    cloud=True
)

args.workspace = "a-workspace-name"

bitbucket_cloud.workspaces.get(args.workspace)projects.create(
    key="ABC",
    name="ABC Project",
    description="A useful description",
    is_private=True
)
```

This returns:

```
Traceback (most recent call last):
  File "src/bbmigrate/cli2.py", line 80, in <module>
    bitbucket_cloud.workspaces.get(args.cloud_workspace).projects.create(
  File "/home/mdavis/.local/share/virtualenvs/bb-server-cloud-migrate-h2IgRdlA/lib/python3.8/site-packages/atlassian/bitbucket/cloud/workspaces/projects.py", line 48, in create
    return self.__get_object(self.post(None, data=data))
  File "/home/mdavis/.local/share/virtualenvs/bb-server-cloud-migrate-h2IgRdlA/lib/python3.8/site-packages/atlassian/rest_client.py", line 303, in post
    response = self.request(
  File "/home/mdavis/.local/share/virtualenvs/bb-server-cloud-migrate-h2IgRdlA/lib/python3.8/site-packages/atlassian/rest_client.py", line 236, in request
    response.raise_for_status()
  File "/home/mdavis/.local/share/virtualenvs/bb-server-cloud-migrate-h2IgRdlA/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.bitbucket.org/2.0/workspaces/a-workspace-name/projects
```

Getting a 400: Bad Request on a POST for an item that already exists totally makes sense. So how do I do this "create" in an idempotent way? I saw that there's also a "Project" method in `projects.py` (singular vs. the plural "Projects") which has an "update" method. The update method uses a PUT instead of a POST, so great, I thought! I just need to use that. But when I try to call that method like so...

```
bitbucket_cloud.workspaces.get(args.workspace)projects.update(
    key="ABC",
    name="ABC Project",
    description="A useful description",
    is_private=True
)
```

I get `AttributeError: 'Projects' object has no attribute 'update'`. Similarly, the lint/debugger in VSCode doesn't show the `update` method as an available method in "projects".

I'm new to Python, so odds are I'm missing something here about how to call this method...but if not, then this seems like a bug.

**Comment by Spacetown** [comment]
The `create` create method creates a project in Bitbucket and not a API object for an existing project. For this you should use the `get` method.

**Comment by rodalli** [comment]
Thank you @Spacetown, that makes sense. So now this works...

```
bitbucket_cloud.workspaces.get(args.workspace)projects.get('ABC').update(
    key="ABC",
    name="ABC Project",
    description="A useful description",
    is_private=True
)
```

Unless ABC project doesn't yet exist. Then I get a 404. To be clear, I'm trying to write a script that takes in a list of projects (key, name, description) and creates them on Bitbucket Cloud in a given workspace.

Does this package provide a way to run a PUT for a project? I'm trying to do this idempotently (create the project if it doesn't exist, or update it if it already exists).

**Comment by rodalli** [comment]
There's a method to do this in the Bitbucket Server implementation, but not for Bitbucket Cloud. Is that a correct statement?

https://github.com/atlassian-api/atlassian-python-api/blob/master/atlassian/bitbucket/__init__.py#L300

**Comment by rodalli** [comment]
I was able to solve my problem by just stealing the logic from the Bitbucket __init__.py code, like so:

```
    try:
        bitbucket_cloud.workspaces.get(args.workspace).projects.get(project['key'])
        proj_exists = True
    except HTTPError as e:
        if e.response.status_code in (401, 404):
            pass
```

Relatively easy to do, but it would be really cool to have the same functionality built right into the Bitbucket Cloud class as well. I'll update the title to reflect the request.
