### ISSUE TITLE
Can't create repositories in Bitbucket Cloud?

### ISSUE THREAD

**Issue by rodalli** [atlassian-api/atlassian-python-api#760]
There's a method available to [create repos in Bitbucket Server](https://github.com/atlassian-api/atlassian-python-api/blob/master/atlassian/bitbucket/server/projects/repos/__init__.py#L14) but I can't find an equivalent method for Bitbucket Cloud.

It seems [this update method](https://github.com/atlassian-api/atlassian-python-api/blob/a863ad779fb7c8199d6ba037fd8189e9710ca7e7/atlassian/bitbucket/cloud/repositories/__init__.py#L163) is the intended equivalent, but I can't figure out how to call this.  I thought this would be the way to do it, but the below gives an error because the instance of 'repositories' has no 'update' member.

```
from atlassian.bitbucket import Cloud

bitbucket_cloud = Cloud(
    url = 'https://api.bitbucket.org/',
    username="fake_username",
    password="password123",
    cloud=True
)

bitbucket_cloud.repositories.update(
    repo_slug="test-repo",
    workspace="AG",
    description="A test repository.",
    is_private=True
)
```

The thing that really throws me for a loop is that there's [a "delete" method](https://github.com/atlassian-api/atlassian-python-api/blob/a863ad779fb7c8199d6ba037fd8189e9710ca7e7/atlassian/bitbucket/cloud/repositories/__init__.py#L175) that's there and can be used from the same class, but not update!

**Comment by Spacetown** [comment]
@rodalli The uodate method is to change the deescription and other properties and is also available on the server. It's a method of an existiong repository which is retrieved with `bitbucket_cloud.repositories.get(...)`. I'll create a PR for this.

**Comment by Spacetown** [comment]
@rodalli I've created the branch https://github.com/Spacetown/atlassian-python-api/tree/add_create_method but I get an error:
```
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.bitbucket.org/2.0/repositories/Spacetown/test1
```

For me te request is as documented in the API https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Bworkspace%7D/%7Brepo_slug%7D#post. Please can you check this on your site?

**Comment by rodalli** [comment]
@Spacetown 

I'm seeing the same result:
```
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.bitbucket.org/2.0/repositories/pgi-tools-archive/mdavis-test
```

I see in the example in the API documentation that the "scm" key is set to "git", but in the data that you're passing to the self.post method, there's no "scm" key. Could that be the issue?

**Comment by Spacetown** [comment]
@rodalli I didn't get that this is realy needed. Now it works.
