### ISSUE TITLE
Need example on how to assign issue

### ISSUE THREAD

**Issue by rayjlinden** [atlassian-api/atlassian-python-api#775]
This project could sure use more examples of how to do even basic things.

For example, I'd like to assign an issue being created to the current user.  I have no idea how to do that...
No example exists to show how to assign to another users either...

Maybe someone could point to working examples elsewhere?  I'd be happy to do a couple of PRs for examples once I figure out how to do some of this stuff.

**Comment by Spacetown** [comment]
Are you talking about issues in this board or with the API in the atlassian products?

**Comment by rayjlinden** [comment]
Ha!  Not in GitHub.  But in the Jira api this repo implements!  When
talking to Jira cloud specifically.

**Comment by Spacetown** [comment]
To assign an issue you should use
https://github.com/atlassian-api/atlassian-python-api/blob/c9b4bb0156983fdff1b9b87bc5376784cb400766/atlassian/jira.py#L928

**Comment by isaac-philip** [comment]
I tried the assign_issue existing endpoint and didn't work for me. That could be the reason @rayjlinden was seeking assistance.

I have pushed the fix which tested works and example added.

Please review.
