### ISSUE TITLE
[JIRA] The bulk_issue() filters project keys too aggressively

### ISSUE THREAD

**Issue by Verequus** [atlassian-api/atlassian-python-api#793]
The regex `r"[A-Z]{1,10}-\d+"`  only allows for project keys which consist of big capital letters (as stated [here](https://confluence.atlassian.com/adminjiraserver/editing-a-project-key-938847080.html)). But it is possible for project keys to have also numbers, if you change the key format (as shown [there](https://confluence.atlassian.com/adminjiraserver/changing-the-project-key-format-938847081.html)).

That means that keys following a different format are discarded as invalid. It is is likely easier to expand the regex to follow the most general rules of project key naming than adding an optional parameter which allows configuration. So I suggest to change the regex to this: `r"[A-Z][A-Z_0-9]*-\d+"`

This also fixes the issue that even only using capital letters, the number of letters is not limited by JIRA.

**Comment by Spacetown** [comment]
In my opinion the regex should be `r"[A-Z][A-Z_0-9]+-\d+"`. According to the documentation the key must be at least 2 characters long.

**Comment by Verequus** [comment]
I've been looking at this at well. But I could only find that restriction for the JIRA standard project keys. Checking the key format change options, it is not mentioned there. I have no JIRA to test if that is a documentation bug or that the true JIRA minimum of project key length is 1, just that this was deemed to short in general.

**Comment by Spacetown** [comment]
What about using `r"\w+-\d+"`? It seems, that the regex is only needed to get a correct JQL string and this should be enough. If the user e.g. uses 123PROJECT-123 which isn't a valid project id because it starts with a number the JQL should be ok. In my opinion it's better to filter the issue_list by the JQL than doing a prefilter by a regex which maybe flter a valid item.

**Comment by Verequus** [comment]
I agree with pushing as much as validation onto the JQL. So your proposal works for me. The filtering cannot distinguish between syntactical correct ticket ids and existing ticket ids anyway.
