### ISSUE TITLE
[Confluence] 501 Server error when attempting to update confluence page

### ISSUE THREAD

**Issue by CermitDFrog** [atlassian-api/atlassian-python-api#797]
When using the update_or_create method for an existing page I am getting a 501 server error. This can be resolved by logging into confluence and visiting the page before updating. Seems to be related to the following bug, which has a code based solution.

https://community.atlassian.com/t5/Atlassian-Cloud-Migration/REST-API-returns-501-Not-Implemented-Error-Until-Page-is-Visited/qaq-p/1703504

**Comment by gonchik** [comment]
Hi! 
it sounds useful


Cheers,
Gonchik

**Comment by CermitDFrog** [comment]
Issued PR. Fix is super minor and should resolve the issue I was having. To be honest I had forgotten about this issue till last week. I was just patching in place on my code. #1051
