### ISSUE TITLE
Username and userkey replaced by accountid in restAPI.  Here is a fix for get_user_details_by_accountid

### ISSUE THREAD

**Issue by pmusolino-rms** [atlassian-api/atlassian-python-api#811]
these parameters are no longer allowed to be passed to the Rest API.  

Created PR for same

**Comment by Spacetown** [comment]
You should create a PR instead of posting the modified function.

**Comment by pmusolino-rms** [comment]
> You should create a PR instead of posting the modified function.

Done.

**Comment by Spacetown** [comment]
@gonchik This can be closed.
