### ISSUE TITLE
Option to fork a repository to another project

### ISSUE THREAD

**Issue by sudarshan2906** [atlassian-api/atlassian-python-api#817]
I am not sure if the bitbucket 1.0 API supports this or not

Currently the function `fork_repository` only supports to fork to the current project. It would be good option if it lets to clone to another project as well

**Comment by zacaryc** [comment]
On this topic I've created https://github.com/atlassian-api/atlassian-python-api/pull/843
I have the same use case to fork to another project, and have been using my local version for a while quite successfully to do that. I still need to work out how/if to turn on 'Fork Syncing' as part of the fork, which I currently just go through and update manually, but one step at a time.

**Comment by zacaryc** [comment]
@sudarshan2906 https://github.com/atlassian-api/atlassian-python-api/pull/843 merged.
