### ISSUE TITLE
Search with jql is not case sensitive

### ISSUE THREAD

**Issue by afedisa** [atlassian-api/atlassian-python-api#834]
Hi,
I'm trying to get all details of a project but `project(key)` is case sensitive, then if project is "**project1**" and your request is "**PROJECT1**" I have no results, correct
If "project1" has issues and I try to get all this issues using `get_all_project_issues("PROJECT1")`, instead of "project1", I get all issues, because _jql_ is not case sensitive.
It can be standar?

thanks

**Comment by Spacetown** [comment]
I think this is a problem of the atlassian jira API. Can you check the http response if you call the project endpoint in the browser with correct and with wrong case?

**Comment by afedisa** [comment]
Hi, 
I've checked and, as you say, is a jira API problem
