### ISSUE TITLE
Get issues of a non exist projetc

### ISSUE THREAD

**Issue by afedisa** [atlassian-api/atlassian-python-api#835]
Hi,
I'm trying to get all issues of a project, the problem is that if it doesn't exist, I can't send the response that says "project doesn't exist or you don't have permissions", I only can send "400 Bad Request".
I see this message in log file, but I can't catch it to be used as response.

Thanks

**Comment by Spacetown** [comment]
I don't get the problem, please provide a code snippet.

**Comment by afedisa** [comment]
Thanks @Spacetown,
The code is very simple:
```
def jira_connector():
    try:
        config_data =  get_credentials()
        jira = Jira(
            url             =   config_data['url'],
            username        =   config_data['username'],
            password        =   config_data['password'],
            advanced_mode   =   bool(config_data['advanced_mode'])
            )
        return jira
    except Exception as err:
        logger.error(f' JIRA_CONNECTOR ERROR: {err}')

jira = atlassian_connection.jira_connector()
result = jira.get_all_project_issues(project_id, fields='*all', start=start, limit=limit)
return response.json(result.json())
```

**Comment by Spacetown** [comment]
You catch it here and return nothing (None):
```python
    except Exception as err:
        logger.error(f' JIRA_CONNECTOR ERROR: {err}')
```

**Comment by afedisa** [comment]
The problem is the module function:
`return self.jql(jql, fields=fields, start=start, limit=limit)["issues"]`
This is response of API, but if the "answer" of the "jql" is an error, that is not catched by API, then in my exception, only receive a "Bad Request" and a message "'Response' object is not subscriptable" because is trying to get "issues" from an object that contains an error

**Comment by Spacetown** [comment]
Can you post the exception message with stack backtrace?

**Comment by Spacetown** [comment]
This is because you set `advanced_mode` to `True` when you create `jira`. In this case the user should handle the errors. See:
https://github.com/atlassian-api/atlassian-python-api/blob/721a4895348fc410b4781f2c1af01b6ddf80b9c5/atlassian/rest_client.py#L233-L237

As a result of this the response doesn't have the required key.
@gonchik What is the reason for the advanced mode? Setting it globaly may cause trouble.

**Comment by gonchik** [comment]
@Spacetown  The reason is the next, 
1. Early we did not handle exceptions.
2. Some users prefer handle exception by own side. 
3. Agree with global level. 

If you have an idea to cover welcome :)

**Comment by Spacetown** [comment]
What about deactivating the advanced mode locally in the jul call? 
Every function doing something with the response should respect the advanced mode or deactivate it.

**Comment by gonchik** [comment]
Why not? 
Also, still unclear how many users are using an advanced mode. 
I used my self that option more than 1 year ago, after just start to skip it as most of info appear in the debug logs .

**Comment by Spacetown** [comment]
I prefer also to deactivate it localy if the function relies on the data and doesn't give it to the user as it is.

**Comment by gonchik** [comment]
So let's do it!
