### ISSUE TITLE
[Confluence] editor="v1" does not work in confluence.create_page()

### ISSUE THREAD

**Issue by eiju-akahane** [atlassian-api/atlassian-python-api#851]
I would like to create a page which uses the old editor to copy old Confluence page as-is.
However, the editor= option only accepts "v2" as a paramter.
confluence.create_page(space, title, body, parent_id=None, type='page', representation='storage', editor='v2')

The confluence.py accepts only "v2" as a parameter.

```
    def create_page(
    :::
        if editor == "v2":
            data["metadata"] = {"properties": {"editor": {"value": "v2"}}}
```

I think the next code works to support "v1" also as a paramter.
```
        if editor is not None and editor in ["v1", "v2"]:
            data["metadata"] = {"properties": {"editor": {"value": editor}}}
```

**Comment by gonchik** [comment]
Hello @eiju-akahane ,
Could you provide a PR request please?

**Comment by eiju-akahane** [comment]
Hi @gonchik ,
I created PR:  https://github.com/atlassian-api/atlassian-python-api/pull/857
Could you review and merge it into your code?

**Comment by gonchik** [comment]
Hi @eiju-akahane , 
sure. 
Thanks for the PR
