### ISSUE TITLE
import secrets broke the compability with older interprets

### ISSUE THREAD

**Issue by StykMartin** [atlassian-api/atlassian-python-api#913]
Hello,

the following commit[0] broke the runtime on older interprets (due to secrets import) even when the project declares to support it.
I believe it is time to move on and stop supporting older interprets or run the CI on top of it, so we are sure that we are not making changes that will break it.

At this point, I believe there is no need to support Python 2 and <= Python 3.5 officially.
﻿
[0] ﻿https://github.com/atlassian-api/atlassian-python-api/commit/e8855284203ea1eb2911b016408973ea9f2f2f16

**Comment by Spacetown** [comment]
I prefer to remove the Autogeneration of the pw. This can be done on user side and not inside API. If a pw is needed by the REST endpoint it should also be a required argument.
Even if 2.7 is EOL it should be supported.

**Comment by StykMartin** [comment]
> I prefer to remove the Autogeneration of the pw. This can be done on user side and not inside API. If a pw is needed by the REST endpoint it should also be a required argument. Even if 2.7 is EOL it should be supported.

I didn't check at first how secrets library is used. But you are completely right. I will post PR making password arg required.
