### ISSUE TITLE
What is the status of support in Python 3.10?

### ISSUE THREAD

**Issue by mbk4** [atlassian-api/atlassian-python-api#917]
Hi!
As I understand from this page [https://pypi.org/project/atlassian-python-api/3.17.0/](https://pypi.org/project/atlassian-python-api/3.17.0/) Python up to maximum of 3.9 is supported. Is the Python 3.10 support planned in the near future?
Thank you for the responses.

**Comment by gonchik** [comment]
Hi! Let me add it

**Comment by mbk4** [comment]
> Hi! Let me add it https://docs.python.org/3/whatsnew/3.10.html

@gonchik Thank you for the reply. So this library is supported in Python 3.10 and it is just the badge missing?

**Comment by gonchik** [comment]
@mbk4 I would say yes.

**Comment by gonchik** [comment]
Now it works well.
