### ISSUE TITLE
limit too small getting branches permissions

### ISSUE THREAD

**Issue by couturiehe01** [atlassian-api/atlassian-python-api#933]
The bitbucket.get_branch_permission() function doesn't provide a way to set a limit greater than 25, whereas more than that can be set in Bitbucket (usually max = 100). Therefore, we can't get all permissions.
Could you please either add a 'limit' parameter, or set the default value to 999 for instance?

**Comment by Spacetown** [comment]
Increasing the limit isn't a solution. The solution would be to call the paged get instead of a normal get inside the function.
