### ISSUE TITLE
Insights

### ISSUE THREAD

**Issue by zerodago** [atlassian-api/atlassian-python-api#950]
Hello, does this library support insights? 
Do you plan to do it? 
Tks

**Comment by gonchik** [comment]
Hello, @zerodago , 
yes, we have a plan to the implementation of that component. 
Cheers,
Gonchik Tsymzhitov

**Comment by zerodago** [comment]
Great! 
Do you have an estimate time?
I look forward to it.
Tks

**Comment by gonchik** [comment]
@zerodago let me focus on that, looks it's going to be more interesting and needful feature

**Comment by gonchik** [comment]
I'm still think better to evaluate with decorators or just like this
https://github.com/atlassian-api/atlassian-python-api/pull/952
