### ISSUE TITLE
503 Server Error: Service Unavailable for url

### ISSUE THREAD

**Issue by DorotaKarkutIntel** [atlassian-api/atlassian-python-api#961]
I am unable to connect to Confluence and Jira. I try to connect with: 
confluence = Confluence(
    url=my_company_url,
    username=username,
    password=password)
Then I try to get page with: 
confluence.get_page_by_id(page_id)
I get  _503 Server Error: Service Unavailable for url_
I have a proxy at my company and I have set up env variables for proxy. It was working fine until about week ago. I didn't change anything in my environment.

**Comment by Spacetown** [comment]
Maybe something on the proxy was changed.

**Comment by Basavaraj-PN** [comment]
I'm experiencing the same issue even on non company devices.

**Comment by gonchik** [comment]
@DorotaKarkutIntel  @Basavaraj-PN could you provide more info please :)

**Comment by DorotaKarkutIntel** [comment]
I found a workaround: 
1. delete files: 
- python-crtifi-win32-init.pth
- distutils-precedence.pth
2. pip install pip-system-certs
