### ISSUE TITLE
Wrong logging level

### ISSUE THREAD

**Issue by BenjaminH-Sogeti** [atlassian-api/atlassian-python-api#967]
# Wrong logging level in service-desk class

Creating a comment log "Creating comment..." at warning level, since it is a normal behavior shouldn't it be at _info_ level ? 

https://github.com/atlassian-api/atlassian-python-api/blob/c03332b57b37d4860e4bc783fb9de43fae7bc713/atlassian/service_desk.py#L239

**Comment by Spacetown** [comment]
@gonchik This can be closed.
