### ISSUE TITLE
 How to call the confluence.append_page() function of the python-api? 

### ISSUE THREAD

**Issue by alxfed** [atlassian-api/atlassian-python-api#983]
What exactly does the parameter 'self' in the function confluence.append_page(self, ...)
on this page https://atlassian-python-api.readthedocs.io/confluence.html mean? 

How am I (of somebody else for that matter) supposed to call this function?
The code on line 1617 and on on this page https://github.com/atlassian-api/atlassian-python-api/blob/master/atlassian/confluence.py is not much of a help.

**Comment by infame-io** [comment]
Looks to me a small error in the documentation @alxfed

**Comment by gonchik** [comment]
Thanks! @infame-io
